using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using CharacterViewer.Rendering;
using CharacterViewer.Rendering.Offscreen;
using NPC_Plugin_Chooser_2.BackEnd.CharacterViewerHost.Adapters;
using NPC_Plugin_Chooser_2.Models;
using NPC_Plugin_Chooser_2.View_Models;
using OpenTK.Graphics.OpenGL4;
using OpenTK.Wpf;

namespace NPC_Plugin_Chooser_2.Views;

/// <summary>
/// Miniature view-only 3D viewport embedded inside a mugshot tile ("Live
/// Tile" mode). Hosts a GLWpfControl bound to a per-tile transient
/// <see cref="VM_InternalMugshotPreview"/> and supports orbit (left-drag),
/// pan (middle-drag) and zoom (wheel) — nothing else: no lighting/render
/// panels, no attire toggles, no selectors, no persistence of camera state.
///
/// The initial camera framing replicates the autogenerated-mugshot framing
/// exactly: the same <see cref="UC_InternalMugshotPreview.BuildAutoFramingSpec"/>
/// spec fed to <see cref="MeshAwareCameraFitter.ApplyTo"/> with the mugshot
/// OUTPUT dimensions as the viewport (the fitter only reads the aspect, and
/// the tile is packed at the output aspect, so the on-screen result matches
/// the PNG the offscreen renderer would produce), or the Manual* orbit state
/// verbatim when the camera mode is Manual — mirroring
/// InternalMugshotGenerator's Auto/Manual branch.
///
/// GL lifecycle follows the same invariants as UC_InternalMugshotPreview
/// (each control mints a private context; all GL work happens in the render
/// callback or with this control's context explicitly current; see that
/// class's ShutdownGl doc for the cross-context ID-collision hazard).
/// Teardown is driven by <see cref="VM_InternalMugshotPreview.RequestViewShutdown"/>:
/// the tile VM raises it when the tile leaves live mode or is disposed, and
/// <see cref="ShutdownGl"/> runs with this control's context current.
/// </summary>
public partial class UC_LiveTileViewport : UserControl
{
    private VM_InternalMugshotPreview? _vm;
    private VM_CharacterViewer? _viewer;
    private Settings? _settings;
    private bool _glStarted;
    private bool _firstRenderProcessed;

    // Installed on the bound viewer so its off-render-callback GL work runs
    // against THIS control's context (same rationale as the preview UC).
    private GlContextPinningMarshaller? _pinningMarshaller;

    // Once the user orbits/pans/zooms, later SceneCommitted events (e.g. from
    // an attire-override apply finishing after the initial commit) must not
    // snap the camera back to the mugshot framing.
    private bool _userAdjustedCamera;

    // Left-drag tracking so a genuine orbit drag can swallow the bubbling
    // MouseLeftButtonUp — the tile template treats that event as "select this
    // appearance mod", which must keep working for plain clicks but would be
    // hostile if every orbit drag also committed a selection.
    private bool _leftDragActive;
    private Point _leftDragStart;
    private bool _leftDragMoved;

    // Private 4x MSAA FBO, blit-resolved into GLWpfControl's backbuffer —
    // identical to the preview UC's setup (GLWpfControl exposes no MSAA knob).
    private int _msaaFbo = -1;
    private int _msaaColorRbo = -1;
    private int _msaaDepthRbo = -1;
    private (int W, int H) _msaaSize = (0, 0);
    private const int MsaaSamples = 4;

    public UC_LiveTileViewport()
    {
        InitializeComponent();
        DataContextChanged += OnDataContextChanged;
        Loaded += (_, _) => TryStartGl();
        GlControl.SizeChanged += (_, _) => TryStartGl();

        // Attached permanently — they no-op without a bound viewer, and the
        // control dies with its tile so there is nothing to detach from.
        GlControl.MouseDown += GlControl_MouseDown;
        GlControl.MouseMove += GlControl_MouseMove;
        GlControl.MouseUp += GlControl_MouseUp;
        GlControl.MouseWheel += GlControl_MouseWheel;
    }

    private void OnDataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
    {
        if (_viewer != null)
        {
            _viewer.SceneCommitted -= OnSceneCommitted;
        }
        if (_vm != null)
        {
            _vm.ViewShutdownRequested -= ShutdownGl;
        }

        _vm = DataContext as VM_InternalMugshotPreview;
        _viewer = _vm?.Viewer;
        _userAdjustedCamera = false;

        InstallContextPinningMarshaller();

        if (_viewer != null)
        {
            // SceneCommitted is the only reliable "Renderer.Meshes populated"
            // signal, which MeshAwareCameraFitter needs — LoadAsync returns
            // before the mesh upload happens on a render tick.
            _viewer.SceneCommitted += OnSceneCommitted;
        }
        if (_vm != null)
        {
            _vm.ViewShutdownRequested += ShutdownGl;
            _settings = SettingsAccessor.GetSettings();
        }

        TryStartGl();
    }

    private void OnSceneCommitted()
    {
        if (Dispatcher.CheckAccess())
        {
            ApplyMugshotFraming();
        }
        else
        {
            Dispatcher.BeginInvoke(new Action(ApplyMugshotFraming));
        }
    }

    /// <summary>
    /// Seeds the camera with the exact autogenerated-mugshot framing (Auto:
    /// mesh-aware fit against the output aspect; Manual: the persisted orbit
    /// state — the same branch InternalMugshotGenerator takes). Skipped once
    /// the user has taken over the camera.
    /// </summary>
    private void ApplyMugshotFraming()
    {
        if (_viewer == null || _settings == null) return;
        if (_userAdjustedCamera) return;
        if (!_viewer.IsSceneReady) return; // Retried on the next SceneCommitted.

        var cfg = _settings.InternalMugshot;
        if (cfg.CameraMode == InternalMugshotCameraMode.Manual)
        {
            _viewer.Camera.Distance = cfg.ManualDistance;
            _viewer.Camera.Azimuth = cfg.ManualAzimuth;
            _viewer.Camera.Elevation = cfg.ManualElevation;
            _viewer.Camera.Target = new OpenTK.Mathematics.Vector3(
                cfg.ManualTargetX, cfg.ManualTargetY, cfg.ManualTargetZ);
            return;
        }

        var framing = UC_InternalMugshotPreview.BuildAutoFramingSpec(cfg);
        try
        {
            // Pass the OUTPUT dimensions, not the tile's: the fitter reads the
            // viewport only for its aspect ratio (distance-for-width), and the
            // mugshot the tile replaces was framed at the output aspect.
            MeshAwareCameraFitter.ApplyTo(_viewer, framing,
                Math.Max(1, cfg.OutputWidth), Math.Max(1, cfg.OutputHeight));
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine(
                "UC_LiveTileViewport: MeshAwareCameraFitter.ApplyTo failed: " + ex.Message);
        }
    }

    // -------- Mouse: orbit / pan / zoom only --------

    private void GlControl_MouseDown(object sender, MouseButtonEventArgs e)
    {
        if (_viewer == null) return;
        if (e.ChangedButton != MouseButton.Left && e.ChangedButton != MouseButton.Middle) return;

        var pos = e.GetPosition(GlControl);
        _viewer.Camera.OnMouseDown((float)pos.X, (float)pos.Y,
            e.LeftButton == MouseButtonState.Pressed,
            middleButton: e.MiddleButton == MouseButtonState.Pressed);
        GlControl.CaptureMouse();
        if (e.ChangedButton == MouseButton.Left)
        {
            _leftDragActive = true;
            _leftDragStart = pos;
            _leftDragMoved = false;
        }
    }

    private void GlControl_MouseMove(object sender, MouseEventArgs e)
    {
        if (_viewer == null) return;
        var pos = e.GetPosition(GlControl);
        _viewer.Camera.OnMouseMove((float)pos.X, (float)pos.Y);
        if (_leftDragActive
            && (Math.Abs(pos.X - _leftDragStart.X) >= SystemParameters.MinimumHorizontalDragDistance
                || Math.Abs(pos.Y - _leftDragStart.Y) >= SystemParameters.MinimumVerticalDragDistance))
        {
            _leftDragMoved = true;
            _userAdjustedCamera = true;
        }
        if (GlControl.IsMouseCaptured
            && Mouse.MiddleButton == MouseButtonState.Pressed)
        {
            _userAdjustedCamera = true;
        }
    }

    private void GlControl_MouseUp(object sender, MouseButtonEventArgs e)
    {
        if (_viewer == null) return;
        _viewer.Camera.OnMouseUp();
        GlControl.ReleaseMouseCapture();

        bool wasDrag = _leftDragActive && _leftDragMoved;
        if (e.ChangedButton == MouseButton.Left)
        {
            _leftDragActive = false;
            _leftDragMoved = false;
        }
        // A real orbit drag must not double as a click: the tile's
        // MouseLeftButtonUp trigger selects the appearance mod.
        if (wasDrag && e.ChangedButton == MouseButton.Left)
        {
            e.Handled = true;
        }
    }

    private void GlControl_MouseWheel(object sender, MouseWheelEventArgs e)
    {
        if (_viewer == null) return;
        _viewer.Camera.OnMouseWheel(e.Delta);
        _userAdjustedCamera = true;
        // Keep the wheel from scrolling the mugshot gallery underneath.
        e.Handled = true;
    }

    // -------- GL init / render / teardown --------

    private void TryStartGl()
    {
        if (_glStarted) return;
        if (_vm == null) return;
        if (!IsLoaded) return;
        if (GlControl.ActualWidth <= 0 || GlControl.ActualHeight <= 0) return;

        var settings = new GLWpfControlSettings
        {
            MajorVersion = 3,
            MinorVersion = 3,
            RenderContinuously = true
        };
        GlControl.Start(settings);
        _glStarted = true;
        InstallContextPinningMarshaller();

        // GLWpfControl bug workaround: visibility-toggle to force the
        // CompositionTarget.Rendering subscription to register.
        GlControl.Visibility = Visibility.Collapsed;
        GlControl.Visibility = Visibility.Visible;
    }

    private void InstallContextPinningMarshaller()
    {
        if (_viewer == null || !_glStarted) return;
        _viewer.RenderThreadMarshaller =
            _pinningMarshaller ??= new GlContextPinningMarshaller(GlControl);
    }

    private void GlControl_OnRender(TimeSpan delta)
    {
        if (_viewer == null) return;

        // Dead-context detection: WPF recreated this UC (or GL was restarted)
        // while the viewer still holds GL IDs minted by the dead context.
        if (!_firstRenderProcessed && _viewer.IsGlInitialized)
        {
            _viewer.HandleGlContextLoss();
            _msaaFbo = -1;
            _msaaColorRbo = -1;
            _msaaDepthRbo = -1;
            _msaaSize = (0, 0);
        }

        if (!_viewer.IsGlInitialized)
        {
            try
            {
                _viewer.InitializeGl(ModuleResourceLocator.ShaderDirectory);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("UC_LiveTileViewport InitializeGl failed: " + ex.Message);
                return;
            }
        }

        _firstRenderProcessed = true;
        _viewer.ProcessPendingScene();

        var src = PresentationSource.FromVisual(GlControl);
        double scaleX = src?.CompositionTarget?.TransformToDevice.M11 ?? 1.0;
        double scaleY = src?.CompositionTarget?.TransformToDevice.M22 ?? 1.0;
        int w = Math.Max(1, (int)(GlControl.ActualWidth * scaleX));
        int h = Math.Max(1, (int)(GlControl.ActualHeight * scaleY));

        GL.GetInteger(GetPName.DrawFramebufferBinding, out int gwpfFbo);

        try
        {
            EnsureMsaaFbo(w, h);

            if (_msaaFbo > 0)
            {
                GL.BindFramebuffer(FramebufferTarget.Framebuffer, _msaaFbo);
                GL.Enable(EnableCap.Multisample);
                _viewer.Renderer.Render(_viewer.Camera, w, h);

                GL.BindFramebuffer(FramebufferTarget.ReadFramebuffer, _msaaFbo);
                GL.BindFramebuffer(FramebufferTarget.DrawFramebuffer, gwpfFbo);
                GL.BlitFramebuffer(
                    0, 0, w, h,
                    0, 0, w, h,
                    ClearBufferMask.ColorBufferBit, BlitFramebufferFilter.Nearest);
            }
            else
            {
                _viewer.Renderer.Render(_viewer.Camera, w, h);
            }
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine("UC_LiveTileViewport Render failed: " + ex.Message);
        }
        finally
        {
            GL.BindFramebuffer(FramebufferTarget.Framebuffer, gwpfFbo);
        }
    }

    private void EnsureMsaaFbo(int width, int height)
    {
        if (_msaaFbo != -1 && _msaaSize == (width, height)) return;

        DestroyMsaaFbo();

        _msaaFbo = GL.GenFramebuffer();
        GL.BindFramebuffer(FramebufferTarget.Framebuffer, _msaaFbo);

        _msaaColorRbo = GL.GenRenderbuffer();
        GL.BindRenderbuffer(RenderbufferTarget.Renderbuffer, _msaaColorRbo);
        GL.RenderbufferStorageMultisample(RenderbufferTarget.Renderbuffer,
            MsaaSamples, RenderbufferStorage.Rgba8, width, height);
        GL.FramebufferRenderbuffer(FramebufferTarget.Framebuffer,
            FramebufferAttachment.ColorAttachment0,
            RenderbufferTarget.Renderbuffer, _msaaColorRbo);

        _msaaDepthRbo = GL.GenRenderbuffer();
        GL.BindRenderbuffer(RenderbufferTarget.Renderbuffer, _msaaDepthRbo);
        GL.RenderbufferStorageMultisample(RenderbufferTarget.Renderbuffer,
            MsaaSamples, RenderbufferStorage.Depth24Stencil8, width, height);
        GL.FramebufferRenderbuffer(FramebufferTarget.Framebuffer,
            FramebufferAttachment.DepthStencilAttachment,
            RenderbufferTarget.Renderbuffer, _msaaDepthRbo);

        var status = GL.CheckFramebufferStatus(FramebufferTarget.Framebuffer);
        if (status != FramebufferErrorCode.FramebufferComplete)
        {
            System.Diagnostics.Debug.WriteLine(
                $"UC_LiveTileViewport: MSAA FBO incomplete: {status} ({width}x{height}, samples={MsaaSamples}). Falling back to direct render.");
            DestroyMsaaFbo();
            return;
        }

        _msaaSize = (width, height);
    }

    private void DestroyMsaaFbo()
    {
        if (_msaaDepthRbo != -1) { GL.DeleteRenderbuffer(_msaaDepthRbo); _msaaDepthRbo = -1; }
        if (_msaaColorRbo != -1) { GL.DeleteRenderbuffer(_msaaColorRbo); _msaaColorRbo = -1; }
        if (_msaaFbo != -1) { GL.DeleteFramebuffer(_msaaFbo); _msaaFbo = -1; }
        _msaaSize = (0, 0);
    }

    /// <summary>
    /// Tears down the bound preview VM's GL resources with THIS control's
    /// context current, then releases the context itself. Same ordered
    /// contract as UC_InternalMugshotPreview.ShutdownGl (see its doc for the
    /// cross-context ID-collision rationale). Idempotent; invoked via
    /// <see cref="VM_InternalMugshotPreview.ViewShutdownRequested"/> when the
    /// tile leaves live mode or its VM is disposed on NPC switch.
    /// </summary>
    public void ShutdownGl()
    {
        try
        {
            GlControl.Context?.MakeCurrent();
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine(
                "UC_LiveTileViewport.ShutdownGl: MakeCurrent failed: " + ex.Message);
        }

        try
        {
            DestroyMsaaFbo();
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine(
                "UC_LiveTileViewport.ShutdownGl: MSAA FBO teardown failed: " + ex.Message);
        }

        try
        {
            if (_vm != null)
            {
                _vm.ViewShutdownRequested -= ShutdownGl;
            }
            _vm?.Dispose();
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine(
                "UC_LiveTileViewport.ShutdownGl: viewer dispose failed: " + ex.Message);
        }

        // Release the context + GLFW window + D3D9Ex device. Must come last —
        // the deletes above need the context alive. Start() is legal again
        // after Dispose, which is exactly what happens when the same tile is
        // toggled back to live mode (a fresh preview VM arrives and
        // OnDataContextChanged → TryStartGl restarts GL).
        try
        {
            GlControl.Dispose();
            _glStarted = false;
            _firstRenderProcessed = false;
            _pinningMarshaller = null;
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine(
                "UC_LiveTileViewport.ShutdownGl: GL context release failed: " + ex.Message);
        }
    }
}
