using System.Security.Cryptography;
using System.Text;
using FluentAssertions;
using NPC_Plugin_Chooser_2.BackEnd;
using NPC_Plugin_Chooser_2.Tests.TestSupport;
using Xunit;

namespace NPC_Plugin_Chooser_2.Tests.Harness;

/// <summary>
/// Deterministic private-static helpers on <see cref="PortraitCreator"/>, reached via
/// <see cref="Reflect.InvokeStatic{TOwner,T}"/> so the heavy instance constructor
/// (which builds a render semaphore from a live <c>Settings</c> and captures
/// AppContext-relative executable paths) never runs.
///
/// Two seams are covered:
///   - <c>IsOlderVersion(string?, string)</c>: pure version-compare semantics.
///   - <c>CalculateSha256(string)</c>: file content hash (touches temp files).
///
/// The instance methods (FindNpcNifPath, GeneratePortraitAsync, RunProcessInternalAsync,
/// IsAutoGenerated, NeedsRegeneration, InitializeAsync, SaveOutputLog) are intentionally
/// not exercised here — they require the external NPCPortraitCreator.exe, a live Mutagen
/// environment / BsaHandler, or PNG fixtures, which belong to the integration wave.
/// </summary>
public class PortraitCreatorStaticTests
{
    // ----- IsOlderVersion: missing / blank pngVersion -> false ----------------

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("\t")]
    public void IsOlderVersion_BlankPngVersion_ReturnsFalse(string? pngVersion)
    {
        // Blank png version means "not an auto-generated mugshot we should touch":
        // the guard returns false so we never overwrite it.
        Reflect.InvokeStatic<PortraitCreator, bool>("IsOlderVersion", pngVersion, "1.0.0")
            .Should().BeFalse();
    }

    // ----- IsOlderVersion: ordering of well-formed versions -------------------

    [Theory]
    [InlineData("1.0.0", "2.0.0")]   // older major
    [InlineData("1.2.3", "1.2.4")]   // older revision
    [InlineData("1.2.0", "1.3.0")]   // older minor
    [InlineData("0.9.9", "1.0.0")]   // crossing major boundary
    public void IsOlderVersion_PngStrictlyOlder_ReturnsTrue(string pngVersion, string exeVersion)
    {
        Reflect.InvokeStatic<PortraitCreator, bool>("IsOlderVersion", pngVersion, exeVersion)
            .Should().BeTrue();
    }

    [Theory]
    [InlineData("2.0.0", "1.0.0")]   // newer major
    [InlineData("1.2.4", "1.2.3")]   // newer revision
    [InlineData("1.0.0", "1.0.0")]   // exactly equal -> not older
    [InlineData("3.1.4", "3.1.4")]   // equal again
    public void IsOlderVersion_PngNewerOrEqual_ReturnsFalse(string pngVersion, string exeVersion)
    {
        Reflect.InvokeStatic<PortraitCreator, bool>("IsOlderVersion", pngVersion, exeVersion)
            .Should().BeFalse();
    }

    [Fact]
    public void IsOlderVersion_TwoComponentVersusThreeComponent_ShorterIsOlder()
    {
        // System.Version treats an undefined Build component as -1, which sorts BEFORE 0.
        // So "1.2" (Build = -1) compares strictly less than "1.2.0" (Build = 0).
        Reflect.InvokeStatic<PortraitCreator, bool>("IsOlderVersion", "1.2", "1.2.0")
            .Should().BeTrue("undefined Build (-1) sorts below 0");

        // ...and the reverse is therefore NOT older.
        Reflect.InvokeStatic<PortraitCreator, bool>("IsOlderVersion", "1.2.0", "1.2")
            .Should().BeFalse();
    }

    [Fact]
    public void IsOlderVersion_TwoComponentEqual_ReturnsFalse()
    {
        Reflect.InvokeStatic<PortraitCreator, bool>("IsOlderVersion", "1.2", "1.2")
            .Should().BeFalse();
    }

    [Theory]
    [InlineData("not-a-version", "1.0.0")]
    [InlineData("1.0.x", "1.0.0")]
    [InlineData("abc", "1.0.0")]
    [InlineData("v1.0.0", "1.0.0")]   // leading 'v' is not parseable by System.Version
    [InlineData("1", "1.0.0")]        // single component is not a valid System.Version
    public void IsOlderVersion_UnparseablePngVersion_ReturnsTrue(string pngVersion, string exeVersion)
    {
        // An unparseable (but non-blank) png version is treated as "definitely stale".
        Reflect.InvokeStatic<PortraitCreator, bool>("IsOlderVersion", pngVersion, exeVersion)
            .Should().BeTrue();
    }

    [Theory]
    [InlineData("1.0.0", "not-a-version")]
    [InlineData("2.5.0", "garbage")]
    [InlineData("1.0.0", "")]   // empty exe version is blank -> TryParse fails -> true
    public void IsOlderVersion_UnparseableExeVersion_ReturnsTrue(string pngVersion, string exeVersion)
    {
        // If we cannot parse the current executable version, err on regenerating.
        Reflect.InvokeStatic<PortraitCreator, bool>("IsOlderVersion", pngVersion, exeVersion)
            .Should().BeTrue();
    }

    [Fact]
    public void IsOlderVersion_BothUnparseable_ReturnsTrue()
    {
        // png is non-blank but unparseable -> first TryParse fails -> true (exe never reached).
        Reflect.InvokeStatic<PortraitCreator, bool>("IsOlderVersion", "foo", "bar")
            .Should().BeTrue();
    }

    [Theory]
    [InlineData("  1.0.0  ", "2.0.0")]   // surrounding whitespace is trimmed before parse
    [InlineData("1.0.0", "  2.0.0  ")]
    [InlineData(" 1.0.0 ", " 1.0.0 ")]   // trimmed equal -> not older
    public void IsOlderVersion_TrimsSurroundingWhitespace(string pngVersion, string exeVersion)
    {
        // The method calls .Trim() on both operands before TryParse, so padded but
        // otherwise valid versions still parse (and would NOT fall into the unparseable->true path).
        var result = Reflect.InvokeStatic<PortraitCreator, bool>("IsOlderVersion", pngVersion, exeVersion);
        var expected = pngVersion.Trim() != exeVersion.Trim() && pngVersion.Trim() == "1.0.0";
        result.Should().Be(expected);
    }

    // ----- CalculateSha256 ----------------------------------------------------

    [Fact]
    public void CalculateSha256_EmptyFile_ReturnsKnownHash()
    {
        using var tmp = new TempDir();
        var path = tmp.WriteText("empty.bin", "");

        var hash = Reflect.InvokeStatic<PortraitCreator, string>("CalculateSha256", path);

        // Well-known SHA-256 of zero bytes.
        hash.Should().Be("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
    }

    [Fact]
    public void CalculateSha256_AbcContent_ReturnsKnownHash()
    {
        using var tmp = new TempDir();
        // Write the exact bytes 'a','b','c' with no BOM / trailing newline.
        var path = tmp.Combine("abc.bin");
        System.IO.File.WriteAllBytes(path, Encoding.ASCII.GetBytes("abc"));

        var hash = Reflect.InvokeStatic<PortraitCreator, string>("CalculateSha256", path);

        // Canonical NIST SHA-256("abc") test vector.
        hash.Should().Be("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");
    }

    [Fact]
    public void CalculateSha256_IsLowercaseHexNoDashes64Chars()
    {
        using var tmp = new TempDir();
        var path = tmp.Combine("blob.bin");
        System.IO.File.WriteAllBytes(path, Encoding.UTF8.GetBytes("some arbitrary content éè"));

        var hash = Reflect.InvokeStatic<PortraitCreator, string>("CalculateSha256", path)!;

        hash.Should().HaveLength(64, "SHA-256 is 32 bytes = 64 hex chars");
        hash.Should().NotContain("-", "the helper strips BitConverter dashes");
        hash.Should().MatchRegex("^[0-9a-f]{64}$", "output is lowercase hex");
        hash.Should().Be(hash.ToLowerInvariant());
    }

    [Fact]
    public void CalculateSha256_MatchesIndependentReferenceImplementation()
    {
        using var tmp = new TempDir();
        var bytes = Encoding.UTF8.GetBytes("The quick brown fox jumps over the lazy dog");
        var path = tmp.Combine("fox.bin");
        System.IO.File.WriteAllBytes(path, bytes);

        var hash = Reflect.InvokeStatic<PortraitCreator, string>("CalculateSha256", path);

        var expected = Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
        hash.Should().Be(expected);
    }

    [Fact]
    public void CalculateSha256_IdenticalContentSameDifferentPath_ProducesSameHash()
    {
        using var tmp = new TempDir();
        var content = "deterministic payload µ 1234567890";
        var a = tmp.WriteText("dir1/a.bin", content);
        var b = tmp.WriteText("dir2/b.bin", content);

        var hashA = Reflect.InvokeStatic<PortraitCreator, string>("CalculateSha256", a);
        var hashB = Reflect.InvokeStatic<PortraitCreator, string>("CalculateSha256", b);

        hashA.Should().Be(hashB, "the hash is content-derived, not path-derived");
    }

    [Fact]
    public void CalculateSha256_DifferentContent_ProducesDifferentHash()
    {
        using var tmp = new TempDir();
        var a = tmp.WriteText("a.bin", "content-A");
        var b = tmp.WriteText("b.bin", "content-B");

        var hashA = Reflect.InvokeStatic<PortraitCreator, string>("CalculateSha256", a);
        var hashB = Reflect.InvokeStatic<PortraitCreator, string>("CalculateSha256", b);

        hashA.Should().NotBe(hashB);
    }
}
