using System.Collections.Generic;
using System.IO;
using FluentAssertions;
using NPC_Plugin_Chooser_2.Models;
using NPC_Plugin_Chooser_2.Tests.TestSupport;
using NPC_Plugin_Chooser_2.View_Models;
using Xunit;

namespace NPC_Plugin_Chooser_2.Tests.Harness;

/// <summary>
/// Covers the self-output eviction guard on <see cref="VM_Mods"/>: a folder that contains this app's own
/// NPC_Token.json marker must never be adopted as an appearance mod, even though its output plugin contains
/// NPC + FaceGen data by content. The token is written up front by the patcher, but an entry adopted before
/// the marker existed persists in Settings.ModSettings; nothing content-based would evict it, so
/// <see cref="VM_Mods.LoadModsFromSettings"/> drops such an entry on reload (and RefreshSingleModSettingAsync
/// drops it on demand). Exercised on a <see cref="Reflect.Uninitialized{T}"/> instance — the skip branch runs
/// before the heavy VM factory is touched, so no DI graph or live environment is needed.
/// </summary>
public class VM_ModsOwnOutputTokenTests
{
    private const string TokenFileName = "NPC_Token.json";

    private static string MakeTempDir(bool withToken)
    {
        var dir = Path.Combine(Path.GetTempPath(), "NpcOwnOutput_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        if (withToken) File.WriteAllText(Path.Combine(dir, TokenFileName), "{}");
        return dir;
    }

    [Fact]
    public void FolderPathsContainOwnOutputToken_TrueOnlyWhenAMarkerIsPresent()
    {
        var withToken = MakeTempDir(withToken: true);
        var withoutToken = MakeTempDir(withToken: false);
        try
        {
            bool Check(params string?[] paths) =>
                Reflect.InvokeStatic<VM_Mods, bool>("FolderPathsContainOwnOutputToken", new List<string?>(paths));

            Check(withToken).Should().BeTrue("the folder contains an NPC_Token.json marker");
            Check(withoutToken).Should().BeFalse("the folder has no marker");
            Check(withoutToken, withToken).Should().BeTrue("any marked folder in the list is sufficient");
            Check().Should().BeFalse("no folders means no marker");
            Check("", null, withoutToken).Should().BeFalse("blank/null paths are ignored");
        }
        finally
        {
            TryDelete(withToken);
            TryDelete(withoutToken);
        }
    }

    [Fact]
    public void LoadModsFromSettings_SkipsAndCachesOwnOutputEntry()
    {
        var outputDir = MakeTempDir(withToken: true);
        try
        {
            var settings = new Settings();
            settings.ModSettings.Add(new ModSetting
            {
                DisplayName = "NPC Output",
                CorrespondingFolderPaths = new List<string> { outputDir }
            });

            var vm = Reflect.Uninitialized<VM_Mods>();
            Reflect.SetField(vm, "_settings", settings);

            var tempList = new List<VM_ModSetting>();
            var loadedDisplayNames = new HashSet<string>();
            var claimedMugshotPaths = new HashSet<string>();

            Reflect.InvokeVoid(vm, "LoadModsFromSettings", tempList, loadedDisplayNames, claimedMugshotPaths);

            tempList.Should().BeEmpty("an own-output entry must not be loaded as an appearance mod");
            loadedDisplayNames.Should().NotContain("NPC Output");
            settings.CachedNonAppearanceMods.Should()
                .ContainKey(outputDir)
                .WhoseValue.Should().Be(VM_Mods.OwnOutputFailureReason,
                    "the folder is cached as non-appearance so the folder scan does not re-add it");
        }
        finally
        {
            TryDelete(outputDir);
        }
    }

    [Fact]
    public void LoadModsFromSettings_KeepsAutoGeneratedEntryEvenIfFolderHasToken()
    {
        // Auto-generated entries (Base Game / Creation Club) normally carry no folder paths, but guard
        // against a spurious eviction: even if such an entry somehow points at a token-bearing folder, the
        // IsAutoGenerated short-circuit must keep it. It reaches the VM factory, which is null on an
        // uninitialized instance, so "kept" manifests as the factory being invoked (NullReferenceException)
        // rather than a clean skip. That distinguishes the two branches without standing up the DI graph.
        var outputDir = MakeTempDir(withToken: true);
        try
        {
            var settings = new Settings();
            settings.ModSettings.Add(new ModSetting
            {
                DisplayName = "Base Game",
                IsAutoGenerated = true,
                CorrespondingFolderPaths = new List<string> { outputDir }
            });

            var vm = Reflect.Uninitialized<VM_Mods>();
            Reflect.SetField(vm, "_settings", settings);

            var act = () => Reflect.InvokeVoid(vm, "LoadModsFromSettings",
                new List<VM_ModSetting>(), new HashSet<string>(), new HashSet<string>());

            // Not skipped -> proceeds to the (null) factory. If the guard wrongly skipped it, no throw
            // would occur and CachedNonAppearanceMods would contain the folder instead.
            act.Should().Throw<Exception>();
            settings.CachedNonAppearanceMods.Should().NotContainKey(outputDir);
        }
        finally
        {
            TryDelete(outputDir);
        }
    }

    private static void TryDelete(string dir)
    {
        try { if (Directory.Exists(dir)) Directory.Delete(dir, true); } catch { /* best effort */ }
    }
}
