using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CharacterViewer.Rendering;
using Mutagen.Bethesda.Plugins;
using NPC_Plugin_Chooser_2.Models;

namespace NPC_Plugin_Chooser_2.BackEnd.CharacterViewerHost;

/// <summary>
/// Render-free scanner behind the Mod Issues tab: walks every eligible
/// appearance mod's NPCs and checks that the assets the ENGINE actually reads
/// exist — the FaceGen NIF + tint, the ArmorAddon world models the resolver
/// would draw (skin parts and the full effective outfit, including
/// SkyPatcher/SPID contests and LeveledItem recursion), the textures baked
/// inside those NIFs, and AlternateTextures TXST entries. Record-resolved
/// paths beyond that are deliberately NOT probed: ground-truth geometry and
/// texture paths live inside the NIFs, so anything reachable from the FaceGen
/// NIF supersedes what the records claim.
///
/// <para>Resolution goes through the same <see cref="NpcMeshResolver"/> +
/// <see cref="GameAssetResolver"/> scope chain the mugshot renderer uses
/// (mirroring <see cref="MeshSurveyRunner"/>), so a "missing" verdict here is
/// exactly a wireframe/white/invisible outcome in a render. Results are cached
/// per mod in <see cref="ModIssuesCache"/> and invalidated by
/// <see cref="ModStateSnapshot"/> + loose-asset-tree drift.</para>
/// </summary>
public sealed class ModIssueScanner
{
    private readonly Settings _settings;
    private readonly NpcMeshResolver _resolver;
    private readonly GameAssetResolver _assetResolver;
    private readonly IBsaArchiveProvider _bsa;
    private readonly FaceGenConsistencyAnalyzer _faceGenConsistency;
    private readonly ModIssuesCache _cache;

    public ModIssueScanner(
        Settings settings,
        NpcMeshResolver resolver,
        GameAssetResolver assetResolver,
        IBsaArchiveProvider bsa,
        FaceGenConsistencyAnalyzer faceGenConsistency,
        ModIssuesCache cache)
    {
        _settings = settings;
        _resolver = resolver;
        _assetResolver = assetResolver;
        _bsa = bsa;
        _faceGenConsistency = faceGenConsistency;
        _cache = cache;
    }

    /// <summary>Progress notification. Units are NPCs, not mods — mods vary from
    /// one NPC to thousands, so a mod-granular bar sits still through the big
    /// ones and then leaps, which reads as a hang. Each mod contributes its NPC
    /// count to <see cref="Total"/>; a cache hit (or the mod-not-installed fast
    /// path) advances <see cref="Completed"/> by the whole mod's weight at once.</summary>
    public sealed record ProgressInfo(int Completed, int Total, string CurrentLabel);

    /// <summary>A mod's contribution to the progress total. Never zero so even a
    /// degenerate entry still ticks the bar when it completes.</summary>
    private static int Weight(ModSetting mod) => Math.Max(1, mod.NpcFormKeys?.Count ?? 0);

    /// <summary>One mod queued for scanning. The snapshot is produced by the
    /// caller (the VM owns snapshot generation) so the scanner stays VM-free.</summary>
    public sealed record ModScanTarget(ModSetting Model, ModStateSnapshot? Snapshot);

    /// <summary>Mods eligible for scanning: installed appearance mods that
    /// provide NPCs. Mugshot-only entries and the synthetic Base Game /
    /// Creation Club entries carry no folder paths, so both fall out of the
    /// folder requirement; IsAutoGenerated is excluded explicitly as a belt.</summary>
    public static bool IsEligible(ModSetting mod)
        => !mod.IsAutoGenerated
           && mod.CorrespondingFolderPaths is { Count: > 0 }
           && mod.NpcFormKeys is { Count: > 0 };

    /// <summary>
    /// Scans the given mods, reusing valid cache entries unless
    /// <paramref name="ignoreCache"/>. Returns the per-mod results actually in
    /// effect after the run (cache hits included). Cancellation preserves every
    /// completed mod (already stored + saved); the in-flight mod is discarded so
    /// a previous valid entry survives.
    /// </summary>
    /// <param name="onModCompleted">Invoked (on a background thread) as each
    /// mod's result becomes final — after a fresh scan is stored, or when a
    /// cache entry is reused — so the UI can display results incrementally
    /// instead of waiting for the whole run.</param>
    public async Task<Dictionary<string, ModIssueScanResult>> RunAsync(
        IReadOnlyList<ModScanTarget> mods,
        bool ignoreCache,
        IProgress<ProgressInfo> progress,
        CancellationToken ct,
        Action<string, ModIssueScanResult>? onModCompleted = null)
    {
        var results = new Dictionary<string, ModIssueScanResult>(StringComparer.OrdinalIgnoreCase);
        if (mods.Count == 0) return results;

        _cache.Load();

        // Opening hundreds of archives can take seconds; do it once, off the UI thread.
        await Task.Run(() => _bsa.EnsureAllArchivesOpened(), ct).ConfigureAwait(false);

        // Parse results shared across mods/NPCs within one run: Skyrim NPCs share
        // body/armor NIFs heavily, and the extraction cache hands back a stable
        // disk path per (bsa, rel), so the resolved path is a safe dedupe key.
        var nifParseCache = new ConcurrentDictionary<string, Lazy<IReadOnlyList<(string ShapeName, IReadOnlyList<string> TexturePaths, bool DrawnInGame)>>>(
            StringComparer.OrdinalIgnoreCase);

        int totalNpcs = mods.Sum(t => Weight(t.Model));
        int completedNpcs = 0;

        bool anyStored = false;
        try
        {
            for (int i = 0; i < mods.Count; i++)
            {
                ct.ThrowIfCancellationRequested();
                var target = mods[i];
                var mod = target.Model;
                int baseNpcs = completedNpcs;

                progress.Report(new ProgressInfo(baseNpcs, totalNpcs, mod.DisplayName));

                var trees = await Task.Run(
                    () => ModIssuesCache.BuildLooseAssetTrees(mod.CorrespondingFolderPaths), ct)
                    .ConfigureAwait(false);

                if (!ignoreCache &&
                    _cache.TryGetValid(mod.DisplayName, target.Snapshot, trees, out var cached))
                {
                    results[mod.DisplayName] = cached;
                    completedNpcs = baseNpcs + Weight(mod);
                    progress.Report(new ProgressInfo(completedNpcs, totalNpcs,
                        $"{mod.DisplayName} (unchanged — cached)"));
                    onModCompleted?.Invoke(mod.DisplayName, cached);
                    continue;
                }

                var result = await Task.Run(
                    () => ScanModAsync(mod, target.Snapshot, trees, nifParseCache,
                        (j, n) => progress.Report(new ProgressInfo(baseNpcs + j, totalNpcs,
                            $"{mod.DisplayName} ({j}/{n} NPCs)")), ct), ct)
                    .ConfigureAwait(false);

                results[mod.DisplayName] = result;
                _cache.Store(mod.DisplayName, result);
                anyStored = true;
                completedNpcs = baseNpcs + Weight(mod);
                progress.Report(new ProgressInfo(completedNpcs, totalNpcs, mod.DisplayName));
                onModCompleted?.Invoke(mod.DisplayName, result);
                // Throttle: persist after each mod so a crash/cancel keeps progress.
                await _cache.SaveAsync().ConfigureAwait(false);
            }

            _cache.Prune(_settings.ModSettings.Select(m => m.DisplayName));
            if (anyStored) await _cache.SaveAsync().ConfigureAwait(false);
            progress.Report(new ProgressInfo(totalNpcs, totalNpcs, "Done."));
        }
        catch (OperationCanceledException)
        {
            if (anyStored) await _cache.SaveAsync().ConfigureAwait(false);
            progress.Report(new ProgressInfo(completedNpcs, totalNpcs, "Cancelled."));
            throw;
        }
        finally
        {
            _assetResolver.SetAdditionalScopes(null);
            _assetResolver.SetAdditionalFolders(null);
        }

        return results;
    }

    private async Task<ModIssueScanResult> ScanModAsync(
        ModSetting mod,
        ModStateSnapshot? snapshot,
        List<LooseAssetTreeSnapshot> trees,
        ConcurrentDictionary<string, Lazy<IReadOnlyList<(string ShapeName, IReadOnlyList<string> TexturePaths, bool DrawnInGame)>>> nifParseCache,
        Action<int, int> reportNpcProgress,
        CancellationToken ct)
    {
        var result = new ModIssueScanResult
        {
            ScanTimeUtc = DateTime.UtcNow,
            Snapshot = snapshot,
            LooseAssetTrees = trees,
        };

        // Fast path: mod effectively uninstalled — every folder is missing or
        // empty. One mod-level issue instead of one per NPC asset.
        bool anyContent = mod.CorrespondingFolderPaths.Any(f =>
        {
            try { return Directory.Exists(f) && Directory.EnumerateFileSystemEntries(f).Any(); }
            catch { return false; }
        });
        if (!anyContent)
        {
            result.Issues.Add(new ModIssue
            {
                Type = ModIssueType.ModNotInstalled,
                AffectedPath = string.Join("; ", mod.CorrespondingFolderPaths),
                Detail = "None of this mod's folders exist (or they are empty) — the mod appears to be uninstalled.",
            });
            result.ScanCompleted = true;
            return result;
        }

        var npcKeys = mod.NpcFormKeys.OrderBy(fk => fk.ToString(), StringComparer.OrdinalIgnoreCase).ToList();
        var issues = new ConcurrentBag<ModIssue>();

        // NPCs run in parallel: the resolver stack is exercised concurrently by
        // the batch mugshot generator already, GameAssetResolver's scope state
        // is AsyncLocal (isolated per task flow), and nifly loads are
        // thread-safe. NIF parses dominate the cost and dedupe via the shared cache.
        int completed = 0;
        using var gate = new SemaphoreSlim(Math.Max(1, Environment.ProcessorCount - 1));
        var tasks = npcKeys.Select(async npcKey =>
        {
            await gate.WaitAsync(ct).ConfigureAwait(false);
            try
            {
                await Task.Run(() => ScanNpc(mod, npcKey, nifParseCache, issues, ct), ct).ConfigureAwait(false);
            }
            finally
            {
                gate.Release();
                int done = Interlocked.Increment(ref completed);
                if (done % 10 == 0 || done == npcKeys.Count) reportNpcProgress(done, npcKeys.Count);
            }
        }).ToList();

        await Task.WhenAll(tasks).ConfigureAwait(false);
        ct.ThrowIfCancellationRequested();

        result.Issues.AddRange(issues
            .OrderBy(iss => iss.NpcDisplayName, StringComparer.OrdinalIgnoreCase)
            .ThenBy(iss => iss.Type)
            .ThenBy(iss => iss.AffectedPath, StringComparer.OrdinalIgnoreCase));
        result.ScannedNpcCount = npcKeys.Count;
        result.ScanCompleted = true;
        return result;
    }

    private void ScanNpc(
        ModSetting mod,
        FormKey npcKey,
        ConcurrentDictionary<string, Lazy<IReadOnlyList<(string ShapeName, IReadOnlyList<string> TexturePaths, bool DrawnInGame)>>> nifParseCache,
        ConcurrentBag<ModIssue> issues,
        CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        string npcName = mod.NpcFormKeysToDisplayName.TryGetValue(npcKey, out var n) ? n : npcKey.ToString();
        // Per-NPC dedupe: the same shape/texture miss can surface through several
        // body parts sharing one NIF.
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        void AddIssue(ModIssueType type, string affectedPath, string? nifPath = null,
            string? shapeName = null, string? referencer = null, string? detail = null,
            bool isOutfit = false)
        {
            if (!seen.Add($"{type}|{nifPath}|{shapeName}|{affectedPath}")) return;
            issues.Add(new ModIssue
            {
                Type = type,
                NpcFormKey = npcKey,
                NpcDisplayName = npcName,
                AffectedPath = affectedPath,
                NifPath = nifPath,
                ShapeName = shapeName,
                ReferencingRecord = referencer,
                Detail = detail,
                IsOutfitIssue = isOutfit,
            });
        }

        try
        {
            // Same scope chain the mugshot renderer would use for this (mod, NPC).
            _assetResolver.SetAdditionalScopes(_resolver.BuildResolutionScopes(mod, npcKey));

            var (npc, resolveHeadPart, resolveRace) = _resolver.ResolveNpcForConsistency(npcKey, mod);
            if (npc == null) return; // Record-level problems are the Validator's domain.

            var appearanceKey = _resolver.ResolveAppearanceNpcKey(npcKey, mod);
            bool shouldHaveFaceGen = OutputValidator.SubjectShouldHaveOwnFaceGen(npc, resolveRace);
            var (faceGenMeshRel, faceGenTintRel) = Auxilliary.GetFaceGenSubPathStrings(appearanceKey, regularized: true);

            if (shouldHaveFaceGen && !_resolver.FaceGenExists(npcKey, mod))
            {
                AddIssue(ModIssueType.MissingFaceGenMesh, faceGenMeshRel,
                    detail: "No FaceGen head mesh anywhere the game would look — this NPC renders with the dark-face/no-head bug.");
            }

            var paths = _resolver.Resolve(npcKey, mod);
            if (paths == null) return;

            // FaceGen tint DDS. Only meaningful for NPCs that own FaceGen.
            if (shouldHaveFaceGen && !string.IsNullOrWhiteSpace(paths.FaceTintPath) &&
                ResolveToDisk(paths.FaceTintPath!, allowLoadOrderFallback: false) == null)
            {
                AddIssue(ModIssueType.MissingFaceGenTint, faceGenTintRel,
                    detail: "FaceGen tint texture is missing — faces typically render grey/mismatched without it.");
            }

            // The NPC's own drawn meshes (skin ARMA world models + FaceGen head).
            // No weight-sibling checks here: ResolvedNpcMeshPaths carries no
            // weight-slider flag, and without it a single-weight skin file is
            // indistinguishable from a genuinely missing counterpart.
            var nifJobs = new List<NifJob>();
            CheckMesh(paths.BodyMeshPath, "Skin ARMA (Body)", false, false, false, nifJobs, AddIssue);
            CheckMesh(paths.HandsMeshPath, "Skin ARMA (Hands)", false, false, false, nifJobs, AddIssue);
            CheckMesh(paths.FeetMeshPath, "Skin ARMA (Feet)", false, false, false, nifJobs, AddIssue);
            CheckMesh(paths.HairMeshPath, "Worn hair ARMA", false, false, false, nifJobs, AddIssue);
            CheckMesh(paths.TailMeshPath, "Tail ARMA", false, false, false, nifJobs, AddIssue);

            // FaceGen head: existence already handled above (FaceGenExists knows
            // the renderer's vanilla-loose-skip rule, which plain resolution
            // doesn't), so only queue the texture walk when it resolves.
            string? headDisk = ResolveToDisk(paths.HeadMeshPath, allowLoadOrderFallback: false);
            if (headDisk != null)
            {
                nifJobs.Add(new NifJob(headDisk, paths.HeadMeshPath!, "FaceGen head", false, IsFaceGen: true));
            }

            // Full effective outfit (incl. headgear): what the renderer would
            // actually dress the NPC in, LeveledItems and runtime distributors included.
            IReadOnlyList<MeshOverride> overrides;
            try
            {
                overrides = _resolver.ResolveAttireMeshOverrides(npcKey, mod,
                    includeDefaultOutfit: true, includeHeadgear: true);
            }
            catch
            {
                overrides = Array.Empty<MeshOverride>();
            }

            foreach (var over in overrides)
            {
                ct.ThrowIfCancellationRequested();
                if (string.IsNullOrWhiteSpace(over.MeshPath)) continue;
                // Weight siblings only when the ARMA's weight slider is on for
                // this sex — the engine's own signal that a _0/_1 pair exists.
                CheckMesh(over.MeshPath, over.Key, over.AllowLoadOrderFallback,
                    isOutfit: true, checkWeightSibling: over.HasWeightVariants, nifJobs, AddIssue);

                // AlternateTextures (MODS): the one record-side texture channel the
                // engine applies over NIF-baked paths.
                if (over.AlternateTextures != null)
                {
                    foreach (var spec in over.AlternateTextures)
                    {
                        foreach (var tex in spec.Textures.Values)
                        {
                            CheckAltTexture(tex, over, spec.ShapeName, AddIssue);
                        }
                    }
                }
                else if (over.ShapeTextures != null)
                {
                    foreach (var (shapeName, slots) in over.ShapeTextures)
                    {
                        foreach (var tex in slots.Values)
                        {
                            CheckAltTexture(tex, over, shapeName, AddIssue);
                        }
                    }
                }
            }

            // Textures baked inside every rendered NIF — ground truth for what the
            // engine samples. Per-texture verdicts, grouped per shape via ShapeName.
            foreach (var job in nifJobs)
            {
                ct.ThrowIfCancellationRequested();
                IReadOnlyList<(string ShapeName, IReadOnlyList<string> TexturePaths, bool DrawnInGame)> byShape;
                try
                {
                    byShape = nifParseCache.GetOrAdd(job.DiskPath,
                        dp => new Lazy<IReadOnlyList<(string, IReadOnlyList<string>, bool)>>(
                            () => NifHandler.GetTexturesByShape(dp),
                            LazyThreadSafetyMode.ExecutionAndPublication)).Value;
                }
                catch
                {
                    continue; // Unparseable NIF — the renderer has its own reporting for that.
                }

                foreach (var (shapeName, texturePaths, drawnInGame) in byShape)
                {
                    // A shape the engine cannot draw cannot render untextured
                    // (wig mods keep alpha-0 hair shapes whose textures were
                    // never meant to be installed).
                    if (!drawnInGame) continue;

                    foreach (var tex in texturePaths)
                    {
                        if (string.IsNullOrWhiteSpace(tex)) continue;
                        // The face tint is CPU-blended from the FaceGen ladder,
                        // not sampled from disk by this path.
                        if (job.IsFaceGen && !string.IsNullOrEmpty(paths.FaceTintPath) &&
                            (paths.FaceTintPath!.Contains(tex, StringComparison.OrdinalIgnoreCase) ||
                             tex.Contains(faceGenTintRel, StringComparison.OrdinalIgnoreCase)))
                        {
                            continue;
                        }
                        if (!Auxilliary.TryRegularizePath(tex, out var rel) || string.IsNullOrWhiteSpace(rel)) continue;
                        if (ResolveToDisk(rel, job.AllowLoadOrderFallback) != null) continue;

                        AddIssue(ModIssueType.MissingNifTexture, rel,
                            nifPath: job.GamePath,
                            shapeName: string.IsNullOrWhiteSpace(shapeName) ? "(unnamed shape)" : shapeName,
                            referencer: job.Referencer,
                            isOutfit: job.IsOutfit);
                    }
                }
            }

            // Dark-face class: records vs. the baked FaceGen shapes.
            if (headDisk != null)
            {
                try
                {
                    var analysis = _faceGenConsistency.Analyze(npc, resolveHeadPart, resolveRace, headDisk);
                    if (analysis.HasMismatch)
                    {
                        AddIssue(ModIssueType.DarkFaceMismatch, faceGenMeshRel,
                            nifPath: paths.HeadMeshPath,
                            detail: analysis.BuildReason(scope: FaceGenConsistencyAnalyzer.ReasonScope.SelectedMod));
                    }
                }
                catch
                {
                    // Best-effort, mirroring the mugshot generator: an analyzer
                    // failure must not fail the scan.
                }
            }
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch
        {
            // One NPC's failure must not sink the mod's scan.
        }
        finally
        {
            _assetResolver.SetAdditionalScopes(null);
        }
    }

    private sealed record NifJob(string DiskPath, string GamePath, string Referencer,
        bool AllowLoadOrderFallback, bool IsFaceGen = false, bool IsOutfit = false);

    private delegate void AddIssueDelegate(ModIssueType type, string affectedPath, string? nifPath = null,
        string? shapeName = null, string? referencer = null, string? detail = null, bool isOutfit = false);

    private void CheckMesh(string? gamePath, string referencer, bool allowLoadOrderFallback,
        bool isOutfit, bool checkWeightSibling,
        List<NifJob> nifJobs, AddIssueDelegate addIssue)
    {
        if (string.IsNullOrWhiteSpace(gamePath)) return;

        string? disk = ResolveToDisk(gamePath, allowLoadOrderFallback);
        if (disk == null)
        {
            addIssue(ModIssueType.MissingArmaMesh, gamePath, referencer: referencer,
                detail: "The mesh could not be found in the mod, vanilla archives, or the Data folder — it will not render.",
                isOutfit: isOutfit);
            return;
        }

        nifJobs.Add(new NifJob(disk, gamePath!, referencer, allowLoadOrderFallback, IsOutfit: isOutfit));

        // _0/_1 weight sibling: only when the source ARMA's weight slider is
        // enabled — then the engine morphs between both files and a missing
        // counterpart pops or crashes at non-matching weights. With the slider
        // off, a lone weight file is the normal shipping shape.
        if (!checkWeightSibling) return;
        string? sibling = DeriveWeightSibling(gamePath!);
        if (sibling != null && ResolveToDisk(sibling, allowLoadOrderFallback) == null)
        {
            addIssue(ModIssueType.MissingWeightSibling, sibling, referencer: referencer,
                detail: $"The weight counterpart of {Path.GetFileName(gamePath)} is missing.",
                isOutfit: isOutfit);
        }
    }

    private void CheckAltTexture(string texPath, MeshOverride over, string shapeName,
        AddIssueDelegate addIssue)
    {
        if (string.IsNullOrWhiteSpace(texPath)) return;
        if (!Auxilliary.TryRegularizePath(texPath, out var rel) || string.IsNullOrWhiteSpace(rel)) return;
        if (ResolveToDisk(rel, over.AllowLoadOrderFallback) != null) return;

        addIssue(ModIssueType.MissingAltTexture, rel, over.MeshPath,
            string.IsNullOrWhiteSpace(shapeName) ? "(unnamed shape)" : shapeName, over.Key,
            "An AlternateTextures entry points at this texture; the shape it retextures will render untextured.",
            isOutfit: true);
    }

    /// <summary>Resolves a game path (or passes through an already-rooted disk
    /// path) to an on-disk file via the renderer's scope chain. Null = missing.</summary>
    private string? ResolveToDisk(string? path, bool allowLoadOrderFallback)
    {
        if (string.IsNullOrWhiteSpace(path)) return null;
        try
        {
            if (Path.IsPathRooted(path)) return File.Exists(path) ? path : null;
            using (_assetResolver.PushLoadOrderFallback(allowLoadOrderFallback))
            {
                return _assetResolver.ResolveAssetSource(path!).ResolvedDiskPath;
            }
        }
        catch
        {
            return null;
        }
    }

    /// <summary>Returns the _0/_1 weight-sibling path of a world-model NIF, or
    /// null when the filename doesn't follow the weight-pair convention.</summary>
    internal static string? DeriveWeightSibling(string nifPath)
    {
        if (string.IsNullOrWhiteSpace(nifPath)) return null;
        if (nifPath.EndsWith("_0.nif", StringComparison.OrdinalIgnoreCase))
            return nifPath[..^"_0.nif".Length] + "_1.nif";
        if (nifPath.EndsWith("_1.nif", StringComparison.OrdinalIgnoreCase))
            return nifPath[..^"_1.nif".Length] + "_0.nif";
        return null;
    }
}
