using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CharacterViewer.Rendering;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using NPC_Plugin_Chooser_2.Models;

namespace NPC_Plugin_Chooser_2.BackEnd.CharacterViewerHost;

/// <summary>
/// Render-free scanner behind the Mod Issues tab: walks every eligible
/// appearance mod's NPCs and checks that the assets the ENGINE actually reads
/// exist — the FaceGen NIF + tint, the ArmorAddon world models the resolver
/// would draw (skin parts and the full effective outfit, including
/// SkyPatcher/SPID contests and LeveledItem recursion), the textures baked
/// inside those NIFs, and AlternateTextures TXST entries. Record-resolved
/// paths beyond that are deliberately NOT probed: ground-truth geometry and
/// texture paths live inside the NIFs, so anything reachable from the FaceGen
/// NIF supersedes what the records claim.
///
/// <para>Resolution goes through the same <see cref="NpcMeshResolver"/> +
/// <see cref="GameAssetResolver"/> scope chain the mugshot renderer uses
/// (mirroring <see cref="MeshSurveyRunner"/>), so a "missing" verdict here is
/// exactly a wireframe/white/invisible outcome in a render. Results are cached
/// per mod in <see cref="ModIssuesCache"/> and invalidated by
/// <see cref="ModStateSnapshot"/> + loose-asset-tree drift.</para>
/// </summary>
public sealed class ModIssueScanner
{
    private readonly Settings _settings;
    private readonly NpcMeshResolver _resolver;
    private readonly GameAssetResolver _assetResolver;
    private readonly IBsaArchiveProvider _bsa;
    private readonly FaceGenConsistencyAnalyzer _faceGenConsistency;
    private readonly ModIssuesCache _cache;

    /// <summary>(folder, mod display name) pairs over every ModSetting folder,
    /// longest folder first, rebuilt per run. Attributes a resolved asset's
    /// disk/BSA path to the installed mod that supplies it — outfit meshes
    /// usually come from an outfit mod, not the appearance mod under scan, and
    /// the report should say so (<see cref="ModIssue.SourceModName"/>).</summary>
    private List<(string Folder, string ModName)> _folderOwners = new();

    public ModIssueScanner(
        Settings settings,
        NpcMeshResolver resolver,
        GameAssetResolver assetResolver,
        IBsaArchiveProvider bsa,
        FaceGenConsistencyAnalyzer faceGenConsistency,
        ModIssuesCache cache,
        EnvironmentStateProvider env)
    {
        _settings = settings;
        _resolver = resolver;
        _assetResolver = assetResolver;
        _bsa = bsa;
        _faceGenConsistency = faceGenConsistency;
        _cache = cache;
        _env = env;
    }

    private readonly EnvironmentStateProvider _env;

    /// <summary>Winning head parts by EditorID, built once per run. Types the
    /// orphan baked shapes so the analyzer can say which same-slot shape the
    /// .nif carries in place of a missing one. EditorIDs are effectively
    /// globally unique and a same-named part has the same Type regardless of
    /// which override wins, so winning-override resolution is safe here even
    /// though the consistency check itself is Origin-scoped.</summary>
    private Dictionary<string, IHeadPartGetter> _headPartsByEditorId = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>Progress notification. Units are NPCs, not mods — mods vary from
    /// one NPC to thousands, so a mod-granular bar sits still through the big
    /// ones and then leaps, which reads as a hang. Each mod contributes its NPC
    /// count to <see cref="Total"/>; a cache hit (or the mod-not-installed fast
    /// path) advances <see cref="Completed"/> by the whole mod's weight at once.</summary>
    public sealed record ProgressInfo(int Completed, int Total, string CurrentLabel);

    /// <summary>A mod's contribution to the progress total. Never zero so even a
    /// degenerate entry still ticks the bar when it completes.</summary>
    private static int Weight(ModSetting mod) => Math.Max(1, mod.NpcFormKeys?.Count ?? 0);

    /// <summary>One mod queued for scanning. The snapshot is produced by the
    /// caller (the VM owns snapshot generation) so the scanner stays VM-free.</summary>
    public sealed record ModScanTarget(ModSetting Model, ModStateSnapshot? Snapshot);

    /// <summary>Mods eligible for scanning: installed appearance mods that
    /// provide NPCs. Mugshot-only entries and the synthetic Base Game /
    /// Creation Club entries carry no folder paths, so both fall out of the
    /// folder requirement; IsAutoGenerated is excluded explicitly as a belt.
    /// "Installed" requires at least one folder to exist with content: a
    /// ModSetting whose folders were all deleted keeps its settings entry, but
    /// it must drop out of the Mod Issues tab entirely — mod list, unscanned
    /// list, and cache (pruned by <see cref="RunAsync"/>) — rather than sit
    /// there as a permanent "mod not installed" row (user-requested
    /// 2026-08-16).</summary>
    public static bool IsEligible(ModSetting mod)
        => IsEligibleBySettings(mod) && HasInstalledContent(mod);

    /// <summary>The settings-only half of <see cref="IsEligible"/> — everything
    /// except the <see cref="HasInstalledContent"/> disk probe, which is too
    /// expensive to run per keystroke (the Mod Issues scan-target search box
    /// filters mod names on this predicate).</summary>
    public static bool IsEligibleBySettings(ModSetting mod)
        => !mod.IsAutoGenerated
           && mod.CorrespondingFolderPaths is { Count: > 0 }
           && mod.NpcFormKeys is { Count: > 0 };

    /// <summary>At least one of the mod's folders exists and is non-empty.</summary>
    public static bool HasInstalledContent(ModSetting mod)
        => mod.CorrespondingFolderPaths.Any(f =>
        {
            try { return Directory.Exists(f) && Directory.EnumerateFileSystemEntries(f).Any(); }
            catch { return false; }
        });

    /// <summary>
    /// Scans the given mods, reusing valid cache entries unless
    /// <paramref name="ignoreCache"/>. Returns the per-mod results actually in
    /// effect after the run (cache hits included). Cancellation preserves every
    /// completed mod (already stored + saved); the in-flight mod is discarded so
    /// a previous valid entry survives.
    /// </summary>
    /// <param name="onModCompleted">Invoked (on a background thread) as each
    /// mod's result becomes final — after a fresh scan is stored, or when a
    /// cache entry is reused — so the UI can display results incrementally
    /// instead of waiting for the whole run.</param>
    public async Task<Dictionary<string, ModIssueScanResult>> RunAsync(
        IReadOnlyList<ModScanTarget> mods,
        bool ignoreCache,
        IProgress<ProgressInfo> progress,
        CancellationToken ct,
        Action<string, ModIssueScanResult>? onModCompleted = null)
    {
        var results = new Dictionary<string, ModIssueScanResult>(StringComparer.OrdinalIgnoreCase);
        if (mods.Count == 0) return results;

        _cache.Load();

        // Opening hundreds of archives can take seconds; do it once, off the UI thread.
        await Task.Run(() => _bsa.EnsureAllArchivesOpened(), ct).ConfigureAwait(false);

        // Parse results shared across mods/NPCs within one run: Skyrim NPCs share
        // body/armor NIFs heavily, and the extraction cache hands back a stable
        // disk path per (bsa, rel), so the resolved path is a safe dedupe key.
        var nifParseCache = new ConcurrentDictionary<string, Lazy<IReadOnlyList<NifHandler.NifShapeTextureInfo>>>(
            StringComparer.OrdinalIgnoreCase);

        _folderOwners = _settings.ModSettings
            .SelectMany(ms => ms.CorrespondingFolderPaths
                .Where(f => !string.IsNullOrWhiteSpace(f))
                .Select(f => (Folder: f.TrimEnd('\\', '/'), ModName: ms.DisplayName)))
            .OrderByDescending(t => t.Folder.Length)
            .ToList();

        _headPartsByEditorId = await Task.Run(() =>
        {
            var map = new Dictionary<string, IHeadPartGetter>(StringComparer.OrdinalIgnoreCase);
            try
            {
                foreach (var hp in _env.LoadOrder?.PriorityOrder.HeadPart().WinningOverrides()
                                   ?? Enumerable.Empty<IHeadPartGetter>())
                {
                    if (!string.IsNullOrEmpty(hp.EditorID)) map.TryAdd(hp.EditorID!, hp);
                }
            }
            catch { /* typing orphan shapes is best-effort */ }
            return map;
        }, ct).ConfigureAwait(false);

        int totalNpcs = mods.Sum(t => Weight(t.Model));
        int completedNpcs = 0;

        bool anyStored = false;
        try
        {
            for (int i = 0; i < mods.Count; i++)
            {
                ct.ThrowIfCancellationRequested();
                var target = mods[i];
                var mod = target.Model;
                int baseNpcs = completedNpcs;

                progress.Report(new ProgressInfo(baseNpcs, totalNpcs, mod.DisplayName));

                var trees = await Task.Run(
                    () => ModIssuesCache.BuildLooseAssetTrees(mod.CorrespondingFolderPaths), ct)
                    .ConfigureAwait(false);

                if (!ignoreCache &&
                    _cache.TryGetValid(mod.DisplayName, target.Snapshot, trees, out var cached))
                {
                    results[mod.DisplayName] = cached;
                    completedNpcs = baseNpcs + Weight(mod);
                    progress.Report(new ProgressInfo(completedNpcs, totalNpcs,
                        $"{mod.DisplayName} (unchanged — cached)"));
                    onModCompleted?.Invoke(mod.DisplayName, cached);
                    continue;
                }

                var result = await Task.Run(
                    () => ScanModAsync(mod, target.Snapshot, trees, nifParseCache,
                        (j, n) => progress.Report(new ProgressInfo(baseNpcs + j, totalNpcs,
                            $"{mod.DisplayName} ({j}/{n} NPCs)")), ct), ct)
                    .ConfigureAwait(false);

                results[mod.DisplayName] = result;
                _cache.Store(mod.DisplayName, result);
                anyStored = true;
                completedNpcs = baseNpcs + Weight(mod);
                progress.Report(new ProgressInfo(completedNpcs, totalNpcs, mod.DisplayName));
                onModCompleted?.Invoke(mod.DisplayName, result);
                // Throttle: persist after each mod so a crash/cancel keeps progress.
                await _cache.SaveAsync().ConfigureAwait(false);
            }

            // Eligibility-based prune: entries whose mod was removed from the settings OR
            // whose folders no longer exist with content (deleted/uninstalled mods) both
            // drop out, so a deleted mod's row disappears on the next rescan instead of
            // lingering as "mod not installed".
            int pruned = _cache.Prune(_settings.ModSettings.Where(IsEligible).Select(m => m.DisplayName));
            if (anyStored || pruned > 0) await _cache.SaveAsync().ConfigureAwait(false);
            progress.Report(new ProgressInfo(totalNpcs, totalNpcs, "Done."));
        }
        catch (OperationCanceledException)
        {
            if (anyStored) await _cache.SaveAsync().ConfigureAwait(false);
            progress.Report(new ProgressInfo(completedNpcs, totalNpcs, "Cancelled."));
            throw;
        }
        finally
        {
            _assetResolver.SetAdditionalScopes(null);
            _assetResolver.SetAdditionalFolders(null);
        }

        return results;
    }

    private async Task<ModIssueScanResult> ScanModAsync(
        ModSetting mod,
        ModStateSnapshot? snapshot,
        List<LooseAssetTreeSnapshot> trees,
        ConcurrentDictionary<string, Lazy<IReadOnlyList<NifHandler.NifShapeTextureInfo>>> nifParseCache,
        Action<int, int> reportNpcProgress,
        CancellationToken ct)
    {
        var result = new ModIssueScanResult
        {
            ScanTimeUtc = DateTime.UtcNow,
            Snapshot = snapshot,
            LooseAssetTrees = trees,
        };

        // Fast path: mod effectively uninstalled — every folder is missing or
        // empty. One mod-level issue instead of one per NPC asset.
        bool anyContent = mod.CorrespondingFolderPaths.Any(f =>
        {
            try { return Directory.Exists(f) && Directory.EnumerateFileSystemEntries(f).Any(); }
            catch { return false; }
        });
        if (!anyContent)
        {
            result.Issues.Add(new ModIssue
            {
                Type = ModIssueType.ModNotInstalled,
                AffectedPath = string.Join("; ", mod.CorrespondingFolderPaths),
                Detail = "None of this mod's folders exist (or they are empty) — the mod appears to be uninstalled.",
            });
            result.ScanCompleted = true;
            return result;
        }

        var npcKeys = mod.NpcFormKeys.OrderBy(fk => fk.ToString(), StringComparer.OrdinalIgnoreCase).ToList();
        var issues = new ConcurrentBag<ModIssue>();

        // NPCs run in parallel: the resolver stack is exercised concurrently by
        // the batch mugshot generator already, GameAssetResolver's scope state
        // is AsyncLocal (isolated per task flow), and nifly loads are
        // thread-safe. NIF parses dominate the cost and dedupe via the shared cache.
        int completed = 0;
        int failedNpcs = 0;
        using var gate = new SemaphoreSlim(Math.Max(1, Environment.ProcessorCount - 1));
        var tasks = npcKeys.Select(async npcKey =>
        {
            await gate.WaitAsync(ct).ConfigureAwait(false);
            try
            {
                bool ok = await Task.Run(() => ScanNpc(mod, npcKey, nifParseCache, issues, ct), ct).ConfigureAwait(false);
                if (!ok) Interlocked.Increment(ref failedNpcs);
            }
            finally
            {
                gate.Release();
                int done = Interlocked.Increment(ref completed);
                if (done % 10 == 0 || done == npcKeys.Count) reportNpcProgress(done, npcKeys.Count);
            }
        }).ToList();

        await Task.WhenAll(tasks).ConfigureAwait(false);
        ct.ThrowIfCancellationRequested();

        result.Issues.AddRange(issues
            .OrderBy(iss => iss.NpcDisplayName, StringComparer.OrdinalIgnoreCase)
            .ThenBy(iss => iss.Type)
            .ThenBy(iss => iss.AffectedPath, StringComparer.OrdinalIgnoreCase));
        result.ScannedNpcCount = npcKeys.Count;
        result.FailedNpcCount = failedNpcs;
        result.ScanCompleted = true;
        return result;
    }

    /// <summary>Returns false when the NPC's scan threw and was swallowed, so the
    /// mod's <see cref="ModIssueScanResult.FailedNpcCount"/> can surface the gap.</summary>
    private bool ScanNpc(
        ModSetting mod,
        FormKey npcKey,
        ConcurrentDictionary<string, Lazy<IReadOnlyList<NifHandler.NifShapeTextureInfo>>> nifParseCache,
        ConcurrentBag<ModIssue> issues,
        CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        string npcName = mod.NpcFormKeysToDisplayName.TryGetValue(npcKey, out var n) ? n : npcKey.ToString();
        // Per-NPC dedupe: the same shape/texture miss can surface through several
        // body parts sharing one NIF.
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        void AddIssue(ModIssueType type, string affectedPath, string? nifPath = null,
            string? shapeName = null, string? referencer = null, string? detail = null,
            bool isOutfit = false, ModIssueSeverity severity = ModIssueSeverity.Issue,
            string? sourceMod = null, string? recordPlugin = null)
        {
            // recordPlugin joins the dedupe key: per-plugin dark-face verdicts share
            // one AffectedPath (the FaceGen NIF), and the second variant's row must
            // not be swallowed as a duplicate of the first.
            if (!seen.Add($"{type}|{nifPath}|{shapeName}|{affectedPath}|{recordPlugin}")) return;
            issues.Add(new ModIssue
            {
                Type = type,
                NpcFormKey = npcKey,
                NpcDisplayName = npcName,
                AffectedPath = affectedPath,
                NifPath = nifPath,
                ShapeName = shapeName,
                ReferencingRecord = referencer,
                Detail = detail,
                IsOutfitIssue = isOutfit,
                Severity = severity,
                SourceModName = sourceMod,
                RecordPluginName = recordPlugin,
            });
        }

        try
        {
            // Same scope chain the mugshot renderer would use for this (mod, NPC).
            _assetResolver.SetAdditionalScopes(_resolver.BuildResolutionScopes(mod, npcKey));

            var (npc, resolveHeadPart, resolveRace, npcFromModPlugins) =
                _resolver.ResolveNpcForConsistency(npcKey, mod);
            if (npc == null) return true; // Record-level problems are the Validator's domain.

            var appearanceKey = _resolver.ResolveAppearanceNpcKey(npcKey, mod);
            bool shouldHaveFaceGen = OutputValidator.SubjectShouldHaveOwnFaceGen(npc, resolveRace);
            var (faceGenMeshRel, faceGenTintRel) = Auxilliary.GetFaceGenSubPathStrings(appearanceKey, regularized: true);

            // FaceGen paths belong to the appearance TERMINUS: a Traits-templated NPC has
            // no face of its own and the whole template group misses the SAME file — say
            // so, or "5 NPCs missing one .dds" reads like a display bug.
            string? templateNote = appearanceKey.Equals(npcKey)
                ? null
                : $"This NPC inherits its appearance from template {appearanceKey}; the file is the template's, shared by every NPC inheriting it.";

            if (shouldHaveFaceGen && !_resolver.FaceGenExists(npcKey, mod))
            {
                AddIssue(ModIssueType.MissingFaceGenMesh, faceGenMeshRel,
                    detail: "No FaceGen head mesh anywhere the game would look — this NPC renders with the dark-face/no-head bug."
                            + (templateNote == null ? "" : "\n" + templateNote));
            }

            var paths = _resolver.Resolve(npcKey, mod);
            if (paths == null) return true;

            // FaceGen tint DDS. Only meaningful for NPCs that own FaceGen.
            if (shouldHaveFaceGen && !string.IsNullOrWhiteSpace(paths.FaceTintPath) &&
                ResolveToDisk(paths.FaceTintPath!, allowLoadOrderFallback: false) == null)
            {
                AddIssue(ModIssueType.MissingFaceGenTint, faceGenTintRel,
                    detail: "FaceGen tint texture is missing — faces typically render grey/mismatched without it."
                            + (templateNote == null ? "" : "\n" + templateNote));
            }

            // The NPC's own drawn meshes (skin ARMA world models + FaceGen head).
            // No weight-sibling checks here: ResolvedNpcMeshPaths carries no
            // weight-slider flag, and without it a single-weight skin file is
            // indistinguishable from a genuinely missing counterpart.
            // Name WHERE the skin meshes come from (the WornArmor record or the race's
            // skin) so "why is femalebody_1.nif being checked" answers itself.
            string skinVia = npc.WornArmor.IsNull
                ? $" via race skin ({npc.Race.FormKey})"
                : $" via WornArmor {npc.WornArmor.FormKey}";

            var nifJobs = new List<NifJob>();
            // isSkin: the engine textures every shape reached through the worn-skin
            // ArmorAddon chain — body/hands/feet AND the race-specific extras like Khajiit/
            // Argonian tails and worn hair — from the record chain's TextureSet (the ARMA's,
            // or the race skin's). The paths baked in these NIFs are runtime-superseded,
            // so their misses demote to Note below. Only FaceGen bakes are final.
            CheckMesh(mod, paths.BodyMeshPath, "Skin ARMA (Body)" + skinVia, false, false, false, nifJobs, AddIssue, isSkin: true);
            CheckMesh(mod, paths.HandsMeshPath, "Skin ARMA (Hands)" + skinVia, false, false, false, nifJobs, AddIssue, isSkin: true);
            CheckMesh(mod, paths.FeetMeshPath, "Skin ARMA (Feet)" + skinVia, false, false, false, nifJobs, AddIssue, isSkin: true);
            CheckMesh(mod, paths.HairMeshPath, "Worn hair ARMA", false, false, false, nifJobs, AddIssue, isSkin: true);
            CheckMesh(mod, paths.TailMeshPath, "Tail ARMA", false, false, false, nifJobs, AddIssue, isSkin: true);

            // FaceGen head: existence already handled above (FaceGenExists knows
            // the renderer's vanilla-loose-skip rule, which plain resolution
            // doesn't), so only queue the texture walk when it resolves.
            var headSource = ResolveSource(paths.HeadMeshPath, allowLoadOrderFallback: false);
            string? headDisk = headSource?.ResolvedDiskPath;
            if (headDisk != null)
            {
                nifJobs.Add(new NifJob(headDisk, paths.HeadMeshPath!, "FaceGen head", false, IsFaceGen: true,
                    SourceDescription: headSource!.LoosePath ??
                        (headSource.BsaPath != null ? $"{headSource.BsaPath} :: {headSource.InternalBsaPath}" : headDisk)));
            }

            // Full effective outfit (incl. headgear): what the renderer would
            // actually dress the NPC in, LeveledItems and runtime distributors included.
            IReadOnlyList<MeshOverride> overrides;
            try
            {
                overrides = _resolver.ResolveAttireMeshOverrides(npcKey, mod,
                    includeDefaultOutfit: true, includeHeadgear: true);
            }
            catch
            {
                overrides = Array.Empty<MeshOverride>();
            }

            foreach (var over in overrides)
            {
                ct.ThrowIfCancellationRequested();
                if (string.IsNullOrWhiteSpace(over.MeshPath)) continue;
                // Weight siblings only when the ARMA's weight slider is on for
                // this sex — the engine's own signal that a _0/_1 pair exists.
                CheckMesh(mod, over.MeshPath, over.Key, over.AllowLoadOrderFallback,
                    isOutfit: true, checkWeightSibling: over.HasWeightVariants, nifJobs, AddIssue);

                // AlternateTextures (MODS): the one record-side texture channel the
                // engine applies over NIF-baked paths.
                if (over.AlternateTextures != null)
                {
                    foreach (var spec in over.AlternateTextures)
                    {
                        foreach (var tex in spec.Textures.Values)
                        {
                            CheckAltTexture(mod, tex, over, spec.ShapeName, AddIssue);
                        }
                    }
                }
                else if (over.ShapeTextures != null)
                {
                    foreach (var (shapeName, slots) in over.ShapeTextures)
                    {
                        foreach (var tex in slots.Values)
                        {
                            CheckAltTexture(mod, tex, over, shapeName, AddIssue);
                        }
                    }
                }
            }

            // Textures baked inside every rendered NIF — ground truth for what the
            // engine samples. Per-texture verdicts, grouped per shape via ShapeName.
            // Which SLOT a path occupies decides whether the engine reads it at all
            // and how visible a miss is — see ClassifyNifTextureSlot.
            foreach (var job in nifJobs)
            {
                ct.ThrowIfCancellationRequested();
                IReadOnlyList<NifHandler.NifShapeTextureInfo> byShape;
                try
                {
                    byShape = nifParseCache.GetOrAdd(job.DiskPath,
                        dp => new Lazy<IReadOnlyList<NifHandler.NifShapeTextureInfo>>(
                            () => NifHandler.GetShapeTextureDetails(dp),
                            LazyThreadSafetyMode.ExecutionAndPublication)).Value;
                }
                catch
                {
                    continue; // Unparseable NIF — the renderer has its own reporting for that.
                }

                foreach (var shape in byShape)
                {
                    // A shape the engine cannot draw cannot render untextured
                    // (wig mods keep alpha-0 hair shapes whose textures were
                    // never meant to be installed).
                    if (!shape.DrawnInGame) continue;

                    foreach (var slotTex in shape.Slots)
                    {
                        var tex = slotTex.Path;
                        if (string.IsNullOrWhiteSpace(tex)) continue;
                        if (!Auxilliary.TryRegularizePath(tex, out var rel) || string.IsNullOrWhiteSpace(rel)) continue;

                        var severity = ClassifyNifTextureSlot(slotTex.Slot, job.IsFaceGen,
                            shape.ShaderType, shape.ShaderFlags1, rel);
                        if (severity == null) continue; // slot the engine never reads
                        if (ResolveToDisk(rel, job.AllowLoadOrderFallback) != null) continue;

                        // Worn-skin shapes never sample their baked paths in game: the engine
                        // applies the record chain's TextureSet (the skin ARMA's, or the race
                        // skin's) over them — only FaceGen bakes are final. A missing baked
                        // texture here is invisible (Bijin Brelyna: the body NIF bakes Astrid's
                        // burnt textures and a dead _msn path; in game she wears her WornArmor
                        // ARMA's textures), so it is a Note, never an Issue.
                        if (job.IsSkin) severity = ModIssueSeverity.Note;

                        string shapeDisplay = string.IsNullOrWhiteSpace(shape.ShapeName)
                            ? "(unnamed shape)"
                            : shape.ShapeName;
                        string detail = $"Texture slot {slotTex.Slot} of shape '{shapeDisplay}'.";
                        if (job.IsSkin)
                            detail += " Skin shapes get their textures from the ArmorAddon / race skin " +
                                      "TextureSet at runtime, so the path baked in the NIF is not what the " +
                                      "engine samples — this miss is not visible in game.";

                        // Partition slots are only worth mentioning when they imply
                        // redundancy — another drawn shape covering the same biped
                        // slot(s) (BodySlide variants, replaced brows/hair) means the
                        // broken shape may not even be the one that renders. A bare
                        // slot listing carries no signal on its own.
                        if (shape.PartitionSlots.Count > 0)
                        {
                            var sameSlotShapes = byShape
                                .Where(o => !ReferenceEquals(o, shape) && o.DrawnInGame &&
                                            !string.Equals(o.ShapeName, shape.ShapeName, StringComparison.OrdinalIgnoreCase) &&
                                            o.PartitionSlots.Intersect(shape.PartitionSlots).Any())
                                .Select(o => string.IsNullOrWhiteSpace(o.ShapeName) ? "(unnamed shape)" : o.ShapeName)
                                .Distinct(StringComparer.OrdinalIgnoreCase)
                                .ToList();
                            if (sameSlotShapes.Count > 0)
                            {
                                string others = string.Join("', '", sameSlotShapes.Take(4));
                                if (sameSlotShapes.Count > 4) others += $"', … +{sameSlotShapes.Count - 4} more";
                                detail += $" Shape(s) '{others}' occupy the same biped slot(s) " +
                                          $"({string.Join(", ", shape.PartitionSlots)}).";
                            }
                        }

                        if (!string.IsNullOrEmpty(job.SourceDescription))
                            detail += $"\nReferencing NIF resolved from: {job.SourceDescription}";

                        AddIssue(ModIssueType.MissingNifTexture, rel,
                            nifPath: job.GamePath,
                            shapeName: string.IsNullOrWhiteSpace(shape.ShapeName) ? "(unnamed shape)" : shape.ShapeName,
                            referencer: job.Referencer,
                            detail: detail,
                            isOutfit: job.IsOutfit,
                            severity: severity.Value,
                            sourceMod: job.SourceModName);
                    }
                }
            }

            // Dark-face class: records vs. the baked FaceGen shapes. Resolution is
            // Origin-scoped (mod plugins → the FormKey's defining plugin), so the
            // verdict describes THIS mod's own data, independent of the load order.
            // Multi-plugin mods grade PER PLUGIN record — the WICO field case
            // (2026-08-17): the two plugins carry different head-part sets for the
            // same NPC and only one matches the shipped bake, so a single verdict
            // would silently follow the user's per-NPC source-plugin pin. Head
            // parts/races still resolve through the shared mod-wide scope: the
            // record is the variable under test, not the part definitions.
            if (headDisk != null)
            {
                try
                {
                    var variants = BuildRecordVariants(npc, appearanceKey, mod, npcFromModPlugins);

                    // Analyze every variant up front so a broken plugin's row can
                    // point at a sibling plugin that grades clean (the repin remedy
                    // the user otherwise discovers by hand).
                    var graded = variants
                        .Select(v => (Variant: v,
                            Analysis: _faceGenConsistency.Analyze(v.Record, resolveHeadPart, resolveRace, headDisk,
                                edid => _headPartsByEditorId.TryGetValue(edid, out var hp) ? hp : null)))
                        .ToList();

                    var cleanLabels = graded
                        .Where(g => g.Analysis.MissingBakedShapes.Count == 0 &&
                                    g.Analysis.NullHeadPartLinks == 0 &&
                                    g.Analysis.UnresolvedHeadParts.Count == 0)
                        .Select(g => g.Variant.Label)
                        .Where(l => !string.IsNullOrEmpty(l))
                        .ToList();

                    foreach (var (variant, analysis) in graded)
                    {
                        // Head parts from a plugin that resolves nowhere = a missing hard
                        // dependency. One rollup row per absent plugin instead of folding
                        // it into the dark-face wall of text — one absent plugin used to
                        // produce thousands of DarkFaceMismatch rows across a mod.
                        foreach (var group in analysis.UnresolvedHeadParts.GroupBy(fk => fk.ModKey))
                        {
                            AddIssue(ModIssueType.MissingHeadPartPlugin, group.Key.FileName.String,
                                nifPath: paths.HeadMeshPath,
                                recordPlugin: variant.Label,
                                detail: "This NPC's record uses head part(s) " +
                                        string.Join(", ", group.Select(fk => fk.ToString())) +
                                        " from a plugin that is not in this mod's folders and could not be resolved. " +
                                        "The mod likely requires it (check the mod page's requirements); without it these NPCs dark-face in game.");
                        }

                        if (analysis.MissingBakedShapes.Count > 0 || analysis.NullHeadPartLinks > 0)
                        {
                            // Traits-inert file (SOGS field specimen): the appearance hop used for
                            // RENDERING is Winner-scoped and can follow a load-order override that
                            // strips the vanilla Traits template — but in the mod's OWN context the
                            // template stands, the raw engine renders the terminus's face, and the
                            // graded file at this NPC's own path is never loaded. Note, not Issue:
                            // whether the file ever matters is decided by this app's template
                            // handling at patch time, and Validate Output checks the real output.
                            // Evaluated per VARIANT: one plugin can keep the template while
                            // another strips it.
                            bool traitsInert = appearanceKey.Equals(npcKey) && variant.KeepsTraitsTemplate;

                            string repinRemedy = variant.Label != null && cleanLabels.Count > 0
                                ? $"\nPlugin '{string.Join("', '", cleanLabels)}' in this same mod does not have " +
                                  "this problem for this NPC — selecting it as the NPC's source plugin (right-click " +
                                  "the NPC's mugshot in the Mods tab) avoids the bug."
                                : string.Empty;

                            AddIssue(ModIssueType.DarkFaceMismatch, faceGenMeshRel,
                                nifPath: paths.HeadMeshPath,
                                recordPlugin: variant.Label,
                                severity: traitsInert ? ModIssueSeverity.Note : ModIssueSeverity.Issue,
                                detail: (traitsInert
                                            ? "In the mod's own context this NPC keeps the Traits template flag, so the " +
                                              "unpatched engine renders its template's face and never loads this file — " +
                                              "the mismatch below cannot show in game unless a patch or another plugin " +
                                              "removes the template.\n"
                                            : string.Empty) +
                                        analysis.BuildReason(
                                            scope: FaceGenConsistencyAnalyzer.ReasonScope.SelectedMod,
                                            subjectSuppliesRecord: variant.SubjectSuppliesRecord) +
                                        repinRemedy);
                        }
                    }
                }
                catch
                {
                    // Best-effort, mirroring the mugshot generator: an analyzer
                    // failure must not fail the scan.
                }
            }

            return true;
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch
        {
            // One NPC's failure must not sink the mod's scan; the caller counts it.
            return false;
        }
        finally
        {
            _assetResolver.SetAdditionalScopes(null);
        }
    }

    private sealed record NifJob(string DiskPath, string GamePath, string Referencer,
        bool AllowLoadOrderFallback, bool IsFaceGen = false, bool IsOutfit = false,
        string? SourceModName = null, string? SourceDescription = null, bool IsSkin = false);

    private delegate void AddIssueDelegate(ModIssueType type, string affectedPath, string? nifPath = null,
        string? shapeName = null, string? referencer = null, string? detail = null, bool isOutfit = false,
        ModIssueSeverity severity = ModIssueSeverity.Issue, string? sourceMod = null, string? recordPlugin = null);

    /// <summary>One dark-face grading target: a record and the plugin(s) within the
    /// scanned mod that carry it. Label is null for the single-variant case (a
    /// single-plugin mod, or no mod plugin carries the record and the pinned/origin
    /// resolution stands in) — those rows stay untagged, the pre-v9 presentation.</summary>
    private sealed record RecordVariant(INpcGetter Record, string? Label,
        bool SubjectSuppliesRecord, bool KeepsTraitsTemplate);

    private static bool KeepsTraitsTemplate(INpcGetter npc) =>
        npc.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Traits) &&
        !npc.Template.IsNull;

    /// <summary>The dark-face grading targets for one NPC. Multi-plugin mods yield
    /// one variant per DISTINCT record signature among the plugins carrying the
    /// record (identical records collapse, labeled with every carrier); otherwise
    /// the already-resolved pinned/origin record is the single unlabeled variant.</summary>
    private List<RecordVariant> BuildRecordVariants(INpcGetter pinnedNpc, FormKey appearanceKey,
        ModSetting mod, bool pinnedFromModPlugins)
    {
        if (mod.CorrespondingModKeys.Count > 1)
        {
            var perPlugin = _resolver.ResolveNpcRecordPerPlugin(appearanceKey, mod);
            if (perPlugin.Count > 0)
            {
                return GroupPluginRecordsBySignature(perPlugin)
                    .Select(g => new RecordVariant(g.Record, g.Label,
                        SubjectSuppliesRecord: true, KeepsTraitsTemplate(g.Record)))
                    .ToList();
            }
        }

        return new List<RecordVariant>
        {
            new(pinnedNpc, Label: null, pinnedFromModPlugins, KeepsTraitsTemplate(pinnedNpc)),
        };
    }

    /// <summary>Collapses per-plugin records to one entry per distinct dark-face
    /// signature, preserving plugin order; the label joins every carrier's filename
    /// ("A.esp, B.esp") so identical records produce one row instead of N.</summary>
    internal static List<(INpcGetter Record, string Label)> GroupPluginRecordsBySignature(
        IReadOnlyList<(ModKey Plugin, INpcGetter Record)> perPlugin)
    {
        var order = new List<string>();
        var groups = new Dictionary<string, (INpcGetter Record, List<string> Plugins)>(StringComparer.Ordinal);
        foreach (var (plugin, record) in perPlugin)
        {
            var sig = NpcDarkFaceSignature(record);
            if (groups.TryGetValue(sig, out var existing))
            {
                existing.Plugins.Add(plugin.FileName.String);
            }
            else
            {
                groups[sig] = (record, new List<string> { plugin.FileName.String });
                order.Add(sig);
            }
        }
        return order
            .Select(sig => (groups[sig].Record, string.Join(", ", groups[sig].Plugins)))
            .ToList();
    }

    /// <summary>Equality key for per-plugin dark-face grading: two plugin records
    /// with the same signature produce the same verdict, so they collapse to one
    /// labeled row. Covers exactly the analyzer's record-side inputs: head parts IN
    /// ORDER (the singular-slot rule is first-listed-wins), race, sex, and the
    /// Traits-template state (the inert demotion).</summary>
    internal static string NpcDarkFaceSignature(INpcGetter npc)
    {
        var parts = npc.HeadParts != null
            ? string.Join("|", npc.HeadParts.Select(hp => hp.FormKey.ToString()))
            : string.Empty;
        return parts +
               "§" + npc.Race.FormKey +
               "§" + (Auxilliary.IsFemale(npc) ? 'F' : 'M') +
               "§" + (KeepsTraitsTemplate(npc) ? 'T' : '-');
    }

    private void CheckMesh(ModSetting scannedMod, string? gamePath, string referencer,
        bool allowLoadOrderFallback, bool isOutfit, bool checkWeightSibling,
        List<NifJob> nifJobs, AddIssueDelegate addIssue, bool isSkin = false)
    {
        if (string.IsNullOrWhiteSpace(gamePath)) return;

        var source = ResolveSource(gamePath, allowLoadOrderFallback);
        string? disk = source?.ResolvedDiskPath;
        if (disk == null)
        {
            // The mesh itself is missing, so there is no disk path to attribute —
            // fall back to the referencing record's plugin for "whose mod is this".
            addIssue(ModIssueType.MissingArmaMesh, gamePath, referencer: referencer,
                detail: "The mesh could not be found in the mod, vanilla archives, or the Data folder — it will not render.",
                isOutfit: isOutfit,
                sourceMod: isOutfit ? AttributeProviderByReferencer(referencer, scannedMod) : null);
            return;
        }

        // Which installed mod supplies this NIF: outfit meshes usually come from
        // an outfit/armor mod rather than the appearance mod under scan, and the
        // report should point users at the right author.
        string? sourceMod = isOutfit ? AttributeProviderMod(source, scannedMod) : null;
        string sourceDescription = source!.LoosePath
            ?? (source.BsaPath != null ? $"{source.BsaPath} :: {source.InternalBsaPath}" : disk);
        nifJobs.Add(new NifJob(disk, gamePath!, referencer, allowLoadOrderFallback,
            IsOutfit: isOutfit, SourceModName: sourceMod, SourceDescription: sourceDescription,
            IsSkin: isSkin));

        // _0/_1 weight sibling: only when the source ARMA's weight slider is
        // enabled — then the engine morphs between both files and a missing
        // counterpart pops or crashes at non-matching weights. With the slider
        // off, a lone weight file is the normal shipping shape.
        if (!checkWeightSibling) return;
        string? sibling = DeriveWeightSibling(gamePath!);
        if (sibling != null && ResolveToDisk(sibling, allowLoadOrderFallback) == null)
        {
            addIssue(ModIssueType.MissingWeightSibling, sibling, referencer: referencer,
                detail: $"The weight counterpart of {Path.GetFileName(gamePath)} is missing.",
                isOutfit: isOutfit, sourceMod: sourceMod);
        }
    }

    private void CheckAltTexture(ModSetting scannedMod, string texPath, MeshOverride over, string shapeName,
        AddIssueDelegate addIssue)
    {
        if (string.IsNullOrWhiteSpace(texPath)) return;
        if (!Auxilliary.TryRegularizePath(texPath, out var rel) || string.IsNullOrWhiteSpace(rel)) return;
        if (ResolveToDisk(rel, over.AllowLoadOrderFallback) != null) return;

        addIssue(ModIssueType.MissingAltTexture, rel, over.MeshPath,
            string.IsNullOrWhiteSpace(shapeName) ? "(unnamed shape)" : shapeName, over.Key,
            "An AlternateTextures entry points at this texture; the shape it retextures will render untextured.",
            isOutfit: true, sourceMod: AttributeProviderByReferencer(over.Key, scannedMod));
    }

    /// <summary>
    /// Which slots the engine actually samples, and how visible a missing file
    /// there is. Null = the engine never reads this slot, so a missing file is
    /// not reportable at any tier:
    /// <list type="bullet">
    /// <item>Anything under facegendata\facetint, and slot 6 of a FaceGen head:
    /// the engine loads the face tint ONLY from the canonical FormID-derived
    /// path (proven in-game 2026-08-15, docs/FaceTintEngineTest-2026-08.md) —
    /// the baked slot-6 string is never consulted, which is also why authors get
    /// away with junk strings there. The canonical tint has its own check
    /// (MissingFaceGenTint).</item>
    /// <item>Slots 4/5 (environment cubemap/mask) when neither the shader type
    /// nor the SLSF1 flags enable environment mapping.</item>
    /// </list>
    /// Slots 0/1 (diffuse/normal) are Issues — a miss renders visibly broken
    /// (white/flat mesh). Every other sampled slot is a Note: real but subtle in
    /// game — vanilla itself ships meshes referencing secondary maps it does not
    /// include (mouthhuman_s/_sk, teeth_e: 58% of all texture rows measured on a
    /// live setup). Unknown shader info fails conservative (report as Note).
    /// </summary>
    internal static ModIssueSeverity? ClassifyNifTextureSlot(int slot, bool isFaceGenHead,
        uint shaderType, uint shaderFlags1, string regularizedPath)
    {
        const uint Slsf1EnvironmentMapping = 0x00000080;
        const uint Slsf1EyeEnvironmentMapping = 0x00020000;
        const uint ShaderTypeEnvMap = 1;
        const uint ShaderTypeEyeEnvMap = 16;

        if (regularizedPath.Contains(@"facegendata\facetint", StringComparison.OrdinalIgnoreCase))
            return null;

        switch (slot)
        {
            case 0:
            case 1:
                return ModIssueSeverity.Issue;

            case 6:
                return isFaceGenHead ? null : ModIssueSeverity.Note;

            case 4:
            case 5:
                bool envActive =
                    shaderType == ShaderTypeEnvMap ||
                    shaderType == ShaderTypeEyeEnvMap ||
                    shaderType == NifHandler.UnknownShaderType ||
                    (shaderFlags1 & (Slsf1EnvironmentMapping | Slsf1EyeEnvironmentMapping)) != 0;
                return envActive ? ModIssueSeverity.Note : null;

            default: // 2 glow/subsurface, 3 detail/palette, 7 specular/backlight, 8 spare
                return ModIssueSeverity.Note;
        }
    }

    /// <summary>Resolves a game path (or passes through an already-rooted disk
    /// path) to an on-disk file via the renderer's scope chain. Null = missing.</summary>
    private string? ResolveToDisk(string? path, bool allowLoadOrderFallback)
        => ResolveSource(path, allowLoadOrderFallback)?.ResolvedDiskPath;

    /// <summary>Like <see cref="ResolveToDisk"/> but keeps the full
    /// <see cref="AssetSource"/> so callers can attribute the winning provider
    /// (loose folder or BSA) to an installed mod. Null = missing/unresolvable.</summary>
    private AssetSource? ResolveSource(string? path, bool allowLoadOrderFallback)
    {
        if (string.IsNullOrWhiteSpace(path)) return null;
        try
        {
            if (Path.IsPathRooted(path))
            {
                return File.Exists(path)
                    ? new AssetSource(AssetOriginKind.Loose, path, path, path, null, null)
                    : null;
            }
            using (_assetResolver.PushLoadOrderFallback(allowLoadOrderFallback))
            {
                var source = _assetResolver.ResolveAssetSource(path!);
                return source.ResolvedDiskPath == null ? null : source;
            }
        }
        catch
        {
            return null;
        }
    }

    /// <summary>Maps the winning provider's disk location (loose file or BSA —
    /// both live inside some mod's folder) to the owning ModSetting via
    /// longest-prefix match. Null when the provider is the scanned mod itself
    /// (nothing to point at), the game Data folder, or unattributable.</summary>
    private string? AttributeProviderMod(AssetSource? source, ModSetting scannedMod)
    {
        string? path = source?.LoosePath ?? source?.BsaPath;
        if (string.IsNullOrWhiteSpace(path)) return null;
        foreach (var (folder, name) in _folderOwners)
        {
            if (path.StartsWith(folder, StringComparison.OrdinalIgnoreCase) &&
                (path.Length == folder.Length || path[folder.Length] == '\\' || path[folder.Length] == '/'))
            {
                return name.Equals(scannedMod.DisplayName, StringComparison.OrdinalIgnoreCase)
                    ? null
                    : name;
            }
        }
        return null;
    }

    /// <summary>Fallback attribution when there is no resolved file to map: the
    /// referencer string carries the source record's plugin
    /// ("Outfit:&lt;FormID&gt;:&lt;plugin&gt;:&lt;slots&gt;" per the attire walk's Key
    /// convention); the ModSetting owning that plugin is the mod to look at.</summary>
    private string? AttributeProviderByReferencer(string? referencer, ModSetting scannedMod)
    {
        if (string.IsNullOrWhiteSpace(referencer)) return null;
        var parts = referencer.Split(':');
        if (parts.Length < 3) return null;
        string pluginToken = parts[2].Trim();
        if (pluginToken.Length == 0) return null;

        var owner = _settings.ModSettings.FirstOrDefault(ms =>
            ms.CorrespondingModKeys.Any(k =>
                k.FileName.String.Equals(pluginToken, StringComparison.OrdinalIgnoreCase)));
        if (owner == null) return null;
        return owner.DisplayName.Equals(scannedMod.DisplayName, StringComparison.OrdinalIgnoreCase)
            ? null
            : owner.DisplayName;
    }

    /// <summary>Returns the _0/_1 weight-sibling path of a world-model NIF, or
    /// null when the filename doesn't follow the weight-pair convention.</summary>
    internal static string? DeriveWeightSibling(string nifPath)
    {
        if (string.IsNullOrWhiteSpace(nifPath)) return null;
        if (nifPath.EndsWith("_0.nif", StringComparison.OrdinalIgnoreCase))
            return nifPath[..^"_0.nif".Length] + "_1.nif";
        if (nifPath.EndsWith("_1.nif", StringComparison.OrdinalIgnoreCase))
            return nifPath[..^"_1.nif".Length] + "_0.nif";
        return null;
    }
}
