using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Threading;
using CharacterViewer.Rendering;
using Mutagen.Bethesda.Plugins;
using Newtonsoft.Json.Linq;
using NPC_Plugin_Chooser_2.Models;

namespace NPC_Plugin_Chooser_2.BackEnd.CharacterViewerHost;

/// <summary>
/// Unified renderer-aware staleness check for mugshots. Implements the
/// two-tier policy:
///
/// <list type="number">
/// <item>Was this PNG produced by the user's currently-active renderer? If
/// not (Internal vs LegacyPortraitCreator mismatch), it's stale regardless
/// of any other comparison — switching renderers should drop the previous
/// renderer's outputs.</item>
/// <item>For the active renderer, version-and-settings drift gates: Internal
/// compares <see cref="CharacterViewerRendering.Version"/> + a hash of the
/// relevant <see cref="InternalMugshotSettings"/>; Legacy delegates to
/// <see cref="PortraitCreator.NeedsRegeneration"/> (program version,
/// NIF SHA, background, lighting, etc.).</item>
/// </list>
///
/// Only PNGs that carry a "Parameters" tEXt chunk are considered for
/// regeneration — hand-crafted user mugshots without metadata are left
/// alone, matching the legacy behavior.
/// </summary>
public sealed class MugshotStalenessChecker
{
    private readonly Settings _settings;
    private readonly PortraitCreator _legacy;

    public MugshotStalenessChecker(Settings settings, PortraitCreator legacy)
    {
        _settings = settings;
        _legacy = legacy;
    }

    /// <summary>
    /// Decides whether <paramref name="pngPath"/> needs to be regenerated by
    /// the currently-active renderer.
    /// </summary>
    /// <param name="pngPath">Path to the existing mugshot PNG.</param>
    /// <param name="npcFormKey">FormKey of the NPC the PNG depicts (used for
    /// the Internal renderer's settings-hash check).</param>
    /// <param name="legacyNifPath">FaceGen NIF path — only consulted when the
    /// active renderer is Legacy. Pass null/empty for Internal callers.</param>
    /// <param name="legacyDataFolders">Mod data folders — only consulted when
    /// the active renderer is Legacy. Pass null for Internal callers.</param>
    /// <param name="legacyAutoGenerated">Auto-generated-mod flag forwarded
    /// to <see cref="PortraitCreator.NeedsRegeneration"/>.</param>
    /// <param name="effectiveOutfitIdentityProvider">Lazily supplies the
    /// CURRENT depicted-outfit identity stamp for this tile (see
    /// OutfitDisplayResult.IdentityStamp) — the caller knows the tile's
    /// target/source NPC + mod, which this checker does not. Only invoked for
    /// Internal PNGs stamped with an <c>effective_outfit</c> field (v12+);
    /// null skips the outfit-identity comparison (pre-upgrade callers).</param>
    public bool NeedsRegeneration(
        string pngPath,
        FormKey npcFormKey,
        string? legacyNifPath = null,
        IEnumerable<string>? legacyDataFolders = null,
        bool legacyAutoGenerated = false,
        Func<string>? effectiveOutfitIdentityProvider = null)
    {
        var sw = Stopwatch.StartNew();
        int tid = Environment.CurrentManagedThreadId;
        string fileLabel = string.IsNullOrEmpty(pngPath) ? "(empty)" : Path.GetFileName(pngPath);
        Trace($"ENTER tid={tid} npc={npcFormKey} png={fileLabel}");

        // Missing file = always stale (caller should treat as "generate fresh").
        if (string.IsNullOrWhiteSpace(pngPath) || !File.Exists(pngPath))
        {
            Trace($"EXIT tid={tid} png={fileLabel} result=STALE(missing) elapsed={sw.ElapsedMilliseconds}ms");
            return true;
        }

        var json = MugshotPngMetadata.TryRead(pngPath);
        Trace($"  metadata-read tid={tid} png={fileLabel} hasParams={json != null} elapsed={sw.ElapsedMilliseconds}ms");
        if (json == null)
        {
            // No "Parameters" chunk — treat as a hand-placed mugshot. Legacy's
            // NeedsRegeneration also returns false in this case.
            Trace($"EXIT tid={tid} png={fileLabel} result=FRESH(no-params) elapsed={sw.ElapsedMilliseconds}ms");
            return false;
        }

        var pngRenderer = DetectRenderer(json);

        // Tier 1: cross-renderer staleness. If the PNG came from a different
        // renderer than the user has selected, regenerate.
        if (pngRenderer != _settings.SelectedRenderer)
        {
            Trace($"  Tier1 renderer mismatch png={pngRenderer} active={_settings.SelectedRenderer}");
            Trace($"EXIT tid={tid} png={fileLabel} result=STALE(renderer-mismatch) elapsed={sw.ElapsedMilliseconds}ms");
            return true;
        }

        // Tier 2: per-renderer staleness.
        bool result = _settings.SelectedRenderer switch
        {
            MugshotRenderer.Internal => InternalNeedsRegeneration(json, effectiveOutfitIdentityProvider),
            MugshotRenderer.LegacyPortraitCreator => _legacy.NeedsRegeneration(
                pngPath, legacyNifPath ?? string.Empty,
                legacyDataFolders ?? Array.Empty<string>(),
                legacyAutoGenerated),
            _ => false,
        };
        Trace($"EXIT tid={tid} png={fileLabel} active={_settings.SelectedRenderer} result={(result ? "STALE" : "FRESH")} elapsed={sw.ElapsedMilliseconds}ms");
        return result;
    }

    private static void Trace(string message)
    {
        // Both Debug and Trace listeners receive these — Debug captures in
        // VS output for unattached runs; Trace also flows to attached
        // diagnostic listeners (e.g. DebugView) without recompile.
        Debug.WriteLine($"[StalenessChecker] {message}");
        System.Diagnostics.Trace.WriteLine($"[StalenessChecker] {message}");
    }

    /// <summary>
    /// Reads the "renderer" field from the metadata JSON and maps it to a
    /// <see cref="MugshotRenderer"/>. Legacy PNGs (which predate the field)
    /// are reported as <see cref="MugshotRenderer.LegacyPortraitCreator"/>.
    /// </summary>
    private static MugshotRenderer DetectRenderer(string parametersJson)
    {
        try
        {
            var token = JToken.Parse(parametersJson);
            string? renderer = (token as JObject)?["renderer"]?.Value<string>();
            if (string.Equals(renderer, InternalMugshotMetadata.RendererName, StringComparison.OrdinalIgnoreCase))
            {
                return MugshotRenderer.Internal;
            }
        }
        catch
        {
            // Malformed JSON — fall through to Legacy assumption.
        }
        return MugshotRenderer.LegacyPortraitCreator;
    }

    private bool InternalNeedsRegeneration(string parametersJson, Func<string>? effectiveOutfitIdentityProvider)
    {
        JObject? root;
        try
        {
            root = JToken.Parse(parametersJson) as JObject;
        }
        catch (Exception ex)
        {
            Trace($"  Internal: JSON parse failed ({ex.Message}); treating as STALE");
            return true;
        }
        if (root == null)
        {
            Trace("  Internal: JSON root is not an object; treating as STALE");
            return true;
        }

        // Resolution drift — UNGATED. A PNG at the wrong dimensions is a
        // structural mismatch, not a stylistic preference, so it shouldn't
        // share the AutoUpdateStaleMugshots gate with lighting / framing /
        // camera tweaks. (settings_hash also folds in resolution, but that
        // comparison only fires when AutoUpdateStaleMugshots is on; this
        // check ensures even users who've opted out of auto-update
        // regeneration get correctly-sized mugshots.)
        if (root["output_size"] is JArray sizeArr && sizeArr.Count >= 2)
        {
            int? pngW = sizeArr[0].Value<int?>();
            int? pngH = sizeArr[1].Value<int?>();
            int curW = _settings.InternalMugshot.OutputWidth;
            int curH = _settings.InternalMugshot.OutputHeight;
            if (pngW != curW || pngH != curH)
            {
                Trace($"  Internal: resolution drift png={pngW}x{pngH} current={curW}x{curH}");
                return true;
            }
        }

        // Attire drift — UNGATED. The Include Default Outfit / Include headgear
        // toggles change WHAT the mugshot depicts (nude vs. clothed, hair vs.
        // helmet), so a mismatch is a structural content mismatch like
        // resolution, not a stylistic tweak that should share the
        // AutoUpdateStaleMugshots gate. It's also schema-independent: the
        // settings-hash check below is compared at the PNG's stamped schema, so
        // a pre-v9 PNG (no attire fields) would never see the v9 toggle entries
        // and the hash alone could never flag attire drift. A PNG with no attire
        // metadata was rendered before the feature existed → treat as "no
        // attire" (both false), so old mugshots only regenerate once the user
        // actually enables a toggle.
        // Effective attire flags honor a per-NPC "Render" override keyed by the
        // stamped NPC FormKey; fall back to the global toggles when the PNG has
        // no parseable key (older PNGs) or the NPC has no override. Reused below
        // for the settings-hash recompute so both comparisons agree on what the
        // mugshot should depict.
        bool curOutfit, curHeadgear;
        if (FormKey.TryFactory(root["npc_form_key"]?.Value<string>() ?? string.Empty, out var stampedNpcKey))
        {
            (curOutfit, curHeadgear) = _settings.GetEffectiveAttireFlags(stampedNpcKey);
        }
        else
        {
            curOutfit = _settings.InternalMugshot.IncludeDefaultOutfit;
            curHeadgear = _settings.InternalMugshot.IncludeHeadgear;
        }
        bool pngOutfit = root["include_default_outfit"]?.Value<bool?>() ?? false;
        bool pngHeadgear = root["include_headgear"]?.Value<bool?>() ?? false;
        if (pngOutfit != curOutfit || pngHeadgear != curHeadgear)
        {
            Trace($"  Internal: attire drift png(outfit={pngOutfit},headgear={pngHeadgear}) current(outfit={curOutfit},headgear={curHeadgear})");
            return true;
        }

        // Outfit-identity drift — UNGATED for the same reason as the attire
        // toggles: a different depicted outfit is a content mismatch, not a
        // stylistic tweak. Compared by IDENTITY (FormKey string or "none")
        // only: switching patching modes, Include Outfit, or distributor
        // configs re-stales the tile ONLY when the resolved outfit actually
        // changes. PNGs without the stamp predate the feature (pre-v12) and
        // are left alone, matching the attire-toggle migration behavior; the
        // comparison is also skipped when the caller supplies no provider.
        string? stampedOutfitIdentity = root[InternalMugshotMetadata.EffectiveOutfitKey]?.Value<string>();
        string? currentOutfitIdentity = null;
        if (stampedOutfitIdentity != null && effectiveOutfitIdentityProvider != null)
        {
            try
            {
                currentOutfitIdentity = effectiveOutfitIdentityProvider();
            }
            catch (Exception ex)
            {
                Trace($"  Internal: outfit-identity provider threw ({ex.Message}); skipping outfit comparison");
            }
            if (currentOutfitIdentity != null &&
                !string.Equals(stampedOutfitIdentity, currentOutfitIdentity, StringComparison.OrdinalIgnoreCase))
            {
                Trace($"  Internal: outfit-identity drift png='{stampedOutfitIdentity}' current='{currentOutfitIdentity}'");
                return true;
            }
        }

        // Version drift (gated like the legacy path on AutoUpdateOldMugshots).
        if (_settings.AutoUpdateOldMugshots)
        {
            var pngVersionStr = root["renderer_version"]?.Value<string>();
            if (string.IsNullOrWhiteSpace(pngVersionStr) ||
                !Version.TryParse(pngVersionStr, out var pngVersion) ||
                pngVersion < CharacterViewerRendering.Version)
            {
                Trace($"  Internal: version drift png='{pngVersionStr}' current={CharacterViewerRendering.Version}");
                return true;
            }
        }

        // Missing-asset drift (gated on AutoUpdateMugshotsWithMissingAssets).
        // When the render couldn't resolve some meshes/textures, the stamped
        // arrays record them — the resulting PNG depicts an incomplete model
        // (wireframe shapes / placeholder textures). Treating it as stale
        // gives the user's next session a chance to pick up newly-installed
        // assets automatically. If the assets are still missing on re-render
        // the arrays get re-stamped and we flag stale again next session;
        // user can stop the loop by disabling the toggle or by fixing the
        // load order.
        if (_settings.AutoUpdateMugshotsWithMissingAssets)
        {
            InternalMugshotMetadata.TryReadMissingAssets(
                parametersJson,
                out var missingMeshes,
                out var missingTextures);
            if (missingMeshes.Count > 0 || missingTextures.Count > 0)
            {
                Trace($"  Internal: missing NPC-asset drift meshes={missingMeshes.Count} textures={missingTextures.Count}");
                return true;
            }
        }

        // Missing outfit/headgear assets have their own re-render toggle. Like the
        // NPC arrays they are installable — the render re-stamps and re-flags until
        // the file is present or the toggle is off. (The stale-physics notices are
        // read by a different key and stay neutral: nothing the user installs can
        // fix a broken mod link.)
        if (_settings.AutoUpdateMugshotsWithMissingOutfitAssets)
        {
            var missingOutfitAssets = InternalMugshotMetadata.TryReadMissingOutfitAssets(parametersJson);
            if (missingOutfitAssets.Count > 0)
            {
                Trace($"  Internal: missing outfit-asset drift outfit={missingOutfitAssets.Count}");
                return true;
            }
        }

        // Warning-icon visibility drift (ungated — a deliberate user action).
        // A stamp present while its "Show ... Icon" toggle is OFF marks the
        // PNG stale so it re-renders once WITHOUT the stamp (the generator
        // gates stamping on the same toggle), after which this check goes
        // quiet for it. The toggles are intentionally NOT in the settings
        // hash: flipping one refreshes exactly the mugshots that were
        // displaying that icon, not every mugshot. Turning a toggle back ON
        // cannot resurrect icons for PNGs rendered while it was off — the
        // information was never recorded.
        if (!_settings.InternalMugshot.ShowMissingNpcAssetsIcon)
        {
            InternalMugshotMetadata.TryReadMissingAssets(
                parametersJson, out var stampedMeshes, out var stampedTextures);
            var stampedFaceGen = InternalMugshotMetadata.TryReadFaceGenMismatch(parametersJson);
            if (stampedMeshes.Count > 0 || stampedTextures.Count > 0 || stampedFaceGen != null)
            {
                Trace($"  Internal: npc-assets icon disabled but PNG carries stamp (meshes={stampedMeshes.Count} textures={stampedTextures.Count} facegen={stampedFaceGen != null})");
                return true;
            }
        }
        if (!_settings.InternalMugshot.ShowMissingOutfitAssetsIcon &&
            (InternalMugshotMetadata.TryReadPhysicsConfigNotices(parametersJson).Count > 0 ||
             InternalMugshotMetadata.TryReadMissingOutfitAssets(parametersJson).Count > 0))
        {
            Trace("  Internal: outfit-assets icon disabled but PNG carries outfit-asset stamps");
            return true;
        }

        // Settings drift (gated on AutoUpdateStaleMugshots). The hash is
        // schema-versioned: each pipeline_schema bump is append-only, so
        // a v0 PNG's hash can be reproduced from current cfg by stopping
        // at the v0 boundary. This lets us add new toggles in v(N+1)
        // without invalidating v(N) PNGs — their stamped hash includes
        // only v(N) fields and the comparison hash is recomputed at
        // matching v(N), so the toggle flip in v(N+1) doesn't drift the
        // comparison. Older PNGs stay "in spec at the time they were
        // generated" until the user manually regenerates them.
        if (_settings.AutoUpdateStaleMugshots)
        {
            int pngSchema = root[InternalMugshotMetadata.PipelineSchemaKey]?.Value<int?>() ?? 0;
            var pngHash = root["settings_hash"]?.Value<string>() ?? "";
            // v12 folds the outfit identity into the hash; recompute with the
            // current identity when available, else the stamped one so the
            // hash comparison stays neutral on outfit for legacy callers (the
            // ungated identity check above is the authoritative outfit gate).
            var currentHash = InternalMugshotMetadata.ComputeSettingsHashAtSchema(
                _settings.InternalMugshot, pngSchema, curOutfit, curHeadgear,
                currentOutfitIdentity ?? stampedOutfitIdentity);
            if (!string.Equals(pngHash, currentHash, StringComparison.OrdinalIgnoreCase))
            {
                Trace($"  Internal: settings-hash drift schema={pngSchema} png={pngHash[..Math.Min(8, pngHash.Length)]}.. current={currentHash[..Math.Min(8, currentHash.Length)]}..");
                return true;
            }
        }

        return false;
    }
}
