using System.ComponentModel;
using System.Reflection;
using FluentAssertions;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using NPC_Plugin_Chooser_2.Models;
using NPC_Plugin_Chooser_2.Tests.TestSupport;
using Xunit;

namespace NPC_Plugin_Chooser_2.Tests.Unit;

/// <summary>
/// Plain model / enum invariants: enum membership + ordinals, [Description] labels,
/// default property values, and the <see cref="ScreeningResult"/> / OutputValidation rows.
/// </summary>
public class ModelsAndEnumsTests
{
    private static string? Description<T>(T value) where T : Enum =>
        typeof(T).GetField(value.ToString())!
            .GetCustomAttribute<DescriptionAttribute>()?.Description;

    [Fact]
    public void PatchingMode_Members()
    {
        ((int)PatchingMode.Create).Should().Be(0);
        ((int)PatchingMode.CreateAndPatch).Should().Be(1);
        Enum.GetValues<PatchingMode>().Should().HaveCount(2);
    }

    [Fact]
    public void RecordOverrideHandlingMode_Members()
    {
        ((int)RecordOverrideHandlingMode.Ignore).Should().Be(0);
        ((int)RecordOverrideHandlingMode.Include).Should().Be(1);
        ((int)RecordOverrideHandlingMode.IncludeAsNew).Should().Be(2);
        Enum.GetValues<RecordOverrideHandlingMode>().Should().HaveCount(3);
    }

    [Fact]
    public void MugshotSourceType_Members()
    {
        ((int)MugshotSourceType.None).Should().Be(0);
        ((int)MugshotSourceType.DownloadedMugshots).Should().Be(1);
        ((int)MugshotSourceType.FaceFinder).Should().Be(2);
        ((int)MugshotSourceType.AutoGeneration).Should().Be(3);
    }

    [Fact]
    public void PortraitCameraMode_Members()
    {
        ((int)PortraitCameraMode.Portrait).Should().Be(0);
        ((int)PortraitCameraMode.Fixed).Should().Be(1);
    }

    [Fact]
    public void OutfitOverride_HasThreeMembersWithDescriptions()
    {
        Enum.GetValues<OutfitOverride>().Should().HaveCount(3);
        Description(OutfitOverride.UseModSetting).Should().Be("Use the setting from the mod");
        Description(OutfitOverride.Yes).Should().Be("Always include the outfit");
        Description(OutfitOverride.No).Should().Be("Never include the outfit");
    }

    [Fact]
    public void ValidationSeverity_Order()
    {
        ((int)ValidationSeverity.Error).Should().Be(0);
        ((int)ValidationSeverity.Warning).Should().Be(1);
        ((int)ValidationSeverity.Info).Should().Be(2);
    }

    [Fact]
    public void ValidationCheckKind_ContainsFaceGenAndSkyPatcher()
    {
        var names = Enum.GetNames<ValidationCheckKind>();
        names.Should().Contain(new[] { "Environment", "Selection", "Record", "Asset", "SkyPatcher", "FaceGen" });
    }

    [Fact]
    public void ValidationIssue_SeverityAndCheckTextProjections()
    {
        var issue = new ValidationIssue { Severity = ValidationSeverity.Warning, Check = ValidationCheckKind.FaceGen };
        issue.SeverityText.Should().Be("Warning");
        issue.CheckText.Should().Be("FaceGen");
        issue.NpcDisplayName.Should().BeEmpty();
        issue.Issue.Should().BeEmpty();
    }

    [Fact]
    public void ValidationRunResult_Defaults()
    {
        var r = new ValidationRunResult();
        r.Blocked.Should().BeFalse();
        r.BlockReason.Should().BeNull();
        r.Issues.Should().NotBeNull().And.BeEmpty();
        r.Notes.Should().NotBeNull().And.BeEmpty();
        // Collections are stable references (init-only get).
        var issues = r.Issues;
        r.Issues.Should().BeSameAs(issues);
    }

    [Fact]
    public void Settings_LoggingDefaults()
    {
        var s = new Settings();

        // Performance logging is the one logging channel that ships ON: the per-batch
        // "PERFORMANCE REPORT for Group: [...]" block is ordinary run output that the Run tab's
        // checkbox turns *off*, not opt-in diagnostics like the others.
        s.LogPerformance.Should().BeTrue();

        s.LogVerbose.Should().BeFalse();
        s.LogActivity.Should().BeFalse();
        s.LogStartup.Should().BeFalse();
        s.LogRecordProvenance.Should().BeFalse();
        s.LogAssetProvenance.Should().BeFalse();
    }

    [Fact]
    public void ModSetting_Defaults()
    {
        var m = new ModSetting();
        m.MergeInDependencyRecords.Should().BeTrue();
        m.CopyAssets.Should().BeTrue();
        m.MaxNestedIntervalDepth.Should().Be(2);
        m.ModRecordOverrideHandlingMode.Should().Be(RecordOverrideHandlingMode.Ignore);
        m.IsAutoGenerated.Should().BeFalse();
        m.IsFaceGenOnlyEntry.Should().BeFalse();
        m.CorrespondingModKeys.Should().NotBeNull().And.BeEmpty();
        m.NpcFormKeys.Should().NotBeNull().And.BeEmpty();
        m.MugShotFolderPaths.Should().NotBeNull().And.BeEmpty();
    }

    [Fact]
    public void NpcAppearanceData_And_NpcToken_Defaults()
    {
        var data = new NpcAppearanceData();
        data.ModName.Should().BeEmpty();
        data.AppearancePlugin.Should().Be(default(ModKey));

        var token = new NpcToken();
        token.CreationDate.Should().BeEmpty();
        token.CreatedPlugins.Should().NotBeNull().And.BeEmpty();
        token.ProcessedNpcs.Should().NotBeNull().And.BeEmpty();
    }

    [Fact]
    public void ScreeningResult_StoresAllFields()
    {
        var mod = MutagenFixtures.NewMod("App.esp");
        var npc = MutagenFixtures.NewNpc(mod, editorId: "TestNpc");
        var modSetting = new ModSetting { DisplayName = "MyMod" };
        var fk = npc.FormKey;

        var result = new ScreeningResult(true, npc, modSetting, fk);

        result.SelectionIsValid.Should().BeTrue();
        result.WinningNpcOverride.Should().BeSameAs(npc);
        result.AppearanceModSetting.Should().BeSameAs(modSetting);
        result.AppearanceNpcFormKey.Should().Be(fk);
    }
}
