using System.Collections.Generic;
using System.Linq;
using Mutagen.Bethesda.Plugins;
using NPC_Plugin_Chooser_2.BackEnd.CharacterViewerHost;
using NPC_Plugin_Chooser_2.Models;
using NPC_Plugin_Chooser_2.View_Models;
using Xunit;

namespace NPC_Plugin_Chooser_2.Tests.Unit;

/// <summary>
/// Pins the pure rules of the Mod Issues scanner: weight-sibling derivation,
/// eligibility filtering, and the per-NPC issue text/count aggregation the tab
/// displays.
/// </summary>
public class ModIssueScannerRuleTests
{
    // --- DeriveWeightSibling ---

    [Theory]
    [InlineData(@"meshes\armor\steel\cuirass_0.nif", @"meshes\armor\steel\cuirass_1.nif")]
    [InlineData(@"meshes\armor\steel\cuirass_1.nif", @"meshes\armor\steel\cuirass_0.nif")]
    [InlineData(@"meshes\armor\steel\CUIRASS_0.NIF", @"meshes\armor\steel\CUIRASS_1.nif")]
    public void DeriveWeightSibling_PairedNames(string input, string expected)
    {
        Assert.Equal(expected, ModIssueScanner.DeriveWeightSibling(input));
    }

    [Theory]
    [InlineData(@"meshes\armor\steel\cuirass.nif")]     // no weight suffix
    [InlineData(@"meshes\armor\steel\cuirass_2.nif")]   // not a weight pair
    [InlineData(@"meshes\armor\steel\cuirass_0.tri")]   // not a nif
    [InlineData("")]
    [InlineData(null)]
    public void DeriveWeightSibling_NonPairedNames_ReturnNull(string? input)
    {
        Assert.Null(ModIssueScanner.DeriveWeightSibling(input!));
    }

    // --- Eligibility ---

    private static ModSetting MakeMod(bool autoGenerated = false, bool folders = true, bool npcs = true)
    {
        var mod = new ModSetting
        {
            DisplayName = "Test Mod",
            IsAutoGenerated = autoGenerated,
        };
        if (folders) mod.CorrespondingFolderPaths.Add(@"C:\Mods\Test");
        if (npcs) mod.NpcFormKeys.Add(FormKey.Factory("000ABC:Test.esp"));
        return mod;
    }

    [Fact]
    public void Eligibility_RequiresFoldersAndNpcs_ExcludesAutoGenerated()
    {
        Assert.True(ModIssueScanner.IsEligible(MakeMod()));
        // Base Game / Creation Club synthetic entries are auto-generated.
        Assert.False(ModIssueScanner.IsEligible(MakeMod(autoGenerated: true)));
        // Mugshot-only mods have no folder paths.
        Assert.False(ModIssueScanner.IsEligible(MakeMod(folders: false)));
        Assert.False(ModIssueScanner.IsEligible(MakeMod(npcs: false)));
    }

    // --- Per-NPC aggregation (VM_ModIssueEntry) ---

    private static ModIssue Issue(ModIssueType type, string npc = "000ABC:Test.esp",
        string path = @"textures\missing.dds", string? shape = null, string? nif = null)
    {
        return new ModIssue
        {
            Type = type,
            NpcFormKey = string.IsNullOrEmpty(npc) ? FormKey.Null : FormKey.Factory(npc),
            NpcDisplayName = "Test NPC",
            AffectedPath = path,
            ShapeName = shape,
            NifPath = nif,
        };
    }

    [Fact]
    public void EntryAggregation_CountsAndGroups()
    {
        var result = new ModIssueScanResult
        {
            ScanCompleted = true,
            Issues = new List<ModIssue>
            {
                Issue(ModIssueType.MissingNifTexture, npc: "000AAA:Test.esp"),
                Issue(ModIssueType.MissingNifTexture, npc: "000BBB:Test.esp"),
                Issue(ModIssueType.MissingFaceGenMesh, npc: "000BBB:Test.esp",
                    path: @"meshes\actors\character\facegendata\facegeom\Test.esp\000BBB.nif"),
                Issue(ModIssueType.ModNotInstalled, npc: ""),
            },
        };

        // modsViewModel is only used by the command; null is acceptable for
        // aggregation assertions as long as the command isn't executed.
        var entry = new VM_ModIssueEntry("Test Mod", null!, result, null!);

        Assert.Equal(4, entry.TotalIssueCount);
        Assert.Equal(2, entry.AffectedNpcCount);
        Assert.Equal(2, entry.CountsByType[ModIssueType.MissingNifTexture]);
        Assert.Equal(1, entry.CountsByType[ModIssueType.MissingFaceGenMesh]);
        Assert.Single(entry.ModLevelIssues);
        Assert.Equal(2, entry.IssuesByNpc[FormKey.Factory("000BBB:Test.esp")].Count);
    }

    [Fact]
    public void EntrySummary_ModNotInstalled_WinsOverCounts()
    {
        var result = new ModIssueScanResult
        {
            ScanCompleted = true,
            Issues = new List<ModIssue> { Issue(ModIssueType.ModNotInstalled, npc: "") },
        };
        var entry = new VM_ModIssueEntry("Test Mod", null!, result, null!);
        Assert.Equal("Mod not installed", entry.SummaryText);
    }

    [Fact]
    public void BuildNpcIssueText_GroupsByTypeAndNamesShape()
    {
        var issues = new List<ModIssue>
        {
            Issue(ModIssueType.MissingNifTexture, path: @"textures\a.dds", shape: "Cuirass",
                nif: @"meshes\armor\cuirass_1.nif"),
            Issue(ModIssueType.MissingNifTexture, path: @"textures\b.dds", shape: "Cuirass",
                nif: @"meshes\armor\cuirass_1.nif"),
            Issue(ModIssueType.MissingArmaMesh, path: @"meshes\armor\gone.nif"),
        };

        var text = VM_ModIssueEntry.BuildNpcIssueText(issues);

        Assert.Contains("Missing texture:", text);
        Assert.Contains("Missing mesh:", text);
        Assert.Contains(@"textures\a.dds", text);
        Assert.Contains(@"textures\b.dds", text);
        Assert.Contains("shape 'Cuirass'", text);
        Assert.Contains("cuirass_1.nif", text);
        Assert.Contains(@"meshes\armor\gone.nif", text);
    }
}
