using System.Collections.Generic;
using System.Linq;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using NPC_Plugin_Chooser_2.BackEnd;
using NPC_Plugin_Chooser_2.BackEnd.CharacterViewerHost;
using NPC_Plugin_Chooser_2.Models;
using NPC_Plugin_Chooser_2.View_Models;
using Xunit;

namespace NPC_Plugin_Chooser_2.Tests.Unit;

/// <summary>
/// Pins the pure rules of the Mod Issues scanner: weight-sibling derivation,
/// eligibility filtering, and the per-NPC issue text/count aggregation the tab
/// displays.
/// </summary>
public class ModIssueScannerRuleTests
{
    // --- DeriveWeightSibling ---

    [Theory]
    [InlineData(@"meshes\armor\steel\cuirass_0.nif", @"meshes\armor\steel\cuirass_1.nif")]
    [InlineData(@"meshes\armor\steel\cuirass_1.nif", @"meshes\armor\steel\cuirass_0.nif")]
    [InlineData(@"meshes\armor\steel\CUIRASS_0.NIF", @"meshes\armor\steel\CUIRASS_1.nif")]
    public void DeriveWeightSibling_PairedNames(string input, string expected)
    {
        Assert.Equal(expected, ModIssueScanner.DeriveWeightSibling(input));
    }

    [Theory]
    [InlineData(@"meshes\armor\steel\cuirass.nif")]     // no weight suffix
    [InlineData(@"meshes\armor\steel\cuirass_2.nif")]   // not a weight pair
    [InlineData(@"meshes\armor\steel\cuirass_0.tri")]   // not a nif
    [InlineData("")]
    [InlineData(null)]
    public void DeriveWeightSibling_NonPairedNames_ReturnNull(string? input)
    {
        Assert.Null(ModIssueScanner.DeriveWeightSibling(input!));
    }

    // --- Eligibility ---

    /// <summary>Eligibility now includes an installed-content check, so the folder
    /// (when present) must really exist with content for the positive cases.</summary>
    private static ModSetting MakeMod(bool autoGenerated = false, bool folders = true, bool npcs = true,
        string? folderPath = null)
    {
        var mod = new ModSetting
        {
            DisplayName = "Test Mod",
            IsAutoGenerated = autoGenerated,
        };
        if (folders) mod.CorrespondingFolderPaths.Add(folderPath ?? @"C:\Mods\Test");
        if (npcs) mod.NpcFormKeys.Add(FormKey.Factory("000ABC:Test.esp"));
        return mod;
    }

    private static string MakeContentFolder(TestSupport.TempDir dir)
    {
        System.IO.File.WriteAllText(System.IO.Path.Combine(dir.Path, "dummy.esp"), "x");
        return dir.Path;
    }

    [Fact]
    public void Eligibility_RequiresFoldersAndNpcs_ExcludesAutoGenerated()
    {
        using var dir = new TestSupport.TempDir("eligible");
        var folder = MakeContentFolder(dir);

        Assert.True(ModIssueScanner.IsEligible(MakeMod(folderPath: folder)));
        // Base Game / Creation Club synthetic entries are auto-generated.
        Assert.False(ModIssueScanner.IsEligible(MakeMod(autoGenerated: true, folderPath: folder)));
        // Mugshot-only mods have no folder paths.
        Assert.False(ModIssueScanner.IsEligible(MakeMod(folders: false)));
        Assert.False(ModIssueScanner.IsEligible(MakeMod(npcs: false, folderPath: folder)));
    }

    // --- FaceGen path → subject FormKey (grouped-row template attribution) ---

    [Theory]
    [InlineData(@"meshes\actors\character\facegendata\facegeom\bsheartland.esm\000792c4.nif", "0792C4:BSHeartland.esm")]
    [InlineData(@"meshes\actors\character\FaceGenData\FaceGeom\Skyrim.esm\00013BAB.nif", "013BAB:Skyrim.esm")]
    [InlineData(@"textures\actors\character\facegendata\facetint\Skyrim.esm\00013BAB.dds", "013BAB:Skyrim.esm")]
    public void TryParseFaceGenSubjectKey_DecodesPluginAndFormId(string path, string expected)
    {
        Assert.Equal(FormKey.Factory(expected), VM_ModIssues.TryParseFaceGenSubjectKey(path));
    }

    [Theory]
    [InlineData(@"meshes\actors\character\character assets\femalebody_1.nif")] // not FaceGen
    [InlineData(@"meshes\actors\character\facegendata\facegeom\Skyrim.esm\notahexid.nif")]
    [InlineData("")]
    [InlineData(null)]
    public void TryParseFaceGenSubjectKey_NonFaceGenPaths_ReturnNull(string? path)
    {
        Assert.Null(VM_ModIssues.TryParseFaceGenSubjectKey(path));
    }

    [Fact]
    public void Eligibility_RequiresInstalledContent()
    {
        // A ModSetting whose folders were all deleted (or are empty) must drop out of the
        // Mod Issues tab entirely instead of lingering as "mod not installed"
        // (user-requested 2026-08-16). The cache prune in RunAsync keys off this.
        Assert.False(ModIssueScanner.IsEligible(MakeMod()),
            @"C:\Mods\Test does not exist — the mod is uninstalled");

        using var empty = new TestSupport.TempDir("eligible-empty");
        Assert.False(ModIssueScanner.IsEligible(MakeMod(folderPath: empty.Path)),
            "an existing but EMPTY folder is not installed content");

        using var full = new TestSupport.TempDir("eligible-full");
        Assert.True(ModIssueScanner.IsEligible(MakeMod(folderPath: MakeContentFolder(full))));
    }

    // --- Per-NPC aggregation (VM_ModIssueEntry) ---

    private static ModIssue Issue(ModIssueType type, string npc = "000ABC:Test.esp",
        string path = @"textures\missing.dds", string? shape = null, string? nif = null)
    {
        return new ModIssue
        {
            Type = type,
            NpcFormKey = string.IsNullOrEmpty(npc) ? FormKey.Null : FormKey.Factory(npc),
            NpcDisplayName = "Test NPC",
            AffectedPath = path,
            ShapeName = shape,
            NifPath = nif,
        };
    }

    [Fact]
    public void EntryAggregation_CountsAndGroups()
    {
        var result = new ModIssueScanResult
        {
            ScanCompleted = true,
            Issues = new List<ModIssue>
            {
                Issue(ModIssueType.MissingNifTexture, npc: "000AAA:Test.esp"),
                Issue(ModIssueType.MissingNifTexture, npc: "000BBB:Test.esp"),
                Issue(ModIssueType.MissingFaceGenMesh, npc: "000BBB:Test.esp",
                    path: @"meshes\actors\character\facegendata\facegeom\Test.esp\000BBB.nif"),
                Issue(ModIssueType.ModNotInstalled, npc: ""),
            },
        };

        // modsViewModel is only used by the command; null is acceptable for
        // aggregation assertions as long as the command isn't executed.
        var entry = new VM_ModIssueEntry("Test Mod", null!, result, result.Issues, null!);

        Assert.Equal(4, entry.TotalIssueCount);
        Assert.Equal(2, entry.AffectedNpcCount);
        Assert.Equal(2, entry.CountsByType[ModIssueType.MissingNifTexture]);
        Assert.Equal(1, entry.CountsByType[ModIssueType.MissingFaceGenMesh]);
        Assert.Single(entry.ModLevelIssues);
        Assert.Equal(2, entry.IssuesByNpc[FormKey.Factory("000BBB:Test.esp")].Count);
    }

    [Fact]
    public void EntrySummary_ModNotInstalled_WinsOverCounts()
    {
        var result = new ModIssueScanResult
        {
            ScanCompleted = true,
            Issues = new List<ModIssue> { Issue(ModIssueType.ModNotInstalled, npc: "") },
        };
        var entry = new VM_ModIssueEntry("Test Mod", null!, result, result.Issues, null!);
        Assert.Equal("Mod not installed", entry.SummaryText);
    }

    // --- Slot-aware texture severity (ClassifyNifTextureSlot) ---
    //
    // Engine facts pinned here: the face-tint path/slot is engine-managed (the
    // game loads the tint ONLY from the canonical FormID-derived path — proven
    // in-game 2026-08-15, docs/FaceTintEngineTest-2026-08.md), environment slots
    // are sampled only under env-mapping shader config, and only diffuse/normal
    // misses are visibly broken; the rest are Notes.

    private const uint EnvFlag = 0x00000080;     // SLSF1_Environment_Mapping
    private const uint EyeEnvFlag = 0x00020000;  // SLSF1_Eye_Environment_Mapping

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    public void Slots0And1_AreAlwaysIssues(int slot)
    {
        Assert.Equal(ModIssueSeverity.Issue,
            ModIssueScanner.ClassifyNifTextureSlot(slot, isFaceGenHead: false,
                shaderType: 0, shaderFlags1: 0, regularizedPath: @"textures\a.dds"));
    }

    [Fact]
    public void FaceTintPattern_IsNeverReported_AnySlot()
    {
        // NIF reused from another NPC/plugin bakes a wrong-plugin tint path
        // (the NITHI/Beyond Reach class): engine never reads it.
        Assert.Null(ModIssueScanner.ClassifyNifTextureSlot(6, isFaceGenHead: true,
            shaderType: 4, shaderFlags1: 0,
            regularizedPath: @"textures\actors\character\facegendata\facetint\skyrim.esm\000058b0.dds"));
        // Belt: even in an unexpected slot the pattern is engine-managed.
        Assert.Null(ModIssueScanner.ClassifyNifTextureSlot(0, isFaceGenHead: false,
            shaderType: 0, shaderFlags1: 0,
            regularizedPath: @"textures\facegendata\facetint\dawnguard.esm\00006978.dds"));
    }

    [Fact]
    public void Slot6_OnFaceGenHead_IsSkipped_EvenForJunkStrings()
    {
        // "moneyistoiletpaper": authors put junk in the tint slot because the
        // engine ignores it — the scanner must too.
        Assert.Null(ModIssueScanner.ClassifyNifTextureSlot(6, isFaceGenHead: true,
            shaderType: 4, shaderFlags1: 0, regularizedPath: "moneyistoiletpaper"));
        // On a non-FaceGen shape slot 6 is a real (inner-layer) channel: Note.
        Assert.Equal(ModIssueSeverity.Note,
            ModIssueScanner.ClassifyNifTextureSlot(6, isFaceGenHead: false,
                shaderType: 11, shaderFlags1: 0, regularizedPath: @"textures\inner.dds"));
    }

    [Theory]
    [InlineData(4)]
    [InlineData(5)]
    public void EnvSlots_GatedOnShaderConfig(int slot)
    {
        // No env shader type, no env flags → the engine never samples the slot.
        Assert.Null(ModIssueScanner.ClassifyNifTextureSlot(slot, isFaceGenHead: false,
            shaderType: 0, shaderFlags1: 0, regularizedPath: @"textures\cubemaps\e.dds"));
        // Env-map shader type → sampled, subtle → Note.
        Assert.Equal(ModIssueSeverity.Note,
            ModIssueScanner.ClassifyNifTextureSlot(slot, isFaceGenHead: false,
                shaderType: 1, shaderFlags1: 0, regularizedPath: @"textures\cubemaps\e.dds"));
        // Default shader type with the env flag set → Note.
        Assert.Equal(ModIssueSeverity.Note,
            ModIssueScanner.ClassifyNifTextureSlot(slot, isFaceGenHead: false,
                shaderType: 0, shaderFlags1: EnvFlag, regularizedPath: @"textures\cubemaps\e.dds"));
        // Eye env-map flag counts too (singular-"Eye" eyeballs).
        Assert.Equal(ModIssueSeverity.Note,
            ModIssueScanner.ClassifyNifTextureSlot(slot, isFaceGenHead: false,
                shaderType: 16, shaderFlags1: EyeEnvFlag, regularizedPath: @"textures\cubemaps\e.dds"));
        // Unknown shader info fails conservative: report rather than skip.
        Assert.Equal(ModIssueSeverity.Note,
            ModIssueScanner.ClassifyNifTextureSlot(slot, isFaceGenHead: false,
                shaderType: NifHandler.UnknownShaderType, shaderFlags1: 0,
                regularizedPath: @"textures\cubemaps\e.dds"));
    }

    [Theory]
    [InlineData(2)] // glow / subsurface (mouthhuman_sk)
    [InlineData(3)] // detail / greyscale palette
    [InlineData(7)] // specular / backlight (mouthhuman_s, femalehead_s)
    [InlineData(8)] // spare
    public void SecondarySlots_AreNotes(int slot)
    {
        Assert.Equal(ModIssueSeverity.Note,
            ModIssueScanner.ClassifyNifTextureSlot(slot, isFaceGenHead: false,
                shaderType: 0, shaderFlags1: 0, regularizedPath: @"textures\sec.dds"));
    }

    // --- Ignore-entry matching (Settings.ModIssuesIgnored) ---

    [Fact]
    public void IgnoreEntry_FileScope_MatchesEveryNpcOfThePath()
    {
        var entry = new ModIssueIgnoreEntry
        {
            ModName = "Test Mod",
            Type = ModIssueType.MissingNifTexture,
            AffectedPath = @"textures\missing.dds",
        };

        Assert.True(entry.Matches("Test Mod", Issue(ModIssueType.MissingNifTexture, npc: "000AAA:Test.esp")));
        Assert.True(entry.Matches("TEST MOD", Issue(ModIssueType.MissingNifTexture, npc: "000BBB:Test.esp")));
        Assert.False(entry.Matches("Other Mod", Issue(ModIssueType.MissingNifTexture)));
        Assert.False(entry.Matches("Test Mod", Issue(ModIssueType.MissingArmaMesh)));
        Assert.False(entry.Matches("Test Mod",
            Issue(ModIssueType.MissingNifTexture, path: @"textures\other.dds")));
    }

    [Fact]
    public void IgnoreEntry_AllModsScope_IgnoresModName()
    {
        var entry = new ModIssueIgnoreEntry
        {
            ModName = "Where It Was Created",
            AllMods = true,
            Type = ModIssueType.MissingNifTexture,
            AffectedPath = @"textures\actors\character\mouth\mouthhuman_sk.dds",
        };

        // The vanilla-recurring-file case: one global entry suppresses the path everywhere.
        Assert.True(entry.Matches("Mod A",
            Issue(ModIssueType.MissingNifTexture, path: @"textures\actors\character\mouth\mouthhuman_sk.dds")));
        Assert.True(entry.Matches("Mod B",
            Issue(ModIssueType.MissingNifTexture, path: @"textures\actors\character\mouth\mouthhuman_sk.dds")));
        Assert.False(entry.Matches("Mod A",
            Issue(ModIssueType.MissingNifTexture, path: @"textures\other.dds")));
    }

    [Fact]
    public void IgnoreEntry_ExactScope_PinsNpcNifAndShape()
    {
        var entry = new ModIssueIgnoreEntry
        {
            ModName = "Test Mod",
            Type = ModIssueType.MissingNifTexture,
            AffectedPath = @"textures\missing.dds",
            NpcFormKey = FormKey.Factory("000AAA:Test.esp"),
            NifPath = @"meshes\armor\cuirass_1.nif",
            ShapeName = "Cuirass",
        };

        Assert.True(entry.Matches("Test Mod", Issue(ModIssueType.MissingNifTexture,
            npc: "000AAA:Test.esp", shape: "Cuirass", nif: @"meshes\armor\cuirass_1.nif")));
        // Different NPC, same file: not matched by the exact scope.
        Assert.False(entry.Matches("Test Mod", Issue(ModIssueType.MissingNifTexture,
            npc: "000BBB:Test.esp", shape: "Cuirass", nif: @"meshes\armor\cuirass_1.nif")));
        // Same NPC, different shape.
        Assert.False(entry.Matches("Test Mod", Issue(ModIssueType.MissingNifTexture,
            npc: "000AAA:Test.esp", shape: "Boots", nif: @"meshes\armor\cuirass_1.nif")));
    }

    // --- Scan-target resolution (toolbar searchable combo) ---

    private static readonly List<string> ScanTargetMods = new()
    {
        "Bijin AIO", "Bijin Warmaidens", "Pandorable NPCs", "The Ordinary Women",
    };

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("ALL")]
    [InlineData("all")] // the sentinel is case-insensitive
    public void ResolveScanTarget_AllOrEmpty_MeansEveryMod(string? text)
    {
        Assert.Null(VM_ModIssues.ResolveScanTarget(text, ScanTargetMods));
    }

    [Fact]
    public void ResolveScanTarget_ExactName_WinsOverSubstringMatches()
    {
        // "Bijin AIO" is also a substring... of itself only, but "Bijin" appears
        // in two mods — an exact name must resolve to just that mod.
        var resolved = VM_ModIssues.ResolveScanTarget("bijin aio", ScanTargetMods);
        Assert.NotNull(resolved);
        Assert.Equal(new[] { "Bijin AIO" }, resolved);
    }

    [Fact]
    public void ResolveScanTarget_PartialText_ReturnsEverySubstringMatch()
    {
        var resolved = VM_ModIssues.ResolveScanTarget(" bijin ", ScanTargetMods);
        Assert.NotNull(resolved);
        Assert.Equal(new[] { "Bijin AIO", "Bijin Warmaidens" }, resolved);
    }

    [Fact]
    public void ResolveScanTarget_NoMatch_ReturnsEmpty_NotAll()
    {
        // The caller must be able to tell "nothing matches" (skip the scan, tell
        // the user) apart from "scan everything" (null).
        var resolved = VM_ModIssues.ResolveScanTarget("does not exist", ScanTargetMods);
        Assert.NotNull(resolved);
        Assert.Empty(resolved);
    }

    [Fact]
    public void EligibilityBySettings_IsTheDiskFreeHalfOfIsEligible()
    {
        // The scan-target search box filters on the settings-only predicate (no
        // per-keystroke folder probes), so a configured-but-uninstalled mod may
        // pass it while failing full eligibility — ScanAsync re-applies the full
        // check, so such a pick just scans nothing.
        var uninstalled = MakeMod(); // folder path that doesn't exist on disk
        Assert.True(ModIssueScanner.IsEligibleBySettings(uninstalled));
        Assert.False(ModIssueScanner.IsEligible(uninstalled));

        Assert.False(ModIssueScanner.IsEligibleBySettings(MakeMod(autoGenerated: true)));
        Assert.False(ModIssueScanner.IsEligibleBySettings(MakeMod(folders: false)));
        Assert.False(ModIssueScanner.IsEligibleBySettings(MakeMod(npcs: false)));
    }

    // --- Per-plugin dark-face grading (multi-plugin mods, cache v9) ---

    private static Npc AddParts(Npc npc, params FormKey[] headParts)
    {
        foreach (var hp in headParts) npc.HeadParts.Add(hp.ToLink<IHeadPartGetter>());
        return npc;
    }

    [Fact]
    public void DarkFaceSignature_SameRecordContent_MatchesAcrossPlugins()
    {
        // The WICO shape of things: the same NPC override in two of the mod's
        // plugins. Identical content must collapse to ONE verdict row.
        var modA = TestSupport.MutagenFixtures.NewMod("WICO - Immersive People.esp");
        var modB = TestSupport.MutagenFixtures.NewMod("WICO - USSEP Compatible Patch.esp");
        var race = TestSupport.MutagenFixtures.NewRace(modA, "NordRace");
        var hp1 = FormKey.Factory("000AAA:Parts.esp");
        var hp2 = FormKey.Factory("000BBB:Parts.esp");

        var a = AddParts(TestSupport.MutagenFixtures.NewNpc(modA, race: race), hp1, hp2);
        var b = AddParts(TestSupport.MutagenFixtures.NewNpc(modB, race: race), hp1, hp2);

        Assert.Equal(ModIssueScanner.NpcDarkFaceSignature(a), ModIssueScanner.NpcDarkFaceSignature(b));
    }

    [Fact]
    public void DarkFaceSignature_DiscriminatesEveryAnalyzerInput()
    {
        var mod = TestSupport.MutagenFixtures.NewMod("Test.esp");
        var race = TestSupport.MutagenFixtures.NewRace(mod, "NordRace");
        var race2 = TestSupport.MutagenFixtures.NewRace(mod, "DarkElfRace");
        var hp1 = FormKey.Factory("000AAA:Parts.esp");
        var hp2 = FormKey.Factory("000BBB:Parts.esp");

        var baseline = AddParts(TestSupport.MutagenFixtures.NewNpc(mod, race: race), hp1, hp2);
        string baseSig = ModIssueScanner.NpcDarkFaceSignature(baseline);

        // Head-part ORDER is significant: singular slots are first-listed-wins.
        Assert.NotEqual(baseSig, ModIssueScanner.NpcDarkFaceSignature(
            AddParts(TestSupport.MutagenFixtures.NewNpc(mod, race: race), hp2, hp1)));
        Assert.NotEqual(baseSig, ModIssueScanner.NpcDarkFaceSignature(
            AddParts(TestSupport.MutagenFixtures.NewNpc(mod, race: race), hp1)));
        Assert.NotEqual(baseSig, ModIssueScanner.NpcDarkFaceSignature(
            AddParts(TestSupport.MutagenFixtures.NewNpc(mod, race: race2), hp1, hp2)));
        Assert.NotEqual(baseSig, ModIssueScanner.NpcDarkFaceSignature(
            AddParts(TestSupport.MutagenFixtures.NewNpc(mod, female: true, race: race), hp1, hp2)));
        Assert.NotEqual(baseSig, ModIssueScanner.NpcDarkFaceSignature(
            AddParts(TestSupport.MutagenFixtures.NewNpc(mod, traitsTemplate: true, template: baseline, race: race),
                hp1, hp2)));
    }

    [Fact]
    public void GroupPluginRecords_IdenticalCollapseWithJoinedLabel_DifferingStaySeparate()
    {
        var modA = TestSupport.MutagenFixtures.NewMod("A.esp");
        var modB = TestSupport.MutagenFixtures.NewMod("B.esp");
        var race = TestSupport.MutagenFixtures.NewRace(modA, "NordRace");
        var hp1 = FormKey.Factory("000AAA:Parts.esp");
        var hp2 = FormKey.Factory("000BBB:Parts.esp");

        // Identical records in both plugins -> one entry labeled with both carriers.
        var sameA = AddParts(TestSupport.MutagenFixtures.NewNpc(modA, race: race), hp1);
        var sameB = AddParts(TestSupport.MutagenFixtures.NewNpc(modB, race: race), hp1);
        var collapsed = ModIssueScanner.GroupPluginRecordsBySignature(new[]
        {
            (modA.ModKey, (INpcGetter)sameA),
            (modB.ModKey, (INpcGetter)sameB),
        });
        Assert.Single(collapsed);
        Assert.Equal("A.esp, B.esp", collapsed[0].Label);
        Assert.Same(sameA, collapsed[0].Record); // first carrier's record represents the group

        // Differing records -> per-plugin entries, plugin order preserved.
        var diffB = AddParts(TestSupport.MutagenFixtures.NewNpc(modB, race: race), hp1, hp2);
        var split = ModIssueScanner.GroupPluginRecordsBySignature(new[]
        {
            (modA.ModKey, (INpcGetter)sameA),
            (modB.ModKey, (INpcGetter)diffB),
        });
        Assert.Equal(2, split.Count);
        Assert.Equal("A.esp", split[0].Label);
        Assert.Equal("B.esp", split[1].Label);
    }

    // --- DFIR-derived exclusions (cache v11) ---

    [Fact]
    public void NeverManifested_PlayerAndPresets_AreSkipped()
    {
        var mod = TestSupport.MutagenFixtures.NewMod("Test.esp");

        var ordinary = TestSupport.MutagenFixtures.NewNpc(mod);
        Assert.False(ModIssueScanner.IsNeverManifestedNpc(ordinary.FormKey, ordinary));

        // The Player NPC record (000007:Skyrim.esm) — key-based, record content irrelevant.
        Assert.True(ModIssueScanner.IsNeverManifestedNpc(
            FormKey.Factory("000007:Skyrim.esm"), ordinary));

        // Chargen presets render from the record's morph data, never from FaceGen files
        // (WICO ships FaceGen for every vanilla preset — rows the game cannot display).
        var preset = TestSupport.MutagenFixtures.NewNpc(mod);
        preset.Configuration.Flags |= NpcConfiguration.Flag.IsCharGenFacePreset;
        Assert.True(ModIssueScanner.IsNeverManifestedNpc(preset.FormKey, preset));
    }

    [Fact]
    public void GhostKeyword_OnNpcRecord_DetectedForNoteDemotion()
    {
        var mod = TestSupport.MutagenFixtures.NewMod("Test.esp");

        var plain = TestSupport.MutagenFixtures.NewNpc(mod);
        Assert.False(ModIssueScanner.HasGhostKeyword(plain)); // null Keywords list

        var ghost = TestSupport.MutagenFixtures.NewNpc(mod);
        ghost.Keywords = new Noggog.ExtendedList<IFormLinkGetter<IKeywordGetter>>();
        ghost.Keywords.Add(Mutagen.Bethesda.FormKeys.SkyrimSE.Skyrim.Keyword.ActorTypeGhost);
        Assert.True(ModIssueScanner.HasGhostKeyword(ghost));

        var otherKeyword = TestSupport.MutagenFixtures.NewNpc(mod);
        otherKeyword.Keywords = new Noggog.ExtendedList<IFormLinkGetter<IKeywordGetter>>();
        otherKeyword.Keywords.Add(Mutagen.Bethesda.FormKeys.SkyrimSE.Skyrim.Keyword.ActorTypeNPC);
        Assert.False(ModIssueScanner.HasGhostKeyword(otherKeyword));
    }

    [Fact]
    public void BuildNpcIssueText_GroupsByTypeAndNamesShape()
    {
        var issues = new List<ModIssue>
        {
            Issue(ModIssueType.MissingNifTexture, path: @"textures\a.dds", shape: "Cuirass",
                nif: @"meshes\armor\cuirass_1.nif"),
            Issue(ModIssueType.MissingNifTexture, path: @"textures\b.dds", shape: "Cuirass",
                nif: @"meshes\armor\cuirass_1.nif"),
            Issue(ModIssueType.MissingArmaMesh, path: @"meshes\armor\gone.nif"),
        };

        var text = VM_ModIssueEntry.BuildNpcIssueText(issues);

        Assert.Contains("Missing texture:", text);
        Assert.Contains("Missing mesh:", text);
        Assert.Contains(@"textures\a.dds", text);
        Assert.Contains(@"textures\b.dds", text);
        Assert.Contains("shape 'Cuirass'", text);
        Assert.Contains("cuirass_1.nif", text);
        Assert.Contains(@"meshes\armor\gone.nif", text);
    }
}
