using FluentAssertions;
using NPC_Plugin_Chooser_2.BackEnd;
using NPC_Plugin_Chooser_2.View_Models;
using Xunit;

namespace NPC_Plugin_Chooser_2.Tests.Unit;

/// <summary>
/// Compile-time constants on <see cref="Patcher"/> / <see cref="VM_Run"/> that other
/// subsystems depend on: the stamped output-plugin header description (used by
/// <see cref="PatcherExtensions.TrimDependentPlugins"/> to identify this app's own
/// generated plugins) and the synthetic "all NPCs" group token (the default
/// <c>SelectedNpcGroup</c> and the BAT-export branch selector). These are pure literals,
/// so no environment, temp files, or Skyrim install are required.
/// </summary>
public class PatcherEnumsAndConstantsTests
{
    [Fact]
    public void PluginDescriptionSignature_ExactLiteral()
    {
        // This literal is written into every output plugin's ModHeader.Description
        // (Patcher.RunPatchingLogic) and matched verbatim by TrimDependentPlugins to
        // strip the app's own prior output from the load order before a re-run.
        // Changing it silently breaks self-output detection, so it is pinned here.
        Patcher.PluginDescriptionSignature.Should().Be("Generated By NPC Plugin Chooser 2");
    }

    [Fact]
    public void PluginDescriptionSignature_IsNonEmptyAndStable()
    {
        Patcher.PluginDescriptionSignature.Should().NotBeNullOrWhiteSpace();
    }

    [Fact]
    public void AllNpcsGroup_ExactLiteral()
    {
        VM_Run.ALL_NPCS_GROUP.Should().Be("<All NPCs>");
    }

    [Fact]
    public void AllNpcsGroup_PatcherAndVmRunAgree()
    {
        // Patcher.ALL_NPCS_GROUP is defined as `= VM_Run.ALL_NPCS_GROUP`; assert the two
        // surfaces stay in lockstep so a future edit to one cannot diverge from the other.
        Patcher.ALL_NPCS_GROUP.Should().Be(VM_Run.ALL_NPCS_GROUP);
        Patcher.ALL_NPCS_GROUP.Should().Be("<All NPCs>");
    }

    [Fact]
    public void AllNpcsGroup_IsNonEmpty()
    {
        VM_Run.ALL_NPCS_GROUP.Should().NotBeNullOrWhiteSpace();
        Patcher.ALL_NPCS_GROUP.Should().NotBeNullOrWhiteSpace();
    }

    [Fact]
    public void AllNpcsGroup_DiffersFromPluginDescriptionSignature()
    {
        // Sanity: the two distinct constants must never collide (they live in different
        // namespaces of meaning — a group token vs. a plugin header stamp).
        Patcher.ALL_NPCS_GROUP.Should().NotBe(Patcher.PluginDescriptionSignature);
    }
}
