using FluentAssertions;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using NPC_Plugin_Chooser_2.BackEnd;
using NPC_Plugin_Chooser_2.Tests.TestSupport;
using Xunit;

namespace NPC_Plugin_Chooser_2.Tests.Unit;

/// <summary>
/// <see cref="PatcherExtensions.TrimDependentPlugins"/> — drops this app's own generated
/// plugins (identified by the stamped header description
/// <see cref="Patcher.PluginDescriptionSignature"/>) plus anything that masters to them,
/// and optionally an explicit <c>outputModKey</c> fallback, from a load order. Pure
/// in-memory logic over <see cref="IModListingGetter{TMod}"/> — no Skyrim install needed.
///
/// All listings are built as <c>ModListing&lt;ISkyrimModGetter&gt;</c> (which implements
/// <c>IModListingGetter&lt;ISkyrimModGetter&gt;</c>) over real, freshly-built
/// <see cref="SkyrimMod"/> instances. The two-arg ctor
/// <c>new ModListing&lt;ISkyrimModGetter&gt;(modKey, mod, enabled: true)</c> also lets us
/// model the "listed but unreadable" case by passing a null mod with an explicit ModKey.
///
/// NOTE: PatcherExtensions.DuplicateFromOnlyReferencedGetters (both overloads) not covered:
/// they require a live RecordHandler / ILinkCache + Auxilliary.TryDuplicateGenericRecordAsNew,
/// i.e. a resolved Mutagen environment / Skyrim install, so they belong to the integration wave.
/// </summary>
public class PatcherExtensionsTests
{
    // The exact literal the extension compares the header Description against.
    // Mirrors Patcher.PluginDescriptionSignature ("Generated By NPC Plugin Chooser 2").
    private const string Stamp = Patcher.PluginDescriptionSignature;

    private static SkyrimMod NewMod(string fileName) =>
        new(ModKey.FromFileName(fileName), MutagenFixtures.Release);

    /// <summary>Stamps a mod's header with the generated-plugin signature.</summary>
    private static SkyrimMod Stamped(string fileName, string? description = null)
    {
        var mod = NewMod(fileName);
        mod.ModHeader.Description = description ?? Stamp;
        return mod;
    }

    /// <summary>Adds master references to a mod so it "depends on" the given ModKeys.</summary>
    private static SkyrimMod WithMasters(SkyrimMod mod, params ModKey[] masters)
    {
        foreach (var m in masters)
        {
            mod.ModHeader.MasterReferences.Add(
                new Mutagen.Bethesda.Plugins.Records.MasterReference { Master = m });
        }
        return mod;
    }

    /// <summary>Wraps a real mod as an enabled listing under the getter interface.</summary>
    private static IModListingGetter<ISkyrimModGetter> Listing(SkyrimMod mod) =>
        new ModListing<ISkyrimModGetter>(mod.ModKey, mod, enabled: true);

    /// <summary>A listed-but-unreadable plugin: a real ModKey but a null .Mod.</summary>
    private static IModListingGetter<ISkyrimModGetter> NullModListing(ModKey key) =>
        new ModListing<ISkyrimModGetter>(key, null!, enabled: true);

    private static string[] Names(IEnumerable<IModListingGetter<ISkyrimModGetter>> result) =>
        result.Select(x => x.ModKey.FileName.String).ToArray();

    [Fact]
    public void Signature_MatchesPatcherConstant()
    {
        // Guards the literal the trimming relies on against an accidental rename.
        Patcher.PluginDescriptionSignature.Should().Be("Generated By NPC Plugin Chooser 2");
    }

    [Fact]
    public void Empty_ReturnsEmpty()
    {
        var result = Array.Empty<IModListingGetter<ISkyrimModGetter>>().TrimDependentPlugins();
        result.Should().BeEmpty();
    }

    [Fact]
    public void StampedPlugin_IsExcluded_UnstampedKept_AndOrderPreserved()
    {
        var a = NewMod("A.esp");           // unstamped
        var stamped = Stamped("B.esp");    // generated by us
        var c = NewMod("C.esp");           // unstamped

        var result = new[] { Listing(a), Listing(stamped), Listing(c) }.TrimDependentPlugins();

        Names(result).Should().Equal("A.esp", "C.esp");
    }

    [Fact]
    public void NoStampedPlugins_KeepsEverythingInOrder()
    {
        var a = NewMod("A.esp");
        var b = NewMod("B.esp");
        var c = NewMod("C.esp");

        var result = new[] { Listing(a), Listing(b), Listing(c) }.TrimDependentPlugins();

        Names(result).Should().Equal("A.esp", "B.esp", "C.esp");
    }

    [Fact]
    public void TransitiveDependents_AreExcluded_WhenListedAfterTheirMaster()
    {
        var s = Stamped("S.esp");
        var d1 = WithMasters(NewMod("D1.esp"), s.ModKey);   // direct dependent
        var d2 = WithMasters(NewMod("D2.esp"), d1.ModKey);  // transitive dependent
        var keep = NewMod("Keep.esp");                      // unrelated

        var result = new[] { Listing(s), Listing(d1), Listing(d2), Listing(keep) }
            .TrimDependentPlugins();

        Names(result).Should().Equal("Keep.esp");
    }

    [Fact]
    public void Dependent_MasteringMultiplePlugins_ExcludedIfAnyMasterIsRemoved()
    {
        var stamped = Stamped("Gen.esp");
        var innocent = NewMod("Innocent.esp");
        // depends on both an innocent plugin and a stamped one -> still excluded.
        var dep = WithMasters(NewMod("Dep.esp"), innocent.ModKey, stamped.ModKey);

        var result = new[] { Listing(stamped), Listing(innocent), Listing(dep) }
            .TrimDependentPlugins();

        Names(result).Should().Equal("Innocent.esp");
    }

    [Fact]
    public void TransitiveDependent_ListedBeforeItsMaster_IsKept_SinglePassForwardOnly()
    {
        // The trim seeds mastersToRemove only with stamped mods up front, then extends it
        // while walking the list forward. A transitive dependent that appears BEFORE the
        // intermediate that gets removed is therefore evaluated too early and survives.
        // (Direct dependents of the stamped plugin are still caught regardless of order,
        // because the stamped key is in the seed before the loop starts.)
        var s = Stamped("S.esp");
        var d1 = WithMasters(NewMod("D1.esp"), s.ModKey);   // direct dependent of stamped
        var d2 = WithMasters(NewMod("D2.esp"), d1.ModKey);  // transitive (only via D1)

        // Order: D2 first, then D1, then S.
        var result = new[] { Listing(d2), Listing(d1), Listing(s) }.TrimDependentPlugins();

        // D1 is a direct dependent of the stamped S (seeded) -> removed even though listed
        // before S. D2 depends only on D1, which wasn't yet in the remove-set when D2 was
        // visited -> D2 is kept. S is stamped -> removed.
        Names(result).Should().Equal("D2.esp");
    }

    [Fact]
    public void OutputModKey_Fallback_ExcludesUnstampedKeyAndItsDependents()
    {
        var output = NewMod("Output.esp");                          // NOT stamped
        var dep = WithMasters(NewMod("DepOnOutput.esp"), output.ModKey);
        var other = NewMod("Other.esp");

        var result = new[] { Listing(output), Listing(dep), Listing(other) }
            .TrimDependentPlugins(output.ModKey);

        Names(result).Should().Equal("Other.esp");
    }

    [Fact]
    public void OutputModKey_Null_IsNoOp()
    {
        var a = NewMod("A.esp");
        var b = NewMod("B.esp");

        var result = new[] { Listing(a), Listing(b) }.TrimDependentPlugins(ModKey.Null);

        Names(result).Should().Equal("A.esp", "B.esp");
    }

    [Fact]
    public void OutputModKey_NotPresentInLoadOrder_StillNoCrashAndOthersKept()
    {
        var a = NewMod("A.esp");
        var b = NewMod("B.esp");
        var absent = ModKey.FromFileName("Absent.esp"); // not in the load order at all

        var result = new[] { Listing(a), Listing(b) }.TrimDependentPlugins(absent);

        // Nothing in the order matches/depends on the absent key -> everything kept.
        Names(result).Should().Equal("A.esp", "B.esp");
    }

    [Fact]
    public void OutputModKey_EqualToAlreadyStampedPlugin_NoDoubleExclusion()
    {
        // Passing the stamped plugin's own key as the fallback must not break anything;
        // it's already in the remove-set so the guard skips re-adding it.
        var stamped = Stamped("Gen.esp");
        var keep = NewMod("Keep.esp");

        var result = new[] { Listing(stamped), Listing(keep) }
            .TrimDependentPlugins(stamped.ModKey);

        Names(result).Should().Equal("Keep.esp");
    }

    [Fact]
    public void NullMod_Listing_IsKept_BecauseMastersCannotBeInspected()
    {
        // A listed-but-unreadable plugin (Mod == null) is left in: we only remove plugins
        // we can positively identify as ours or as depending on ours.
        var nullMod = NullModListing(ModKey.FromFileName("Unreadable.esp"));
        var a = NewMod("A.esp");

        var result = new IModListingGetter<ISkyrimModGetter>[] { nullMod, Listing(a) }
            .TrimDependentPlugins();

        Names(result).Should().Equal("Unreadable.esp", "A.esp");
    }

    [Fact]
    public void NullModKey_Listing_IsDropped()
    {
        var nullKey = NullModListing(ModKey.Null); // IsNull ModKey
        var a = NewMod("A.esp");

        var result = new IModListingGetter<ISkyrimModGetter>[] { nullKey, Listing(a) }
            .TrimDependentPlugins();

        Names(result).Should().Equal("A.esp");
    }

    [Fact]
    public void StampComparison_IsExact_NearMissDescriptionsAreKept()
    {
        // .Equals against the exact signature is case-sensitive and whitespace-sensitive,
        // so descriptions that merely resemble the stamp must NOT be trimmed.
        var lower = Stamped("Lower.esp", Stamp.ToLowerInvariant());
        var trailingSpace = Stamped("Trailing.esp", Stamp + " ");
        var prefixed = Stamped("Prefixed.esp", "x" + Stamp);
        var substring = Stamped("Sub.esp", "Generated By NPC Plugin Chooser"); // missing the "2"

        var result = new[] { Listing(lower), Listing(trailingSpace), Listing(prefixed), Listing(substring) }
            .TrimDependentPlugins();

        Names(result).Should().Equal("Lower.esp", "Trailing.esp", "Prefixed.esp", "Sub.esp");
    }

    [Fact]
    public void ExactStampMatch_IsExcluded_EvenAmongNearMisses()
    {
        var near = Stamped("Near.esp", Stamp + "!"); // near miss -> kept
        var exact = Stamped("Exact.esp");            // exact -> removed
        var plain = NewMod("Plain.esp");             // no description -> kept

        var result = new[] { Listing(near), Listing(exact), Listing(plain) }
            .TrimDependentPlugins();

        Names(result).Should().Equal("Near.esp", "Plain.esp");
    }

    [Fact]
    public void PluginWithNullDescription_IsNotTreatedAsStamped()
    {
        // A brand-new mod has a null header Description; the x.Mod?.ModHeader.Description != null
        // guard must keep it (no NRE, not excluded).
        var plain = NewMod("Plain.esp");
        plain.ModHeader.Description.Should().BeNull("a fresh mod has no description");

        var result = new[] { Listing(plain) }.TrimDependentPlugins();

        Names(result).Should().Equal("Plain.esp");
    }

    [Fact]
    public void NonStampedMod_DependingOnAnotherNonStampedMod_IsKept()
    {
        // Mastering a plugin that is NOT in the remove-set has no effect.
        var basePlugin = NewMod("Base.esp");
        var dependent = WithMasters(NewMod("Dependent.esp"), basePlugin.ModKey);

        var result = new[] { Listing(basePlugin), Listing(dependent) }.TrimDependentPlugins();

        Names(result).Should().Equal("Base.esp", "Dependent.esp");
    }

    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    public void DependentOfStamped_ExcludedRegardlessOfOutputKeyArgument(bool passOutputKey)
    {
        // A direct dependent of a stamped plugin is excluded whether or not the optional
        // outputModKey is supplied (the stamp alone drives the exclusion).
        var stamped = Stamped("Gen.esp");
        var dependent = WithMasters(NewMod("Dep.esp"), stamped.ModKey);
        var keep = NewMod("Keep.esp");

        var listings = new[] { Listing(stamped), Listing(dependent), Listing(keep) };
        var result = passOutputKey
            ? listings.TrimDependentPlugins(ModKey.FromFileName("SomeOther.esp"))
            : listings.TrimDependentPlugins();

        Names(result).Should().Equal("Keep.esp");
    }
}
