using FluentAssertions;
using Mutagen.Bethesda.Plugins;
using NPC_Plugin_Chooser_2.BackEnd;
using NPC_Plugin_Chooser_2.Models;
using NPC_Plugin_Chooser_2.View_Models;
using Xunit;

namespace NPC_Plugin_Chooser_2.Tests.Unit;

/// <summary>
/// Newtonsoft round-trips through <see cref="JSONhandler{T}"/> for the persisted Models
/// (<see cref="ModSetting"/>, <see cref="NpcToken"/>, <see cref="NpcAppearanceData"/>).
/// The serializer settings (<c>JSONhandler&lt;T&gt;.GetMyMutagenJSONSettings</c>) register the
/// Mutagen converters (FormKey/ModKey &lt;-&gt; string), a StringEnumConverter
/// (enum as name), the read-only <c>ModSettingConverter</c> migration shim, and
/// <c>ObjectCreationHandling.Replace</c>. (See <c>JSONhandler.GetMyMutagenJSONSettings</c>.)
/// These tests assert the deterministic surface of the
/// models survives Serialize+Deserialize, that clones are reference-distinct, and that the
/// nullable <c>FormKey?</c> tuple element survives in both present and null forms.
/// Pure logic: no clock, no network, no game install.
/// </summary>
public class SerializableModelsRoundTripTests
{
    private static readonly FormKey Npc1 = FormKey.Factory("000801:Skyrim.esm");
    private static readonly FormKey Npc2 = FormKey.Factory("00ABCD:Skyrim.esm");
    private static readonly FormKey Npc3 = FormKey.Factory("0F1234:Dawnguard.esm");
    private static readonly ModKey ModA = ModKey.FromFileName("ModA.esp");
    private static readonly ModKey ModB = ModKey.FromFileName("ModB.esm");
    private static readonly ModKey ModC = ModKey.FromFileName("ModC.esl");

    // Round-trip via the production helpers, asserting both legs succeed.
    private static T RoundTrip<T>(T input)
    {
        var json = JSONhandler<T>.Serialize(input, out var serOk, out var serErr);
        serOk.Should().BeTrue("serialization should succeed: {0}", serErr);
        var clone = JSONhandler<T>.Deserialize(json, out var deOk, out var deErr);
        deOk.Should().BeTrue("deserialization should succeed: {0}", deErr);
        clone.Should().NotBeNull();
        return clone!;
    }

    // ── ModSetting ─────────────────────────────────────────────────────────────

    private static ModSetting MakeRichModSetting()
    {
        return new ModSetting
        {
            DisplayName = "Rich Mod",
            CorrespondingModKeys = new List<ModKey> { ModA, ModB },
            ResourceOnlyModKeys = new HashSet<ModKey> { ModC },
            // Sparse per-plugin merge overrides. Both values are present on purpose: `false` must
            // survive as an explicit choice, not be indistinguishable from "no entry".
            PluginMergeInOverrides = new Dictionary<ModKey, bool> { [ModC] = true, [ModB] = false },
            CorrespondingFolderPaths = new List<string> { @"C:\Mods\Base", @"C:\Mods\Override" },
            MugShotFolderPaths = new List<string> { @"C:\Mugshots\Rich" },
            IsFaceGenOnlyEntry = true,
            FaceGenOnlyNpcFormKeys = new HashSet<FormKey> { Npc1 },
            IsAutoGenerated = false,
            NpcFormKeys = new HashSet<FormKey> { Npc1, Npc2, Npc3 },
            AvailablePluginsForNpcs = new Dictionary<FormKey, List<ModKey>>
            {
                [Npc1] = new() { ModA, ModB },
                [Npc2] = new() { ModC },
                [Npc3] = new(), // empty list must survive as empty (not dropped)
            },
            AmbiguousNpcFormKeys = new HashSet<FormKey> { Npc1 },
            NpcPluginDisambiguation = new Dictionary<FormKey, ModKey> { [Npc1] = ModB },
            NpcFormKeysToDisplayName = new Dictionary<FormKey, string> { [Npc2] = "Lydia" },
            MergeInDependencyRecords = false,
            HasAlteredMergeLogic = true,
            HandleInjectedRecords = true,
            HasAlteredHandleInjectedRecordsLogic = true,
            Keywords = new HashSet<string> { "follower", "vanilla" },
            ModRecordOverrideHandlingMode = RecordOverrideHandlingMode.IncludeAsNew,
            MaxNestedIntervalDepth = 5,
            IncludeAllOverrides = true,
            PluginsWithOverrideRecords = new HashSet<ModKey> { ModA },
            IncludeOutfits = true,
            CopyAssets = false,
            OverwriteBaseGameAssets = true,
            HasBaseGameAssetPaths = true,
            BaseGameAssetPathCount = 42,
            DetectedWigArmors = new HashSet<FormKey> { Npc1 },
            DetectedWigArmatures = new HashSet<FormKey> { Npc3 },
            DetectedAntlerArmors = new HashSet<FormKey> { Npc2 },
            DetectedAntlerArmatures = new HashSet<FormKey> { Npc1 },
            DetectedAntlerHeadParts = new HashSet<FormKey> { Npc2 },
            NpcWigSources = new Dictionary<FormKey, List<NpcWigSource>>
            {
                [Npc1] = new()
                {
                    new NpcWigSource
                        { Kind = NpcWigSourceKind.WornArmor, RecordFormKey = Npc3, EditorId = "FoxGloveHairArma" },
                    new NpcWigSource
                        { Kind = NpcWigSourceKind.Outfit, RecordFormKey = Npc2, EditorId = string.Empty },
                },
            },
            ModWigHandlingMode = WigHandlingMode.ForwardToOutfit,
            ModAntlerHandlingMode = AntlerHandlingMode.Remove,
            ModTemplateHandlingMode = TemplateHandlingMode.GiveEachNpcOwnCopy,
            NpcFormKeysToNotifications = new Dictionary<FormKey,
                (NpcIssueType IssueType, string IssueMessage, FormKey? ReferencedFormKey)>
            {
                // present nullable FormKey
                [Npc1] = (NpcIssueType.Template, "templated to other NPC", Npc2),
                // null nullable FormKey
                [Npc2] = (NpcIssueType.Template, "no referenced key", null),
            },
            LastKnownState = new ModStateSnapshot
            {
                PluginSnapshots = { new FileSnapshot { FileName = "ModA.esp", FileSize = 1024, LastWriteTimeUtc = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc) } },
                DirectorySnapshots = { new DirectorySnapshot { Path = @"C:\Mods\Base\Meshes", FileCount = 7, LastWriteTimeUtc = new DateTime(2026, 2, 2, 0, 0, 0, DateTimeKind.Utc) } },
            },
        };
    }

    [Fact]
    public void ModSetting_ScalarsAndEnum_SurviveRoundTrip()
    {
        var clone = RoundTrip(MakeRichModSetting());

        clone.DisplayName.Should().Be("Rich Mod");
        clone.IsFaceGenOnlyEntry.Should().BeTrue();
        clone.IsAutoGenerated.Should().BeFalse();
        clone.MergeInDependencyRecords.Should().BeFalse();
        clone.HasAlteredMergeLogic.Should().BeTrue();
        clone.HandleInjectedRecords.Should().BeTrue();
        clone.HasAlteredHandleInjectedRecordsLogic.Should().BeTrue();
        clone.MaxNestedIntervalDepth.Should().Be(5);
        clone.IncludeAllOverrides.Should().BeTrue();
        clone.IncludeOutfits.Should().BeTrue();
        clone.CopyAssets.Should().BeFalse();
        clone.OverwriteBaseGameAssets.Should().BeTrue();
        clone.HasBaseGameAssetPaths.Should().BeTrue();
        clone.BaseGameAssetPathCount.Should().Be(42);
        clone.ModRecordOverrideHandlingMode.Should().Be(RecordOverrideHandlingMode.IncludeAsNew);
        clone.ModWigHandlingMode.Should().Be(WigHandlingMode.ForwardToOutfit);
        clone.ModAntlerHandlingMode.Should().Be(AntlerHandlingMode.Remove);
        clone.ModTemplateHandlingMode.Should().Be(TemplateHandlingMode.GiveEachNpcOwnCopy);
        clone.HasTemplatedNpcs.Should().BeTrue("the notification map carries Template entries");
        clone.DetectedWigArmors.Should().BeEquivalentTo(new[] { Npc1 });
        clone.DetectedWigArmatures.Should().BeEquivalentTo(new[] { Npc3 });
        clone.DetectedAntlerArmors.Should().BeEquivalentTo(new[] { Npc2 });
        clone.DetectedAntlerArmatures.Should().BeEquivalentTo(new[] { Npc1 });
        clone.DetectedAntlerHeadParts.Should().BeEquivalentTo(new[] { Npc2 });
        clone.HasWigArmors.Should().BeTrue();
        clone.HasWigSources.Should().BeTrue();
        clone.HasAntlers.Should().BeTrue();
    }

    [Fact]
    public void ModSetting_NpcWigSources_SurviveRoundTrip()
    {
        var clone = RoundTrip(MakeRichModSetting());

        clone.NpcWigSources.Should().ContainKey(Npc1);
        var entries = clone.NpcWigSources[Npc1];
        entries.Should().HaveCount(2);
        entries[0].Kind.Should().Be(NpcWigSourceKind.WornArmor);
        entries[0].RecordFormKey.Should().Be(Npc3);
        entries[0].EditorId.Should().Be("FoxGloveHairArma");
        entries[1].Kind.Should().Be(NpcWigSourceKind.Outfit);
        entries[1].RecordFormKey.Should().Be(Npc2);
        entries[1].EditorId.Should().BeEmpty();
    }

    [Fact]
    public void ModSetting_ModKeyAndFolderCollections_SurviveRoundTrip()
    {
        var clone = RoundTrip(MakeRichModSetting());

        clone.CorrespondingModKeys.Should().Equal(ModA, ModB);
        clone.ResourceOnlyModKeys.Should().BeEquivalentTo(new[] { ModC });
        clone.CorrespondingFolderPaths.Should().Equal(@"C:\Mods\Base", @"C:\Mods\Override");
        clone.MugShotFolderPaths.Should().Equal(@"C:\Mugshots\Rich");
        clone.FaceGenOnlyNpcFormKeys.Should().BeEquivalentTo(new[] { Npc1 });
        clone.NpcFormKeys.Should().BeEquivalentTo(new[] { Npc1, Npc2, Npc3 });
        clone.AmbiguousNpcFormKeys.Should().BeEquivalentTo(new[] { Npc1 });
        clone.PluginsWithOverrideRecords.Should().BeEquivalentTo(new[] { ModA });
        clone.Keywords.Should().BeEquivalentTo(new[] { "follower", "vanilla" });
    }

    [Fact]
    public void ModSetting_PluginMergeInOverrides_SurviveRoundTripAsModKeyedTriState()
    {
        var clone = RoundTrip(MakeRichModSetting());

        // ModKey as a dictionary KEY is the risky part — a broken key round-trip would silently
        // drop every per-plugin merge choice and reinstate the pre-2.2.3 all-or-nothing behaviour.
        clone.PluginMergeInOverrides.Should().HaveCount(2);
        clone.PluginMergeInOverrides.Should().ContainKey(ModC);
        clone.PluginMergeInOverrides[ModC].Should().BeTrue();
        clone.PluginMergeInOverrides[ModB].Should().BeFalse();

        // Plugins with no entry stay absent — that's what keeps their default live.
        clone.PluginMergeInOverrides.Should().NotContainKey(ModA);
    }

    [Fact]
    public void ModSetting_AvailablePluginsForNpcs_PreservesKeysAndOrderedValues()
    {
        var clone = RoundTrip(MakeRichModSetting());

        clone.AvailablePluginsForNpcs.Should().ContainKey(Npc1);
        clone.AvailablePluginsForNpcs[Npc1].Should().Equal(ModA, ModB);
        clone.AvailablePluginsForNpcs[Npc2].Should().Equal(ModC);
        // Empty value list must survive, not collapse to null or be dropped.
        clone.AvailablePluginsForNpcs.Should().ContainKey(Npc3);
        clone.AvailablePluginsForNpcs[Npc3].Should().NotBeNull().And.BeEmpty();
    }

    [Fact]
    public void ModSetting_NpcPluginDisambiguationAndDisplayNames_SurviveRoundTrip()
    {
        var clone = RoundTrip(MakeRichModSetting());

        clone.NpcPluginDisambiguation.Should().ContainKey(Npc1);
        clone.NpcPluginDisambiguation[Npc1].Should().Be(ModB);
        clone.NpcFormKeysToDisplayName.Should().ContainKey(Npc2);
        clone.NpcFormKeysToDisplayName[Npc2].Should().Be("Lydia");
    }

    [Fact]
    public void ModSetting_NotificationsTuple_PresentNullableFormKey_Survives()
    {
        var clone = RoundTrip(MakeRichModSetting());

        clone.NpcFormKeysToNotifications.Should().ContainKey(Npc1);
        var present = clone.NpcFormKeysToNotifications[Npc1];
        present.IssueType.Should().Be(NpcIssueType.Template);
        present.IssueMessage.Should().Be("templated to other NPC");
        present.ReferencedFormKey.Should().Be(Npc2);
        present.ReferencedFormKey.Should().NotBeNull();
    }

    [Fact]
    public void ModSetting_NotificationsTuple_NullNullableFormKey_Survives()
    {
        var clone = RoundTrip(MakeRichModSetting());

        clone.NpcFormKeysToNotifications.Should().ContainKey(Npc2);
        var nulled = clone.NpcFormKeysToNotifications[Npc2];
        nulled.IssueType.Should().Be(NpcIssueType.Template);
        nulled.IssueMessage.Should().Be("no referenced key");
        nulled.ReferencedFormKey.Should().BeNull();
    }

    [Fact]
    public void ModSetting_LastKnownState_SnapshotSurvivesAndCompactsEqual()
    {
        var original = MakeRichModSetting();
        var clone = RoundTrip(original);

        clone.LastKnownState.Should().NotBeNull();
        clone.LastKnownState!.PluginSnapshots.Should().ContainSingle();
        clone.LastKnownState.PluginSnapshots[0].FileName.Should().Be("ModA.esp");
        clone.LastKnownState.PluginSnapshots[0].FileSize.Should().Be(1024);
        clone.LastKnownState.DirectorySnapshots.Should().ContainSingle();
        clone.LastKnownState.DirectorySnapshots[0].FileCount.Should().Be(7);
        clone.LastKnownState.BsaSnapshots.Should().NotBeNull().And.BeEmpty();
        // The snapshot's own value-equality should agree the round-trip is faithful.
        clone.LastKnownState.Equals(original.LastKnownState).Should().BeTrue();
    }

    [Fact]
    public void ModSetting_Clone_IsReferenceDistinctFromOriginal()
    {
        var original = MakeRichModSetting();
        var clone = RoundTrip(original);

        clone.Should().NotBeSameAs(original);
        clone.CorrespondingModKeys.Should().NotBeSameAs(original.CorrespondingModKeys);
        clone.NpcFormKeys.Should().NotBeSameAs(original.NpcFormKeys);
        clone.AvailablePluginsForNpcs.Should().NotBeSameAs(original.AvailablePluginsForNpcs);
        clone.AvailablePluginsForNpcs[Npc1].Should().NotBeSameAs(original.AvailablePluginsForNpcs[Npc1]);
        clone.NpcFormKeysToNotifications.Should().NotBeSameAs(original.NpcFormKeysToNotifications);
        clone.LastKnownState.Should().NotBeSameAs(original.LastKnownState);

        // Mutating the clone must not bleed into the original.
        clone.CorrespondingModKeys.Add(ModKey.FromFileName("Extra.esp"));
        original.CorrespondingModKeys.Should().Equal(ModA, ModB);
    }

    [Fact]
    public void ModSetting_DefaultInstance_RoundTripsToEquivalentDefaults()
    {
        var clone = RoundTrip(new ModSetting());

        clone.DisplayName.Should().BeEmpty();
        clone.CorrespondingModKeys.Should().NotBeNull().And.BeEmpty();
        clone.ResourceOnlyModKeys.Should().NotBeNull().And.BeEmpty();
        clone.NpcFormKeys.Should().NotBeNull().And.BeEmpty();
        clone.AvailablePluginsForNpcs.Should().NotBeNull().And.BeEmpty();
        clone.NpcFormKeysToNotifications.Should().NotBeNull().And.BeEmpty();
        clone.MergeInDependencyRecords.Should().BeTrue();
        clone.CopyAssets.Should().BeTrue();
        clone.MaxNestedIntervalDepth.Should().Be(2);
        // ObjectCreationHandling.Replace: the default-init RecordOverrideHandlingMode.Ignore
        // (a non-null nullable) must be written and read back, not lost.
        clone.ModRecordOverrideHandlingMode.Should().Be(RecordOverrideHandlingMode.Ignore);
        clone.LastKnownState.Should().BeNull("no snapshot was assigned");
    }

    [Fact]
    public void ModSetting_NullOverrideHandlingMode_SurvivesAsNull()
    {
        var original = new ModSetting { ModRecordOverrideHandlingMode = null };
        var clone = RoundTrip(original);
        clone.ModRecordOverrideHandlingMode.Should().BeNull();
    }

    [Fact]
    public void ModSetting_EnumSerializedAsName_NotInteger()
    {
        var setting = new ModSetting { ModRecordOverrideHandlingMode = RecordOverrideHandlingMode.IncludeAsNew };
        var json = JSONhandler<ModSetting>.Serialize(setting, out var ok, out _);
        ok.Should().BeTrue();
        // StringEnumConverter is registered -> the enum is emitted by name.
        json.Should().Contain("IncludeAsNew");
        json.Should().NotContain("\"ModRecordOverrideHandlingMode\": 2");
    }

    [Fact]
    public void ModSetting_FormKeyAndModKey_SerializedAsStrings()
    {
        var setting = new ModSetting
        {
            CorrespondingModKeys = new List<ModKey> { ModA },
            NpcFormKeys = new HashSet<FormKey> { Npc1 },
        };
        var json = JSONhandler<ModSetting>.Serialize(setting, out var ok, out _);
        ok.Should().BeTrue();
        // Mutagen converters emit ModKey / FormKey as their canonical string forms.
        json.Should().Contain("ModA.esp");
        json.Should().Contain("000801:Skyrim.esm");
    }

    [Fact]
    public void ModSettingConverter_MigratesSingularMugShotFolderPath_ToList()
    {
        // The read-only ModSettingConverter migrates the legacy single-string property
        // "MugShotFolderPath" into the new "MugShotFolderPaths" list on deserialize.
        const string legacyJson = """
        {
          "DisplayName": "Legacy",
          "MugShotFolderPath": "C:\\Old\\Mugshots"
        }
        """;
        var migrated = JSONhandler<ModSetting>.Deserialize(legacyJson, out var ok, out var err);
        ok.Should().BeTrue("migration deserialize should succeed: {0}", err);
        migrated!.DisplayName.Should().Be("Legacy");
        migrated.MugShotFolderPaths.Should().ContainSingle().Which.Should().Be(@"C:\Old\Mugshots");
    }

    [Fact]
    public void ModSettingConverter_NewListWins_LegacySingularIgnoredWhenListPresent()
    {
        // When the new list already has entries, the legacy singular value is not merged in.
        const string mixedJson = """
        {
          "DisplayName": "Mixed",
          "MugShotFolderPath": "C:\\Old\\Mugshots",
          "MugShotFolderPaths": [ "C:\\New\\Mugshots" ]
        }
        """;
        var migrated = JSONhandler<ModSetting>.Deserialize(mixedJson, out var ok, out _);
        ok.Should().BeTrue();
        migrated!.MugShotFolderPaths.Should().Equal(@"C:\New\Mugshots");
    }

    [Fact]
    public void ModSettingConverter_LegacyMergeColor_SetsHasAlteredMergeLogic()
    {
        // Presence of the obsolete "MergeInLabelColor" implies the user altered merge logic.
        const string legacyJson = """
        {
          "DisplayName": "Colored",
          "MergeInLabelColor": "#FFAA0000"
        }
        """;
        var migrated = JSONhandler<ModSetting>.Deserialize(legacyJson, out var ok, out _);
        ok.Should().BeTrue();
        migrated!.HasAlteredMergeLogic.Should().BeTrue();
    }

    // ── NpcAppearanceData ──────────────────────────────────────────────────────

    [Fact]
    public void NpcAppearanceData_AllFields_SurviveRoundTrip()
    {
        var data = new NpcAppearanceData
        {
            ModName = "Pandorable",
            AppearancePlugin = ModA,
            OutputPlugin = ModB,
        };
        var clone = RoundTrip(data);

        clone.ModName.Should().Be("Pandorable");
        clone.AppearancePlugin.Should().Be(ModA);
        clone.OutputPlugin.Should().Be(ModB);
    }

    [Fact]
    public void NpcAppearanceData_DefaultModKeys_RoundTripToNullModKey()
    {
        var clone = RoundTrip(new NpcAppearanceData { ModName = "" });
        clone.ModName.Should().BeEmpty();
        clone.AppearancePlugin.Should().Be(default(ModKey));
        clone.OutputPlugin.Should().Be(default(ModKey));
    }

    // ── NpcToken ───────────────────────────────────────────────────────────────

    [Fact]
    public void NpcToken_FullGraph_SurvivesRoundTrip()
    {
        var token = new NpcToken
        {
            CreationDate = "2026-06-26T00:00:00Z",
            CreatedPlugins = new List<ModKey> { ModA, ModB, ModC },
            ProcessedNpcs = new Dictionary<FormKey, NpcAppearanceData>
            {
                [Npc1] = new() { ModName = "ModA", AppearancePlugin = ModA, OutputPlugin = ModB },
                [Npc2] = new() { ModName = "ModC", AppearancePlugin = ModC, OutputPlugin = ModB },
            },
        };

        var clone = RoundTrip(token);

        clone.CreationDate.Should().Be("2026-06-26T00:00:00Z");
        clone.CreatedPlugins.Should().Equal(ModA, ModB, ModC);
        clone.ProcessedNpcs.Should().HaveCount(2);
        clone.ProcessedNpcs.Should().ContainKey(Npc1);
        clone.ProcessedNpcs[Npc1].ModName.Should().Be("ModA");
        clone.ProcessedNpcs[Npc1].AppearancePlugin.Should().Be(ModA);
        clone.ProcessedNpcs[Npc1].OutputPlugin.Should().Be(ModB);
        clone.ProcessedNpcs[Npc2].AppearancePlugin.Should().Be(ModC);
    }

    [Fact]
    public void NpcToken_DictionaryFormKeyKeys_PreservedExactly()
    {
        var token = new NpcToken
        {
            ProcessedNpcs = new Dictionary<FormKey, NpcAppearanceData>
            {
                [Npc1] = new() { ModName = "A" },
                [Npc2] = new() { ModName = "B" },
                [Npc3] = new() { ModName = "C" },
            },
        };
        var clone = RoundTrip(token);

        clone.ProcessedNpcs.Keys.Should().BeEquivalentTo(new[] { Npc1, Npc2, Npc3 });
        // FormKey keys parse back into the same value type (deep, not stringly compared).
        clone.ProcessedNpcs.Should().ContainKey(Npc3);
        clone.ProcessedNpcs[Npc3].ModName.Should().Be("C");
    }

    [Fact]
    public void NpcToken_Clone_IsReferenceDistinctFromOriginal()
    {
        var token = new NpcToken
        {
            CreatedPlugins = new List<ModKey> { ModA },
            ProcessedNpcs = new Dictionary<FormKey, NpcAppearanceData>
            {
                [Npc1] = new() { ModName = "A", AppearancePlugin = ModA },
            },
        };
        var clone = RoundTrip(token);

        clone.Should().NotBeSameAs(token);
        clone.CreatedPlugins.Should().NotBeSameAs(token.CreatedPlugins);
        clone.ProcessedNpcs.Should().NotBeSameAs(token.ProcessedNpcs);
        clone.ProcessedNpcs[Npc1].Should().NotBeSameAs(token.ProcessedNpcs[Npc1]);

        clone.CreatedPlugins.Add(ModB);
        token.CreatedPlugins.Should().Equal(ModA);
    }

    [Fact]
    public void NpcToken_Empty_RoundTripsToEmpty()
    {
        var clone = RoundTrip(new NpcToken());
        clone.CreationDate.Should().BeEmpty();
        clone.CreatedPlugins.Should().NotBeNull().And.BeEmpty();
        clone.ProcessedNpcs.Should().NotBeNull().And.BeEmpty();
    }

    // ── CloneViaJSON convenience helper ────────────────────────────────────────

    [Fact]
    public void CloneViaJSON_ModSetting_ProducesEquivalentDistinctClone()
    {
        var original = MakeRichModSetting();
        var clone = JSONhandler<ModSetting>.CloneViaJSON(original);

        clone.Should().NotBeNull();
        clone.Should().NotBeSameAs(original);
        clone!.DisplayName.Should().Be(original.DisplayName);
        clone.NpcFormKeys.Should().BeEquivalentTo(original.NpcFormKeys);
        clone.AvailablePluginsForNpcs[Npc1].Should().Equal(original.AvailablePluginsForNpcs[Npc1]);
        clone.NpcFormKeysToNotifications[Npc1].ReferencedFormKey.Should().Be(Npc2);
        clone.NpcFormKeysToNotifications[Npc2].ReferencedFormKey.Should().BeNull();
    }

    [Fact]
    public void CloneViaJSON_NpcToken_ProducesEquivalentDistinctClone()
    {
        var token = new NpcToken
        {
            CreationDate = "x",
            CreatedPlugins = new List<ModKey> { ModA, ModB },
            ProcessedNpcs = new Dictionary<FormKey, NpcAppearanceData>
            {
                [Npc1] = new() { ModName = "A", AppearancePlugin = ModA, OutputPlugin = ModB },
            },
        };
        var clone = JSONhandler<NpcToken>.CloneViaJSON(token);

        clone.Should().NotBeNull();
        clone.Should().NotBeSameAs(token);
        clone!.CreatedPlugins.Should().Equal(ModA, ModB);
        clone.ProcessedNpcs.Should().NotBeSameAs(token.ProcessedNpcs);
        clone.ProcessedNpcs[Npc1].OutputPlugin.Should().Be(ModB);
    }

    [Fact]
    public void Settings_ManualAntlerHeadParts_SurviveRoundTrip()
    {
        var settings = new Settings
        {
            ManualAntlerBlockScope = AntlerBlockScope.SpecificNpc,
            ManualAntlerHeadParts = new List<ManualAntlerHeadPart>
            {
                new()
                {
                    EditorId = "000CotG_FaendalHairlineExtra04",
                    Sources =
                    {
                        new AntlerHeadPartSource { ModName = "FoxGlove", NpcFormKey = Npc1 },
                        new AntlerHeadPartSource { ModName = "OtherMod", NpcFormKey = Npc2 },
                    },
                },
            },
        };

        var clone = RoundTrip(settings);

        clone.ManualAntlerBlockScope.Should().Be(AntlerBlockScope.SpecificNpc);
        clone.ManualAntlerHeadParts.Should().ContainSingle();
        var entry = clone.ManualAntlerHeadParts[0];
        entry.EditorId.Should().Be("000CotG_FaendalHairlineExtra04");
        entry.Sources.Should().HaveCount(2);
        entry.Sources.Should().Contain(s => s.ModName == "FoxGlove" && s.NpcFormKey == Npc1);
        entry.Sources.Should().Contain(s => s.ModName == "OtherMod" && s.NpcFormKey == Npc2);
    }

    [Fact]
    public void Settings_ManualWigArmatures_SurviveRoundTrip()
    {
        var settings = new Settings
        {
            ManualWigBlockScope = AntlerBlockScope.SameMod,
            ManualWigArmatures = new List<ManualWigArmature>
            {
                new()
                {
                    EditorId = "0Sky205Addon",
                    Sources = { new WigArmatureSource { ModName = "HPNO", NpcFormKey = Npc1 } },
                },
            },
            ManualNonWigArmatures = new List<ManualWigArmature>
            {
                new()
                {
                    EditorId = "FeatherHoodAddon",
                    Sources = { new WigArmatureSource { ModName = "HPNO", NpcFormKey = Npc2 } },
                },
            },
        };

        var clone = RoundTrip(settings);

        clone.ManualWigBlockScope.Should().Be(AntlerBlockScope.SameMod);
        clone.ManualWigArmatures.Should().ContainSingle();
        clone.ManualWigArmatures[0].EditorId.Should().Be("0Sky205Addon");
        clone.ManualWigArmatures[0].Sources.Should().ContainSingle(
            s => s.ModName == "HPNO" && s.NpcFormKey == Npc1);
        clone.ManualNonWigArmatures.Should().ContainSingle();
        clone.ManualNonWigArmatures[0].EditorId.Should().Be("FeatherHoodAddon");
        clone.ManualNonWigArmatures[0].Sources.Should().ContainSingle(
            s => s.ModName == "HPNO" && s.NpcFormKey == Npc2);
    }

    [Fact]
    public void Settings_FavoriteFacesGroupAssignments_SurviveRoundTrip()
    {
        // The favorites group store is a List<FavoriteFaceGroupAssignment> rather than a
        // Dictionary<(FormKey, string), ...> precisely so it round-trips through Newtonsoft
        // (a ValueTuple dictionary key would be ToString()'d on write and not parse back).
        // This guards that the persisted favorite groups actually survive a save/load.
        var settings = new Settings
        {
            FavoriteFaces = new HashSet<(FormKey NpcFormKey, string ModName)>
            {
                (Npc1, "Pandorable"),
                (Npc2, "FoxGlove"),
            },
            FavoriteFacesGroupAssignments = new List<FavoriteFaceGroupAssignment>
            {
                new()
                {
                    NpcFormKey = Npc1,
                    ModName = "Pandorable",
                    Groups = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "Followers", "Housecarls" },
                },
                new()
                {
                    NpcFormKey = Npc2,
                    ModName = "FoxGlove",
                    Groups = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "Followers" },
                },
            },
        };

        var clone = RoundTrip(settings);

        // The favorite entries themselves (tuple set) survive.
        clone.FavoriteFaces.Should().Contain((Npc1, "Pandorable"));
        clone.FavoriteFaces.Should().Contain((Npc2, "FoxGlove"));

        // And each favorite's group memberships (keyed by source NPC + mod) survive.
        clone.FavoriteFacesGroupAssignments.Should().HaveCount(2);

        var first = clone.FavoriteFacesGroupAssignments.Single(a => a.NpcFormKey == Npc1 && a.ModName == "Pandorable");
        first.Groups.Should().BeEquivalentTo(new[] { "Followers", "Housecarls" });

        var second = clone.FavoriteFacesGroupAssignments.Single(a => a.NpcFormKey == Npc2 && a.ModName == "FoxGlove");
        second.Groups.Should().BeEquivalentTo(new[] { "Followers" });
    }
}
