using System.Collections.Generic;
using System.Linq;
using FluentAssertions;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Skyrim;
using NPC_Plugin_Chooser_2.BackEnd;
using NPC_Plugin_Chooser_2.Models;
using NPC_Plugin_Chooser_2.Tests.TestSupport;
using Xunit;

namespace NPC_Plugin_Chooser_2.Tests.Unit;

/// <summary>
/// <c>UpdateHandler.RepairSourcePluginDisambiguation</c> — the one-time fix for source-plugin
/// choices the pre-2.2.3 default rule got backwards.
///
/// <para><b>The bug.</b> When several of a mod entry's plugins carried the same NPC and all were
/// in the load order, the default picked the EARLIEST-loading one — the record the game overrides
/// — and persisted it indistinguishably from a hand-made choice. Worst hit is the synthetic
/// "Base Game" entry: every DLC-overridden vanilla NPC forwarded Skyrim.esm's record instead of
/// the DLC's. Dawnguard REMOVES MaleEyesHumanDemon from the vampires it overrides and regenerates
/// their FaceGen to match, so re-introducing that head part left the record naming a shape the
/// mesh no longer has — the dark-face bug, confirmed in game on EncVampire02BossBretonM. On the
/// measuring load order 124 of 124 persisted disambiguations were wrong.</para>
///
/// <para>In-memory settings and listings; no game install.</para>
/// </summary>
public class SourcePluginDisambiguationRepairTests
{
    private static readonly ModKey Skyrim = ModKey.FromFileName("Skyrim.esm");
    private static readonly ModKey Dawnguard = ModKey.FromFileName("Dawnguard.esm");
    private static readonly ModKey Dragonborn = ModKey.FromFileName("Dragonborn.esm");
    private static readonly ModKey Absent = ModKey.FromFileName("NotInstalled.esp");

    private static readonly FormKey Vampire = FormKey.Factory("02E1DC:Skyrim.esm");

    /// <summary>Load order: Skyrim -> Dawnguard -> Dragonborn.</summary>
    private static ModKey[] Env() => new[] { Skyrim, Dawnguard, Dragonborn };

    private static (Settings Settings, ModSetting Mod) SettingsWith(
        ModKey chosen, params ModKey[] sources)
    {
        var mod = new ModSetting { DisplayName = "Base Game", IsAutoGenerated = true };
        mod.AvailablePluginsForNpcs[Vampire] = sources.ToList();
        mod.NpcPluginDisambiguation[Vampire] = chosen;

        var settings = new Settings();
        settings.ModSettings.Add(mod);
        return (settings, mod);
    }

    /// <summary>Runs the pure core over one mod entry, against the given load order.</summary>
    private static void Repair(Settings settings, IEnumerable<ModKey> loadOrder)
    {
        var order = loadOrder.ToList();
        var position = new Dictionary<ModKey, int>();
        for (int i = 0; i < order.Count; i++) position[order[i]] = i;

        foreach (var mod in settings.ModSettings)
        {
            UpdateHandler.RepairDisambiguationMap(
                mod.NpcPluginDisambiguation, mod.AvailablePluginsForNpcs, position);
        }
    }

    [Fact]
    public void EarliestLoadingChoice_IsRewrittenToTheLoadOrderWinner()
    {
        // The measured specimen: Base Game pinned to Skyrim.esm when Dawnguard also carries it.
        var (settings, mod) = SettingsWith(chosen: Skyrim, Skyrim, Dawnguard);

        Repair(settings, Env());

        mod.NpcPluginDisambiguation[Vampire].Should().Be(Dawnguard);
    }

    [Fact]
    public void ChoiceAlreadyNamingTheWinner_IsLeftAlone()
    {
        var (settings, mod) = SettingsWith(chosen: Dawnguard, Skyrim, Dawnguard);

        Repair(settings, Env());

        mod.NpcPluginDisambiguation[Vampire].Should().Be(Dawnguard);
    }

    [Fact]
    public void WinnerIsTheLastLoading_NotMerelyLaterThanTheChoice()
    {
        var (settings, mod) = SettingsWith(chosen: Skyrim, Skyrim, Dawnguard, Dragonborn);

        Repair(settings, Env());

        mod.NpcPluginDisambiguation[Vampire].Should().Be(Dragonborn);
    }

    [Fact]
    public void EntryWithASourceOutsideTheLoadOrder_IsLeftAlone()
    {
        // That choice came from the master-depth / alphabetical fallbacks, not the inverted
        // comparison, so this repair has no business touching it.
        var (settings, mod) = SettingsWith(chosen: Skyrim, Skyrim, Absent);

        Repair(settings, Env());

        mod.NpcPluginDisambiguation[Vampire].Should().Be(Skyrim);
    }

    [Fact]
    public void EntryWithASingleSource_IsLeftAlone()
    {
        var (settings, mod) = SettingsWith(chosen: Skyrim, Skyrim);

        Repair(settings, Env());

        mod.NpcPluginDisambiguation[Vampire].Should().Be(Skyrim);
    }

    [Fact]
    public void DisambiguationWithNoRecordedSources_IsLeftAlone()
    {
        var mod = new ModSetting { DisplayName = "Base Game" };
        mod.NpcPluginDisambiguation[Vampire] = Skyrim; // no AvailablePluginsForNpcs entry
        var settings = new Settings();
        settings.ModSettings.Add(mod);

        Repair(settings, Env());

        mod.NpcPluginDisambiguation[Vampire].Should().Be(Skyrim);
    }

    [Fact]
    public void RepairIsIdempotent()
    {
        // ProgramVersion lags the in-development version, so this migration re-fires on every
        // prerelease launch. A second pass must be a no-op.
        var (settings, mod) = SettingsWith(chosen: Skyrim, Skyrim, Dawnguard);

        Repair(settings, Env());
        Repair(settings, Env());

        mod.NpcPluginDisambiguation[Vampire].Should().Be(Dawnguard);
    }

    [Fact]
    public void RepairsAnyMapItIsGiven_NotJustThePersistedModel()
    {
        // The reason the first attempt appeared to do nothing: VM_ModSetting COPIES both
        // dictionaries out of its model on load and writes them back on save, so repairing only
        // the model was undone by the next save. The core takes the map to fix, and the caller
        // runs it over the view models as well.
        var vmDisambiguation = new Dictionary<FormKey, ModKey> { [Vampire] = Skyrim };
        var vmAvailable = new Dictionary<FormKey, List<ModKey>>
        {
            [Vampire] = new() { Skyrim, Dawnguard }
        };
        var position = new Dictionary<ModKey, int> { [Skyrim] = 0, [Dawnguard] = 1 };

        var repaired = UpdateHandler.RepairDisambiguationMap(vmDisambiguation, vmAvailable, position);

        repaired.Should().Be(1);
        vmDisambiguation[Vampire].Should().Be(Dawnguard);
    }

    [Fact]
    public void ReturnsTheNumberRepaired()
    {
        var disambiguation = new Dictionary<FormKey, ModKey> { [Vampire] = Dawnguard };
        var available = new Dictionary<FormKey, List<ModKey>>
        {
            [Vampire] = new() { Skyrim, Dawnguard }
        };
        var position = new Dictionary<ModKey, int> { [Skyrim] = 0, [Dawnguard] = 1 };

        UpdateHandler.RepairDisambiguationMap(disambiguation, available, position)
            .Should().Be(0, "the entry already names the winner");
    }

    [Fact]
    public void NoLoadOrder_LeavesEverythingAlone()
    {
        // Better to leave a wrong value than to rewrite it against an empty order.
        var (settings, mod) = SettingsWith(chosen: Skyrim, Skyrim, Dawnguard);

        Repair(settings, System.Array.Empty<ModKey>());

        mod.NpcPluginDisambiguation[Vampire].Should().Be(Skyrim);
    }
}
