using System.Diagnostics;
using System.Windows.Media;
using Mutagen.Bethesda.Plugins;
using Newtonsoft.Json;
using NPC_Plugin_Chooser_2.View_Models;

namespace NPC_Plugin_Chooser_2.Models;

/// <summary>Which record source supplies a wig carried by a specific NPC:
/// a hair-slot ArmorAddon in the NPC's WornArmor (WNAM / skin-carried), or a
/// wig ARMO in the NPC's Default Outfit. Drives the mugshot tile's per-source
/// tooltip wording.</summary>
public enum NpcWigSourceKind
{
    WornArmor,
    Outfit
}

/// <summary>One wig-relevant record association for one NPC, emitted by the
/// analysis scan (<c>WigDetector.Scan</c>) and persisted in
/// <see cref="ModSetting.NpcWigSources"/>. This records only the NPC→record
/// ASSOCIATION (the part that is expensive to recompute live); wig
/// CLASSIFICATION stays with the detection sets + manual designation lists and
/// is folded in at read time by <see cref="Settings.GetEffectiveNpcWigSources"/>,
/// so a 3D-preview designation changes the effective result without a
/// re-scan. WornArmor entries are candidates (every plausible hair-slot ARMA,
/// detected or not — what makes read-time manual promotion possible);
/// Outfit entries are scan-detected wig ARMOs.</summary>
public class NpcWigSource
{
    public NpcWigSourceKind Kind { get; set; }
    /// <summary>The ARMA (WornArmor) or ARMO (Outfit) FormKey. The
    /// classification key for detection-set membership.</summary>
    public FormKey RecordFormKey { get; set; }
    /// <summary>The record's EditorID — the manual-designation key for
    /// WornArmor candidates (<see cref="Settings.IsWigArmature"/>), display
    /// detail for Outfit entries.</summary>
    public string EditorId { get; set; } = string.Empty;
}

[DebuggerDisplay("{DisplayName}")]
public class ModSetting
{
    public string DisplayName { get; set; } = string.Empty;
    public List<ModKey> CorrespondingModKeys { get; set; } = new();
    public HashSet<ModKey> ResourceOnlyModKeys { get; set; } = new();
    public List<string> CorrespondingFolderPaths { get; set; } = new(); // first should be the base mod, and others are overrides where the program should find conflict winning data if it exists

    /// <summary>
    /// Subset of <see cref="CorrespondingFolderPaths"/> that a Refresh must never drop.
    ///
    /// <para>Some mods have "silent" dependencies — folders that supply meshes/textures but carry no
    /// plugin, so nothing in the master chain that <c>VM_Mods.FindAndAddMissingMasters</c> walks points
    /// at them. <c>VM_Mods.CleanupCorrespondingFolders</c> rebuilds the folder list from that chain and
    /// would silently discard them. Locking pins a folder through the rebuild, at its original relative
    /// position (see <c>LockedFolderOrdering</c>).</para>
    ///
    /// <para>Folders the user adds by hand are locked by default, since a manual add is by definition
    /// something the detector did not find on its own.</para>
    /// </summary>
    public List<string> LockedFolderPaths { get; set; } = new();

    public List<string> MugShotFolderPaths { get; set; } = new();
    public bool IsFaceGenOnlyEntry { get; set; } = false;
    public HashSet<FormKey> FaceGenOnlyNpcFormKeys { get; set; } = new();
    public bool IsAutoGenerated { get; set; } = false;
    public HashSet<FormKey> NpcFormKeys { get; set; } = new(); // All NPCs contained in this mod
    public Dictionary<FormKey, List<ModKey>> AvailablePluginsForNpcs { get; set; } = new(); // Maps all available CorrespondingModKeys that can be used as a source plugin for this ModSetting
    public HashSet<FormKey> AmbiguousNpcFormKeys { get; set; } = new(); // All NPCs with > 1 available plugins
    public Dictionary<FormKey, ModKey> NpcPluginDisambiguation { get; set; } = new(); // Maps NPC FormKey to the ModKey from which it should inherit data, specifically for NPCs appearing in multiple plugins within this ModSetting.
    public Dictionary<FormKey, string> NpcFormKeysToDisplayName { get; set; } = new();

    public bool MergeInDependencyRecords { get; set; } = true;

    // Per-plugin merge-in overrides, set from the "Set Resource-Only Plugins" dialog.
    // SPARSE and tri-state by design: a plugin absent from this map follows the default
    // rule in MergeEligibility (non-resource plugins mirror MergeInDependencyRecords;
    // resource-only plugins inherit from the mod entry that owns them, or default to
    // merging). Storing only explicit choices keeps those defaults live, so flipping a
    // mod's own Merge Dependencies still propagates to the resource plugins it owns.
    public Dictionary<ModKey, bool> PluginMergeInOverrides { get; set; } = new();

    public bool HasAlteredMergeLogic { get; set; } = false;
    public bool HandleInjectedRecords { get; set; } = false;
    public bool HasAlteredHandleInjectedRecordsLogic { get; set; } = false;
    public HashSet<string> Keywords { get; set; } = new();
    
    [JsonIgnore]
    public static string DefaultRecordInjectionToolTip =
        "If checked, the patcher will search for and merge in records that are injected. This can potentially make patching take longer.";
    public string HandleInjectedOverridesToolTip { get; set; } = DefaultRecordInjectionToolTip;

    [JsonIgnore] 
    public static string DefaultMergeInTooltip =
        "If checked, all records needed by the mod will be merged into the output." +
        Environment.NewLine + "The output plugin will no longer depend on them as masters." +
        Environment.NewLine + "Only masters found within this mod's Mod Folders will be merged in." +
        Environment.NewLine + "Do not merge in records from plugins that are going to be kept in your load order.";
    
    public string MergeInToolTip { get; set; } = DefaultMergeInTooltip;

    public RecordOverrideHandlingMode? ModRecordOverrideHandlingMode { get; set; } = RecordOverrideHandlingMode.Ignore;

    /// <summary>
    /// Which NPC fields the override-discovery walk may start from for this mod (the "Override
    /// Roots" dialog). Null means "use <see cref="Settings.DefaultOverrideTraversalRoots"/>", so a
    /// mod that was never customised keeps following the global default as it changes — the same
    /// contract <see cref="PluginMergeInOverrides"/> uses for merge-in.
    ///
    /// <para>Roots only: a checked field is followed to unlimited depth through any record type.
    /// Discovery used to root on every link the NPC record carried, which walked out through AI
    /// packages into cells, placed references and quests and copied their whole ancestry into the
    /// output as private duplicates. The default set is appearance-only; anything a specific mod
    /// genuinely needs beyond that can be ticked back on here rather than guessed at globally.</para>
    /// </summary>
    public HashSet<NpcRootField>? OverrideTraversalRoots { get; set; } = null;

    public int MaxNestedIntervalDepth { get; set; } = 2;
    public bool IncludeAllOverrides { get; set; } = false;
    public HashSet<ModKey> PluginsWithOverrideRecords { get; set; } = new();
    public bool IncludeOutfits { get; set; } = false;
    public bool CopyAssets { get; set; } = true;

    // Base-game-overwrite protection: some mods ship assets at the same data-relative paths as
    // base game / Creation Club assets (e.g. loose skin textures in overhauls like Cathedral HMB).
    // Copying those into the output would override the user's installed replacers (skin mods etc.)
    // game-wide, so the patcher skips them unless the user opts in per mod. FaceGen files are
    // exempt — they are inherently per-NPC and must live at their vanilla-derived paths.
    // OverwriteBaseGameAssets is the user's opt-in; HasBaseGameAssetPaths/BaseGameAssetPathCount
    // are the scan result (computed on import/refresh, not per launch) that controls whether the
    // checkbox is shown. The patcher-side skip is a live path test independent of the scan result.
    public bool OverwriteBaseGameAssets { get; set; } = false;
    public bool HasBaseGameAssetPaths { get; set; } = false;
    public int BaseGameAssetPathCount { get; set; } = 0;

    // Wig/antler detection results (computed during mod analysis on cache miss,
    // persisted so cache hits keep them — same lifecycle as HasBaseGameAssetPaths).
    // Wigs are detected from two sources:
    //   DetectedWigArmors        — ARMOs whose Name contains "wig"/"hair" AND whose
    //                              ARMA(s) occupy a hair biped slot (31 Hair /
    //                              41 LongHair), carried in an outfit.
    //   DetectedWigArmatures     — hair-slot ARMAs carried directly in an NPC's
    //                              WornArmor (WNAM; the High Poly NPC Overhaul
    //                              bald-FaceGen + skin-hair pattern), slot-first
    //                              NPC-scoped detection plus a keyword pass.
    //                              Manual is/is-not designations
    //                              (Settings.IsWigArmature) refine this set at
    //                              consumption time.
    // Antlers are detected from three sources so Remove can reach all of them:
    //   DetectedAntlerArmors     — ARMOs whose EditorID/Name contains "antler"
    //                              (in an outfit; no slot guard).
    //   DetectedAntlerArmatures  — ARMAs whose EditorID contains "antler" (baked
    //                              into a WornArmor) plus the addons of the antler
    //                              ARMOs above.
    //   DetectedAntlerHeadParts  — HeadParts whose Name/EditorID contains "antler"
    //                              (baked into the FaceGen).
    // ModWigHandlingMode / ModAntlerHandlingMode: per-mod overrides of the global
    // Settings.DefaultWigHandlingMode / DefaultAntlerHandlingMode (null = default).
    public HashSet<FormKey> DetectedWigArmors { get; set; } = new();
    public HashSet<FormKey> DetectedWigArmatures { get; set; } = new();
    public HashSet<FormKey> DetectedAntlerArmors { get; set; } = new();
    public HashSet<FormKey> DetectedAntlerArmatures { get; set; } = new();
    public HashSet<FormKey> DetectedAntlerHeadParts { get; set; } = new();
    // Per-NPC wig-source map (same scan/persistence lifecycle as the detection
    // sets above): NPC FormKey → the wig-relevant records that NPC actually
    // carries. Only the NPC→record association is stored; whether each entry
    // is an EFFECTIVE wig is decided at read time from the detection sets +
    // manual designations (Settings.GetEffectiveNpcWigSources), keeping the
    // mugshot tile's "has wig" badge a pure record-derived lookup with no
    // live plugin resolution. Sparse: NPCs with no plausible wig records
    // have no entry.
    public Dictionary<FormKey, List<NpcWigSource>> NpcWigSources { get; set; } = new();
    public WigHandlingMode? ModWigHandlingMode { get; set; } = null;
    public AntlerHandlingMode? ModAntlerHandlingMode { get; set; } = null;

    /// <summary>Per-mod override of <see cref="Settings.DefaultWigHairTintMode"/>
    /// (null = use the global default). Only meaningful when this mod's
    /// effective wig mode is <see cref="WigHandlingMode.ConvertToHeadParts"/>.</summary>
    public WigHairTintMode? ModWigHairTintMode { get; set; } = null;

    /// <summary>Per-mod override of the global <see cref="Settings.TemplateHandlingMode"/>
    /// (null = use the global setting). Resolved by
    /// <see cref="Settings.GetEffectiveTemplateHandlingMode"/>; only shown in the UI when
    /// this mod provides Traits-templated NPCs (<see cref="HasTemplatedNpcs"/>).</summary>
    public TemplateHandlingMode? ModTemplateHandlingMode { get; set; } = null;

    [JsonIgnore]
    public bool HasWigArmors => DetectedWigArmors.Count > 0;

    /// <summary>Antler counterpart of <see cref="HasWigArmors"/>: outfit-carried
    /// antler ARMOs only (source 1), NOT the ARMA/HeadPart sources folded into
    /// <see cref="HasDetectedAntlers"/>. Those are the only antlers a mugshot
    /// depicts through the outfit walk, so this is the cheap precheck for the
    /// depiction paths (mesh-plan bail, identity-stamp bail).</summary>
    [JsonIgnore]
    public bool HasAntlerArmors => DetectedAntlerArmors.Count > 0;

    /// <summary>Whether the analysis SCAN detected wigs from either source
    /// (outfit ARMOs or WNAM-carried hair ARMAs). User designations (persisted
    /// on <see cref="Settings.ManualWigArmatures"/>) are folded in by
    /// <see cref="Settings.ModHasWigs"/> — use that for effective checks.</summary>
    [JsonIgnore]
    public bool HasWigSources => DetectedWigArmors.Count > 0 || DetectedWigArmatures.Count > 0;

    /// <summary>Whether the analysis SCAN detected antlers (any of the three
    /// sources). User-designated antlers (persisted on
    /// <see cref="Settings.ManualAntlerHeadParts"/>) are folded in by
    /// <see cref="Settings.ModHasAntlers"/> — use that for effective checks.</summary>
    [JsonIgnore]
    public bool HasDetectedAntlers => DetectedAntlerArmors.Count > 0 ||
                                      DetectedAntlerArmatures.Count > 0 ||
                                      DetectedAntlerHeadParts.Count > 0;

    [JsonIgnore]
    public bool HasAntlers => HasDetectedAntlers;

    /// <summary>Whether this mod provides any Traits-templated NPCs, per the analysis
    /// scan's persisted per-NPC notifications (same lifecycle as the wig/antler detection
    /// sets: computed on cache miss, persisted so cache hits keep it). Gates the per-mod
    /// Templated NPCs dropdown.</summary>
    [JsonIgnore]
    public bool HasTemplatedNpcs =>
        NpcFormKeysToNotifications.Values.Any(n => n.IssueType == NpcIssueType.Template);

    public Dictionary<FormKey, (NpcIssueType IssueType, string IssueMessage, FormKey? ReferencedFormKey)> 
        NpcFormKeysToNotifications
    {
        get;
        set;
    } = new();
    public ModStateSnapshot? LastKnownState { get; set; }
}